// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "BackendService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::starrocks;

class BackendServiceHandler : virtual public BackendServiceIf {
 public:
  BackendServiceHandler() {
    // Your initialization goes here
  }

  void exec_plan_fragment( ::starrocks::TExecPlanFragmentResult& _return, const  ::starrocks::TExecPlanFragmentParams& params) {
    // Your implementation goes here
    printf("exec_plan_fragment\n");
  }

  void cancel_plan_fragment( ::starrocks::TCancelPlanFragmentResult& _return, const  ::starrocks::TCancelPlanFragmentParams& params) {
    // Your implementation goes here
    printf("cancel_plan_fragment\n");
  }

  void transmit_data( ::starrocks::TTransmitDataResult& _return, const  ::starrocks::TTransmitDataParams& params) {
    // Your implementation goes here
    printf("transmit_data\n");
  }

  void fetch_data( ::starrocks::TFetchDataResult& _return, const  ::starrocks::TFetchDataParams& params) {
    // Your implementation goes here
    printf("fetch_data\n");
  }

  void submit_tasks( ::starrocks::TAgentResult& _return, const std::vector< ::starrocks::TAgentTaskRequest> & tasks) {
    // Your implementation goes here
    printf("submit_tasks\n");
  }

  void make_snapshot( ::starrocks::TAgentResult& _return, const  ::starrocks::TSnapshotRequest& snapshot_request) {
    // Your implementation goes here
    printf("make_snapshot\n");
  }

  void release_snapshot( ::starrocks::TAgentResult& _return, const std::string& snapshot_path) {
    // Your implementation goes here
    printf("release_snapshot\n");
  }

  void publish_cluster_state( ::starrocks::TAgentResult& _return, const  ::starrocks::TAgentPublishRequest& request) {
    // Your implementation goes here
    printf("publish_cluster_state\n");
  }

  void submit_etl_task( ::starrocks::TAgentResult& _return, const  ::starrocks::TMiniLoadEtlTaskRequest& request) {
    // Your implementation goes here
    printf("submit_etl_task\n");
  }

  void get_etl_status( ::starrocks::TMiniLoadEtlStatusResult& _return, const  ::starrocks::TMiniLoadEtlStatusRequest& request) {
    // Your implementation goes here
    printf("get_etl_status\n");
  }

  void delete_etl_files( ::starrocks::TAgentResult& _return, const  ::starrocks::TDeleteEtlFilesRequest& request) {
    // Your implementation goes here
    printf("delete_etl_files\n");
  }

  void submit_export_task( ::starrocks::TStatus& _return, const TExportTaskRequest& request) {
    // Your implementation goes here
    printf("submit_export_task\n");
  }

  void get_export_status( ::starrocks::TExportStatusResult& _return, const  ::starrocks::TUniqueId& task_id) {
    // Your implementation goes here
    printf("get_export_status\n");
  }

  void erase_export_task( ::starrocks::TStatus& _return, const  ::starrocks::TUniqueId& task_id) {
    // Your implementation goes here
    printf("erase_export_task\n");
  }

  void get_tablet_stat(TTabletStatResult& _return) {
    // Your implementation goes here
    printf("get_tablet_stat\n");
  }

  void submit_routine_load_task( ::starrocks::TStatus& _return, const std::vector<TRoutineLoadTask> & tasks) {
    // Your implementation goes here
    printf("submit_routine_load_task\n");
  }

  void finish_stream_load_channel( ::starrocks::TStatus& _return, const TStreamLoadChannel& stream_load_channel) {
    // Your implementation goes here
    printf("finish_stream_load_channel\n");
  }

  void open_scanner( ::starrocks::TScanOpenResult& _return, const  ::starrocks::TScanOpenParams& params) {
    // Your implementation goes here
    printf("open_scanner\n");
  }

  void get_next( ::starrocks::TScanBatchResult& _return, const  ::starrocks::TScanNextBatchParams& params) {
    // Your implementation goes here
    printf("get_next\n");
  }

  void close_scanner( ::starrocks::TScanCloseResult& _return, const  ::starrocks::TScanCloseParams& params) {
    // Your implementation goes here
    printf("close_scanner\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<BackendServiceHandler> handler(new BackendServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new BackendServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

