/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Data_TYPES_H
#define Data_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>
#include "Types_types.h"


namespace starrocks {

class TRowBatch;

class TColumnValue;

class TResultRow;

class TResultBatch;

class TGlobalDict;

class TStatisticData;

class TVariableData;

class TIcebergMetadata;

class TMetadataEntry;

typedef struct _TRowBatch__isset {
  _TRowBatch__isset() : tuple_offsets(false), tuple_data(false), is_compressed(false), be_number(false), packet_seq(false) {}
  bool tuple_offsets :1;
  bool tuple_data :1;
  bool is_compressed :1;
  bool be_number :1;
  bool packet_seq :1;
} _TRowBatch__isset;

class TRowBatch : public virtual ::apache::thrift::TBase {
 public:

  TRowBatch(const TRowBatch&);
  TRowBatch& operator=(const TRowBatch&);
  TRowBatch() noexcept;

  virtual ~TRowBatch() noexcept;
  int32_t num_rows;
  std::vector< ::starrocks::TTupleId>  row_tuples;
  std::vector<int32_t>  tuple_offsets;
  std::string tuple_data;
  bool is_compressed;
  int32_t be_number;
  int64_t packet_seq;

  _TRowBatch__isset __isset;

  void __set_num_rows(const int32_t val);

  void __set_row_tuples(const std::vector< ::starrocks::TTupleId> & val);

  void __set_tuple_offsets(const std::vector<int32_t> & val);

  void __set_tuple_data(const std::string& val);

  void __set_is_compressed(const bool val);

  void __set_be_number(const int32_t val);

  void __set_packet_seq(const int64_t val);

  bool operator == (const TRowBatch & rhs) const;
  bool operator != (const TRowBatch &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TRowBatch & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TRowBatch &a, TRowBatch &b);

std::ostream& operator<<(std::ostream& out, const TRowBatch& obj);

typedef struct _TColumnValue__isset {
  _TColumnValue__isset() : boolVal(false), intVal(false), longVal(false), doubleVal(false), stringVal(false) {}
  bool boolVal :1;
  bool intVal :1;
  bool longVal :1;
  bool doubleVal :1;
  bool stringVal :1;
} _TColumnValue__isset;

class TColumnValue : public virtual ::apache::thrift::TBase {
 public:

  TColumnValue(const TColumnValue&);
  TColumnValue& operator=(const TColumnValue&);
  TColumnValue() noexcept;

  virtual ~TColumnValue() noexcept;
  bool boolVal;
  int32_t intVal;
  int64_t longVal;
  double doubleVal;
  std::string stringVal;

  _TColumnValue__isset __isset;

  void __set_boolVal(const bool val);

  void __set_intVal(const int32_t val);

  void __set_longVal(const int64_t val);

  void __set_doubleVal(const double val);

  void __set_stringVal(const std::string& val);

  bool operator == (const TColumnValue & rhs) const;
  bool operator != (const TColumnValue &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TColumnValue & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TColumnValue &a, TColumnValue &b);

std::ostream& operator<<(std::ostream& out, const TColumnValue& obj);

typedef struct _TResultRow__isset {
  _TResultRow__isset() : colVals(false) {}
  bool colVals :1;
} _TResultRow__isset;

class TResultRow : public virtual ::apache::thrift::TBase {
 public:

  TResultRow(const TResultRow&);
  TResultRow& operator=(const TResultRow&);
  TResultRow() noexcept;

  virtual ~TResultRow() noexcept;
  std::vector<TColumnValue>  colVals;

  _TResultRow__isset __isset;

  void __set_colVals(const std::vector<TColumnValue> & val);

  bool operator == (const TResultRow & rhs) const;
  bool operator != (const TResultRow &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TResultRow & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TResultRow &a, TResultRow &b);

std::ostream& operator<<(std::ostream& out, const TResultRow& obj);

typedef struct _TResultBatch__isset {
  _TResultBatch__isset() : statistic_version(false) {}
  bool statistic_version :1;
} _TResultBatch__isset;

class TResultBatch : public virtual ::apache::thrift::TBase {
 public:

  TResultBatch(const TResultBatch&);
  TResultBatch& operator=(const TResultBatch&);
  TResultBatch() noexcept;

  virtual ~TResultBatch() noexcept;
  std::vector<std::string>  rows;
  bool is_compressed;
  int64_t packet_seq;
  int32_t statistic_version;

  _TResultBatch__isset __isset;

  void __set_rows(const std::vector<std::string> & val);

  void __set_is_compressed(const bool val);

  void __set_packet_seq(const int64_t val);

  void __set_statistic_version(const int32_t val);

  bool operator == (const TResultBatch & rhs) const;
  bool operator != (const TResultBatch &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TResultBatch & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TResultBatch &a, TResultBatch &b);

std::ostream& operator<<(std::ostream& out, const TResultBatch& obj);

typedef struct _TGlobalDict__isset {
  _TGlobalDict__isset() : columnId(false), strings(false), ids(false), version(false) {}
  bool columnId :1;
  bool strings :1;
  bool ids :1;
  bool version :1;
} _TGlobalDict__isset;

class TGlobalDict : public virtual ::apache::thrift::TBase {
 public:

  TGlobalDict(const TGlobalDict&);
  TGlobalDict& operator=(const TGlobalDict&);
  TGlobalDict() noexcept;

  virtual ~TGlobalDict() noexcept;
  int32_t columnId;
  std::vector<std::string>  strings;
  std::vector<int32_t>  ids;
  int64_t version;

  _TGlobalDict__isset __isset;

  void __set_columnId(const int32_t val);

  void __set_strings(const std::vector<std::string> & val);

  void __set_ids(const std::vector<int32_t> & val);

  void __set_version(const int64_t val);

  bool operator == (const TGlobalDict & rhs) const;
  bool operator != (const TGlobalDict &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TGlobalDict & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TGlobalDict &a, TGlobalDict &b);

std::ostream& operator<<(std::ostream& out, const TGlobalDict& obj);

typedef struct _TStatisticData__isset {
  _TStatisticData__isset() : updateTime(false), dbId(false), tableId(false), columnName(false), rowCount(false), dataSize(false), countDistinct(false), nullCount(false), max(false), min(false), histogram(false), dict(false), meta_version(false), partitionId(false), hll(false), partitionName(false) {}
  bool updateTime :1;
  bool dbId :1;
  bool tableId :1;
  bool columnName :1;
  bool rowCount :1;
  bool dataSize :1;
  bool countDistinct :1;
  bool nullCount :1;
  bool max :1;
  bool min :1;
  bool histogram :1;
  bool dict :1;
  bool meta_version :1;
  bool partitionId :1;
  bool hll :1;
  bool partitionName :1;
} _TStatisticData__isset;

class TStatisticData : public virtual ::apache::thrift::TBase {
 public:

  TStatisticData(const TStatisticData&);
  TStatisticData& operator=(const TStatisticData&);
  TStatisticData() noexcept;

  virtual ~TStatisticData() noexcept;
  std::string updateTime;
  int64_t dbId;
  int64_t tableId;
  std::string columnName;
  int64_t rowCount;
  double dataSize;
  int64_t countDistinct;
  int64_t nullCount;
  std::string max;
  std::string min;
  std::string histogram;
  TGlobalDict dict;
  int64_t meta_version;
  int64_t partitionId;
  std::string hll;
  std::string partitionName;

  _TStatisticData__isset __isset;

  void __set_updateTime(const std::string& val);

  void __set_dbId(const int64_t val);

  void __set_tableId(const int64_t val);

  void __set_columnName(const std::string& val);

  void __set_rowCount(const int64_t val);

  void __set_dataSize(const double val);

  void __set_countDistinct(const int64_t val);

  void __set_nullCount(const int64_t val);

  void __set_max(const std::string& val);

  void __set_min(const std::string& val);

  void __set_histogram(const std::string& val);

  void __set_dict(const TGlobalDict& val);

  void __set_meta_version(const int64_t val);

  void __set_partitionId(const int64_t val);

  void __set_hll(const std::string& val);

  void __set_partitionName(const std::string& val);

  bool operator == (const TStatisticData & rhs) const;
  bool operator != (const TStatisticData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TStatisticData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TStatisticData &a, TStatisticData &b);

std::ostream& operator<<(std::ostream& out, const TStatisticData& obj);

typedef struct _TVariableData__isset {
  _TVariableData__isset() : isNull(false), result(false) {}
  bool isNull :1;
  bool result :1;
} _TVariableData__isset;

class TVariableData : public virtual ::apache::thrift::TBase {
 public:

  TVariableData(const TVariableData&);
  TVariableData& operator=(const TVariableData&);
  TVariableData() noexcept;

  virtual ~TVariableData() noexcept;
  bool isNull;
  std::string result;

  _TVariableData__isset __isset;

  void __set_isNull(const bool val);

  void __set_result(const std::string& val);

  bool operator == (const TVariableData & rhs) const;
  bool operator != (const TVariableData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TVariableData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TVariableData &a, TVariableData &b);

std::ostream& operator<<(std::ostream& out, const TVariableData& obj);

typedef struct _TIcebergMetadata__isset {
  _TIcebergMetadata__isset() : content(false), file_path(false), file_format(false), spec_id(false), partition_data(false), record_count(false), file_size_in_bytes(false), split_offsets(false), sort_id(false), equality_ids(false), file_sequence_number(false), data_sequence_number(false), column_stats(false), key_metadata(false) {}
  bool content :1;
  bool file_path :1;
  bool file_format :1;
  bool spec_id :1;
  bool partition_data :1;
  bool record_count :1;
  bool file_size_in_bytes :1;
  bool split_offsets :1;
  bool sort_id :1;
  bool equality_ids :1;
  bool file_sequence_number :1;
  bool data_sequence_number :1;
  bool column_stats :1;
  bool key_metadata :1;
} _TIcebergMetadata__isset;

class TIcebergMetadata : public virtual ::apache::thrift::TBase {
 public:

  TIcebergMetadata(const TIcebergMetadata&);
  TIcebergMetadata& operator=(const TIcebergMetadata&);
  TIcebergMetadata() noexcept;

  virtual ~TIcebergMetadata() noexcept;
  int32_t content;
  std::string file_path;
  std::string file_format;
  int32_t spec_id;
  std::string partition_data;
  int64_t record_count;
  int64_t file_size_in_bytes;
  std::vector<int64_t>  split_offsets;
  int32_t sort_id;
  std::vector<int32_t>  equality_ids;
  int64_t file_sequence_number;
  int64_t data_sequence_number;
  std::string column_stats;
  std::string key_metadata;

  _TIcebergMetadata__isset __isset;

  void __set_content(const int32_t val);

  void __set_file_path(const std::string& val);

  void __set_file_format(const std::string& val);

  void __set_spec_id(const int32_t val);

  void __set_partition_data(const std::string& val);

  void __set_record_count(const int64_t val);

  void __set_file_size_in_bytes(const int64_t val);

  void __set_split_offsets(const std::vector<int64_t> & val);

  void __set_sort_id(const int32_t val);

  void __set_equality_ids(const std::vector<int32_t> & val);

  void __set_file_sequence_number(const int64_t val);

  void __set_data_sequence_number(const int64_t val);

  void __set_column_stats(const std::string& val);

  void __set_key_metadata(const std::string& val);

  bool operator == (const TIcebergMetadata & rhs) const;
  bool operator != (const TIcebergMetadata &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TIcebergMetadata & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TIcebergMetadata &a, TIcebergMetadata &b);

std::ostream& operator<<(std::ostream& out, const TIcebergMetadata& obj);

typedef struct _TMetadataEntry__isset {
  _TMetadataEntry__isset() : iceberg_metadata(false) {}
  bool iceberg_metadata :1;
} _TMetadataEntry__isset;

class TMetadataEntry : public virtual ::apache::thrift::TBase {
 public:

  TMetadataEntry(const TMetadataEntry&);
  TMetadataEntry& operator=(const TMetadataEntry&);
  TMetadataEntry() noexcept;

  virtual ~TMetadataEntry() noexcept;
  TIcebergMetadata iceberg_metadata;

  _TMetadataEntry__isset __isset;

  void __set_iceberg_metadata(const TIcebergMetadata& val);

  bool operator == (const TMetadataEntry & rhs) const;
  bool operator != (const TMetadataEntry &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TMetadataEntry & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TMetadataEntry &a, TMetadataEntry &b);

std::ostream& operator<<(std::ostream& out, const TMetadataEntry& obj);

} // namespace

#endif
