/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Data_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace starrocks {


TRowBatch::~TRowBatch() noexcept {
}

TRowBatch::TRowBatch() noexcept
   : num_rows(0),
     tuple_data(),
     is_compressed(0),
     be_number(0),
     packet_seq(0) {
}

void TRowBatch::__set_num_rows(const int32_t val) {
  this->num_rows = val;
}

void TRowBatch::__set_row_tuples(const std::vector< ::starrocks::TTupleId> & val) {
  this->row_tuples = val;
}

void TRowBatch::__set_tuple_offsets(const std::vector<int32_t> & val) {
  this->tuple_offsets = val;
}

void TRowBatch::__set_tuple_data(const std::string& val) {
  this->tuple_data = val;
}

void TRowBatch::__set_is_compressed(const bool val) {
  this->is_compressed = val;
}

void TRowBatch::__set_be_number(const int32_t val) {
  this->be_number = val;
}

void TRowBatch::__set_packet_seq(const int64_t val) {
  this->packet_seq = val;
}
std::ostream& operator<<(std::ostream& out, const TRowBatch& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TRowBatch::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_num_rows = false;
  bool isset_row_tuples = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->num_rows);
          isset_num_rows = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->row_tuples.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->row_tuples.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += iprot->readI32(this->row_tuples[_i4]);
            }
            xfer += iprot->readListEnd();
          }
          isset_row_tuples = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->tuple_offsets.clear();
            uint32_t _size5;
            ::apache::thrift::protocol::TType _etype8;
            xfer += iprot->readListBegin(_etype8, _size5);
            this->tuple_offsets.resize(_size5);
            uint32_t _i9;
            for (_i9 = 0; _i9 < _size5; ++_i9)
            {
              xfer += iprot->readI32(this->tuple_offsets[_i9]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.tuple_offsets = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->tuple_data);
          this->__isset.tuple_data = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->is_compressed);
          this->__isset.is_compressed = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->be_number);
          this->__isset.be_number = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->packet_seq);
          this->__isset.packet_seq = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_num_rows)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_row_tuples)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TRowBatch::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TRowBatch");

  xfer += oprot->writeFieldBegin("num_rows", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->num_rows);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("row_tuples", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->row_tuples.size()));
    std::vector< ::starrocks::TTupleId> ::const_iterator _iter10;
    for (_iter10 = this->row_tuples.begin(); _iter10 != this->row_tuples.end(); ++_iter10)
    {
      xfer += oprot->writeI32((*_iter10));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("tuple_offsets", ::apache::thrift::protocol::T_LIST, 3);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->tuple_offsets.size()));
    std::vector<int32_t> ::const_iterator _iter11;
    for (_iter11 = this->tuple_offsets.begin(); _iter11 != this->tuple_offsets.end(); ++_iter11)
    {
      xfer += oprot->writeI32((*_iter11));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("tuple_data", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeString(this->tuple_data);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("is_compressed", ::apache::thrift::protocol::T_BOOL, 5);
  xfer += oprot->writeBool(this->is_compressed);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("be_number", ::apache::thrift::protocol::T_I32, 6);
  xfer += oprot->writeI32(this->be_number);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("packet_seq", ::apache::thrift::protocol::T_I64, 7);
  xfer += oprot->writeI64(this->packet_seq);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TRowBatch &a, TRowBatch &b) {
  using ::std::swap;
  swap(a.num_rows, b.num_rows);
  swap(a.row_tuples, b.row_tuples);
  swap(a.tuple_offsets, b.tuple_offsets);
  swap(a.tuple_data, b.tuple_data);
  swap(a.is_compressed, b.is_compressed);
  swap(a.be_number, b.be_number);
  swap(a.packet_seq, b.packet_seq);
  swap(a.__isset, b.__isset);
}

bool TRowBatch::operator==(const TRowBatch & rhs) const
{
  if (!(num_rows == rhs.num_rows))
    return false;
  if (!(row_tuples == rhs.row_tuples))
    return false;
  if (!(tuple_offsets == rhs.tuple_offsets))
    return false;
  if (!(tuple_data == rhs.tuple_data))
    return false;
  if (!(is_compressed == rhs.is_compressed))
    return false;
  if (!(be_number == rhs.be_number))
    return false;
  if (!(packet_seq == rhs.packet_seq))
    return false;
  return true;
}

TRowBatch::TRowBatch(const TRowBatch& other12) {
  num_rows = other12.num_rows;
  row_tuples = other12.row_tuples;
  tuple_offsets = other12.tuple_offsets;
  tuple_data = other12.tuple_data;
  is_compressed = other12.is_compressed;
  be_number = other12.be_number;
  packet_seq = other12.packet_seq;
  __isset = other12.__isset;
}
TRowBatch& TRowBatch::operator=(const TRowBatch& other13) {
  num_rows = other13.num_rows;
  row_tuples = other13.row_tuples;
  tuple_offsets = other13.tuple_offsets;
  tuple_data = other13.tuple_data;
  is_compressed = other13.is_compressed;
  be_number = other13.be_number;
  packet_seq = other13.packet_seq;
  __isset = other13.__isset;
  return *this;
}
void TRowBatch::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TRowBatch(";
  out << "num_rows=" << to_string(num_rows);
  out << ", " << "row_tuples=" << to_string(row_tuples);
  out << ", " << "tuple_offsets=" << to_string(tuple_offsets);
  out << ", " << "tuple_data=" << to_string(tuple_data);
  out << ", " << "is_compressed=" << to_string(is_compressed);
  out << ", " << "be_number=" << to_string(be_number);
  out << ", " << "packet_seq=" << to_string(packet_seq);
  out << ")";
}


TColumnValue::~TColumnValue() noexcept {
}

TColumnValue::TColumnValue() noexcept
   : boolVal(0),
     intVal(0),
     longVal(0),
     doubleVal(0),
     stringVal() {
}

void TColumnValue::__set_boolVal(const bool val) {
  this->boolVal = val;
__isset.boolVal = true;
}

void TColumnValue::__set_intVal(const int32_t val) {
  this->intVal = val;
__isset.intVal = true;
}

void TColumnValue::__set_longVal(const int64_t val) {
  this->longVal = val;
__isset.longVal = true;
}

void TColumnValue::__set_doubleVal(const double val) {
  this->doubleVal = val;
__isset.doubleVal = true;
}

void TColumnValue::__set_stringVal(const std::string& val) {
  this->stringVal = val;
__isset.stringVal = true;
}
std::ostream& operator<<(std::ostream& out, const TColumnValue& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TColumnValue::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->boolVal);
          this->__isset.boolVal = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->intVal);
          this->__isset.intVal = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->longVal);
          this->__isset.longVal = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->doubleVal);
          this->__isset.doubleVal = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->stringVal);
          this->__isset.stringVal = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TColumnValue::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TColumnValue");

  if (this->__isset.boolVal) {
    xfer += oprot->writeFieldBegin("boolVal", ::apache::thrift::protocol::T_BOOL, 1);
    xfer += oprot->writeBool(this->boolVal);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.intVal) {
    xfer += oprot->writeFieldBegin("intVal", ::apache::thrift::protocol::T_I32, 2);
    xfer += oprot->writeI32(this->intVal);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.longVal) {
    xfer += oprot->writeFieldBegin("longVal", ::apache::thrift::protocol::T_I64, 3);
    xfer += oprot->writeI64(this->longVal);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.doubleVal) {
    xfer += oprot->writeFieldBegin("doubleVal", ::apache::thrift::protocol::T_DOUBLE, 4);
    xfer += oprot->writeDouble(this->doubleVal);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.stringVal) {
    xfer += oprot->writeFieldBegin("stringVal", ::apache::thrift::protocol::T_STRING, 5);
    xfer += oprot->writeString(this->stringVal);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TColumnValue &a, TColumnValue &b) {
  using ::std::swap;
  swap(a.boolVal, b.boolVal);
  swap(a.intVal, b.intVal);
  swap(a.longVal, b.longVal);
  swap(a.doubleVal, b.doubleVal);
  swap(a.stringVal, b.stringVal);
  swap(a.__isset, b.__isset);
}

bool TColumnValue::operator==(const TColumnValue & rhs) const
{
  if (__isset.boolVal != rhs.__isset.boolVal)
    return false;
  else if (__isset.boolVal && !(boolVal == rhs.boolVal))
    return false;
  if (__isset.intVal != rhs.__isset.intVal)
    return false;
  else if (__isset.intVal && !(intVal == rhs.intVal))
    return false;
  if (__isset.longVal != rhs.__isset.longVal)
    return false;
  else if (__isset.longVal && !(longVal == rhs.longVal))
    return false;
  if (__isset.doubleVal != rhs.__isset.doubleVal)
    return false;
  else if (__isset.doubleVal && !(doubleVal == rhs.doubleVal))
    return false;
  if (__isset.stringVal != rhs.__isset.stringVal)
    return false;
  else if (__isset.stringVal && !(stringVal == rhs.stringVal))
    return false;
  return true;
}

TColumnValue::TColumnValue(const TColumnValue& other14) {
  boolVal = other14.boolVal;
  intVal = other14.intVal;
  longVal = other14.longVal;
  doubleVal = other14.doubleVal;
  stringVal = other14.stringVal;
  __isset = other14.__isset;
}
TColumnValue& TColumnValue::operator=(const TColumnValue& other15) {
  boolVal = other15.boolVal;
  intVal = other15.intVal;
  longVal = other15.longVal;
  doubleVal = other15.doubleVal;
  stringVal = other15.stringVal;
  __isset = other15.__isset;
  return *this;
}
void TColumnValue::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TColumnValue(";
  out << "boolVal="; (__isset.boolVal ? (out << to_string(boolVal)) : (out << "<null>"));
  out << ", " << "intVal="; (__isset.intVal ? (out << to_string(intVal)) : (out << "<null>"));
  out << ", " << "longVal="; (__isset.longVal ? (out << to_string(longVal)) : (out << "<null>"));
  out << ", " << "doubleVal="; (__isset.doubleVal ? (out << to_string(doubleVal)) : (out << "<null>"));
  out << ", " << "stringVal="; (__isset.stringVal ? (out << to_string(stringVal)) : (out << "<null>"));
  out << ")";
}


TResultRow::~TResultRow() noexcept {
}

TResultRow::TResultRow() noexcept {
}

void TResultRow::__set_colVals(const std::vector<TColumnValue> & val) {
  this->colVals = val;
}
std::ostream& operator<<(std::ostream& out, const TResultRow& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TResultRow::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->colVals.clear();
            uint32_t _size16;
            ::apache::thrift::protocol::TType _etype19;
            xfer += iprot->readListBegin(_etype19, _size16);
            this->colVals.resize(_size16);
            uint32_t _i20;
            for (_i20 = 0; _i20 < _size16; ++_i20)
            {
              xfer += this->colVals[_i20].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.colVals = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TResultRow::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TResultRow");

  xfer += oprot->writeFieldBegin("colVals", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->colVals.size()));
    std::vector<TColumnValue> ::const_iterator _iter21;
    for (_iter21 = this->colVals.begin(); _iter21 != this->colVals.end(); ++_iter21)
    {
      xfer += (*_iter21).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TResultRow &a, TResultRow &b) {
  using ::std::swap;
  swap(a.colVals, b.colVals);
  swap(a.__isset, b.__isset);
}

bool TResultRow::operator==(const TResultRow & rhs) const
{
  if (!(colVals == rhs.colVals))
    return false;
  return true;
}

TResultRow::TResultRow(const TResultRow& other22) {
  colVals = other22.colVals;
  __isset = other22.__isset;
}
TResultRow& TResultRow::operator=(const TResultRow& other23) {
  colVals = other23.colVals;
  __isset = other23.__isset;
  return *this;
}
void TResultRow::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TResultRow(";
  out << "colVals=" << to_string(colVals);
  out << ")";
}


TResultBatch::~TResultBatch() noexcept {
}

TResultBatch::TResultBatch() noexcept
   : is_compressed(0),
     packet_seq(0),
     statistic_version(0) {
}

void TResultBatch::__set_rows(const std::vector<std::string> & val) {
  this->rows = val;
}

void TResultBatch::__set_is_compressed(const bool val) {
  this->is_compressed = val;
}

void TResultBatch::__set_packet_seq(const int64_t val) {
  this->packet_seq = val;
}

void TResultBatch::__set_statistic_version(const int32_t val) {
  this->statistic_version = val;
__isset.statistic_version = true;
}
std::ostream& operator<<(std::ostream& out, const TResultBatch& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TResultBatch::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_rows = false;
  bool isset_is_compressed = false;
  bool isset_packet_seq = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->rows.clear();
            uint32_t _size24;
            ::apache::thrift::protocol::TType _etype27;
            xfer += iprot->readListBegin(_etype27, _size24);
            this->rows.resize(_size24);
            uint32_t _i28;
            for (_i28 = 0; _i28 < _size24; ++_i28)
            {
              xfer += iprot->readBinary(this->rows[_i28]);
            }
            xfer += iprot->readListEnd();
          }
          isset_rows = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->is_compressed);
          isset_is_compressed = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->packet_seq);
          isset_packet_seq = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->statistic_version);
          this->__isset.statistic_version = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_rows)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_is_compressed)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_packet_seq)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TResultBatch::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TResultBatch");

  xfer += oprot->writeFieldBegin("rows", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->rows.size()));
    std::vector<std::string> ::const_iterator _iter29;
    for (_iter29 = this->rows.begin(); _iter29 != this->rows.end(); ++_iter29)
    {
      xfer += oprot->writeBinary((*_iter29));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("is_compressed", ::apache::thrift::protocol::T_BOOL, 2);
  xfer += oprot->writeBool(this->is_compressed);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("packet_seq", ::apache::thrift::protocol::T_I64, 3);
  xfer += oprot->writeI64(this->packet_seq);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.statistic_version) {
    xfer += oprot->writeFieldBegin("statistic_version", ::apache::thrift::protocol::T_I32, 10);
    xfer += oprot->writeI32(this->statistic_version);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TResultBatch &a, TResultBatch &b) {
  using ::std::swap;
  swap(a.rows, b.rows);
  swap(a.is_compressed, b.is_compressed);
  swap(a.packet_seq, b.packet_seq);
  swap(a.statistic_version, b.statistic_version);
  swap(a.__isset, b.__isset);
}

bool TResultBatch::operator==(const TResultBatch & rhs) const
{
  if (!(rows == rhs.rows))
    return false;
  if (!(is_compressed == rhs.is_compressed))
    return false;
  if (!(packet_seq == rhs.packet_seq))
    return false;
  if (__isset.statistic_version != rhs.__isset.statistic_version)
    return false;
  else if (__isset.statistic_version && !(statistic_version == rhs.statistic_version))
    return false;
  return true;
}

TResultBatch::TResultBatch(const TResultBatch& other30) {
  rows = other30.rows;
  is_compressed = other30.is_compressed;
  packet_seq = other30.packet_seq;
  statistic_version = other30.statistic_version;
  __isset = other30.__isset;
}
TResultBatch& TResultBatch::operator=(const TResultBatch& other31) {
  rows = other31.rows;
  is_compressed = other31.is_compressed;
  packet_seq = other31.packet_seq;
  statistic_version = other31.statistic_version;
  __isset = other31.__isset;
  return *this;
}
void TResultBatch::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TResultBatch(";
  out << "rows=" << to_string(rows);
  out << ", " << "is_compressed=" << to_string(is_compressed);
  out << ", " << "packet_seq=" << to_string(packet_seq);
  out << ", " << "statistic_version="; (__isset.statistic_version ? (out << to_string(statistic_version)) : (out << "<null>"));
  out << ")";
}


TGlobalDict::~TGlobalDict() noexcept {
}

TGlobalDict::TGlobalDict() noexcept
   : columnId(0),
     version(0) {
}

void TGlobalDict::__set_columnId(const int32_t val) {
  this->columnId = val;
__isset.columnId = true;
}

void TGlobalDict::__set_strings(const std::vector<std::string> & val) {
  this->strings = val;
__isset.strings = true;
}

void TGlobalDict::__set_ids(const std::vector<int32_t> & val) {
  this->ids = val;
__isset.ids = true;
}

void TGlobalDict::__set_version(const int64_t val) {
  this->version = val;
__isset.version = true;
}
std::ostream& operator<<(std::ostream& out, const TGlobalDict& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TGlobalDict::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->columnId);
          this->__isset.columnId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->strings.clear();
            uint32_t _size32;
            ::apache::thrift::protocol::TType _etype35;
            xfer += iprot->readListBegin(_etype35, _size32);
            this->strings.resize(_size32);
            uint32_t _i36;
            for (_i36 = 0; _i36 < _size32; ++_i36)
            {
              xfer += iprot->readBinary(this->strings[_i36]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.strings = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->ids.clear();
            uint32_t _size37;
            ::apache::thrift::protocol::TType _etype40;
            xfer += iprot->readListBegin(_etype40, _size37);
            this->ids.resize(_size37);
            uint32_t _i41;
            for (_i41 = 0; _i41 < _size37; ++_i41)
            {
              xfer += iprot->readI32(this->ids[_i41]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.ids = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->version);
          this->__isset.version = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TGlobalDict::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TGlobalDict");

  if (this->__isset.columnId) {
    xfer += oprot->writeFieldBegin("columnId", ::apache::thrift::protocol::T_I32, 1);
    xfer += oprot->writeI32(this->columnId);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.strings) {
    xfer += oprot->writeFieldBegin("strings", ::apache::thrift::protocol::T_LIST, 2);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->strings.size()));
      std::vector<std::string> ::const_iterator _iter42;
      for (_iter42 = this->strings.begin(); _iter42 != this->strings.end(); ++_iter42)
      {
        xfer += oprot->writeBinary((*_iter42));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.ids) {
    xfer += oprot->writeFieldBegin("ids", ::apache::thrift::protocol::T_LIST, 3);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->ids.size()));
      std::vector<int32_t> ::const_iterator _iter43;
      for (_iter43 = this->ids.begin(); _iter43 != this->ids.end(); ++_iter43)
      {
        xfer += oprot->writeI32((*_iter43));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.version) {
    xfer += oprot->writeFieldBegin("version", ::apache::thrift::protocol::T_I64, 4);
    xfer += oprot->writeI64(this->version);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TGlobalDict &a, TGlobalDict &b) {
  using ::std::swap;
  swap(a.columnId, b.columnId);
  swap(a.strings, b.strings);
  swap(a.ids, b.ids);
  swap(a.version, b.version);
  swap(a.__isset, b.__isset);
}

bool TGlobalDict::operator==(const TGlobalDict & rhs) const
{
  if (__isset.columnId != rhs.__isset.columnId)
    return false;
  else if (__isset.columnId && !(columnId == rhs.columnId))
    return false;
  if (__isset.strings != rhs.__isset.strings)
    return false;
  else if (__isset.strings && !(strings == rhs.strings))
    return false;
  if (__isset.ids != rhs.__isset.ids)
    return false;
  else if (__isset.ids && !(ids == rhs.ids))
    return false;
  if (__isset.version != rhs.__isset.version)
    return false;
  else if (__isset.version && !(version == rhs.version))
    return false;
  return true;
}

TGlobalDict::TGlobalDict(const TGlobalDict& other44) {
  columnId = other44.columnId;
  strings = other44.strings;
  ids = other44.ids;
  version = other44.version;
  __isset = other44.__isset;
}
TGlobalDict& TGlobalDict::operator=(const TGlobalDict& other45) {
  columnId = other45.columnId;
  strings = other45.strings;
  ids = other45.ids;
  version = other45.version;
  __isset = other45.__isset;
  return *this;
}
void TGlobalDict::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TGlobalDict(";
  out << "columnId="; (__isset.columnId ? (out << to_string(columnId)) : (out << "<null>"));
  out << ", " << "strings="; (__isset.strings ? (out << to_string(strings)) : (out << "<null>"));
  out << ", " << "ids="; (__isset.ids ? (out << to_string(ids)) : (out << "<null>"));
  out << ", " << "version="; (__isset.version ? (out << to_string(version)) : (out << "<null>"));
  out << ")";
}


TStatisticData::~TStatisticData() noexcept {
}

TStatisticData::TStatisticData() noexcept
   : updateTime(),
     dbId(0),
     tableId(0),
     columnName(),
     rowCount(0),
     dataSize(0),
     countDistinct(0),
     nullCount(0),
     max(),
     min(),
     histogram(),
     meta_version(0),
     partitionId(0),
     hll(),
     partitionName() {
}

void TStatisticData::__set_updateTime(const std::string& val) {
  this->updateTime = val;
__isset.updateTime = true;
}

void TStatisticData::__set_dbId(const int64_t val) {
  this->dbId = val;
__isset.dbId = true;
}

void TStatisticData::__set_tableId(const int64_t val) {
  this->tableId = val;
__isset.tableId = true;
}

void TStatisticData::__set_columnName(const std::string& val) {
  this->columnName = val;
__isset.columnName = true;
}

void TStatisticData::__set_rowCount(const int64_t val) {
  this->rowCount = val;
__isset.rowCount = true;
}

void TStatisticData::__set_dataSize(const double val) {
  this->dataSize = val;
__isset.dataSize = true;
}

void TStatisticData::__set_countDistinct(const int64_t val) {
  this->countDistinct = val;
__isset.countDistinct = true;
}

void TStatisticData::__set_nullCount(const int64_t val) {
  this->nullCount = val;
__isset.nullCount = true;
}

void TStatisticData::__set_max(const std::string& val) {
  this->max = val;
__isset.max = true;
}

void TStatisticData::__set_min(const std::string& val) {
  this->min = val;
__isset.min = true;
}

void TStatisticData::__set_histogram(const std::string& val) {
  this->histogram = val;
__isset.histogram = true;
}

void TStatisticData::__set_dict(const TGlobalDict& val) {
  this->dict = val;
__isset.dict = true;
}

void TStatisticData::__set_meta_version(const int64_t val) {
  this->meta_version = val;
__isset.meta_version = true;
}

void TStatisticData::__set_partitionId(const int64_t val) {
  this->partitionId = val;
__isset.partitionId = true;
}

void TStatisticData::__set_hll(const std::string& val) {
  this->hll = val;
__isset.hll = true;
}

void TStatisticData::__set_partitionName(const std::string& val) {
  this->partitionName = val;
__isset.partitionName = true;
}
std::ostream& operator<<(std::ostream& out, const TStatisticData& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TStatisticData::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->updateTime);
          this->__isset.updateTime = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->dbId);
          this->__isset.dbId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->tableId);
          this->__isset.tableId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->columnName);
          this->__isset.columnName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->rowCount);
          this->__isset.rowCount = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->dataSize);
          this->__isset.dataSize = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->countDistinct);
          this->__isset.countDistinct = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->nullCount);
          this->__isset.nullCount = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->max);
          this->__isset.max = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->min);
          this->__isset.min = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 11:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->histogram);
          this->__isset.histogram = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 12:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->dict.read(iprot);
          this->__isset.dict = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 13:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->meta_version);
          this->__isset.meta_version = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 14:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->partitionId);
          this->__isset.partitionId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 15:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->hll);
          this->__isset.hll = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 16:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->partitionName);
          this->__isset.partitionName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TStatisticData::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TStatisticData");

  if (this->__isset.updateTime) {
    xfer += oprot->writeFieldBegin("updateTime", ::apache::thrift::protocol::T_STRING, 1);
    xfer += oprot->writeString(this->updateTime);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.dbId) {
    xfer += oprot->writeFieldBegin("dbId", ::apache::thrift::protocol::T_I64, 2);
    xfer += oprot->writeI64(this->dbId);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.tableId) {
    xfer += oprot->writeFieldBegin("tableId", ::apache::thrift::protocol::T_I64, 3);
    xfer += oprot->writeI64(this->tableId);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.columnName) {
    xfer += oprot->writeFieldBegin("columnName", ::apache::thrift::protocol::T_STRING, 4);
    xfer += oprot->writeString(this->columnName);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.rowCount) {
    xfer += oprot->writeFieldBegin("rowCount", ::apache::thrift::protocol::T_I64, 5);
    xfer += oprot->writeI64(this->rowCount);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.dataSize) {
    xfer += oprot->writeFieldBegin("dataSize", ::apache::thrift::protocol::T_DOUBLE, 6);
    xfer += oprot->writeDouble(this->dataSize);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.countDistinct) {
    xfer += oprot->writeFieldBegin("countDistinct", ::apache::thrift::protocol::T_I64, 7);
    xfer += oprot->writeI64(this->countDistinct);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.nullCount) {
    xfer += oprot->writeFieldBegin("nullCount", ::apache::thrift::protocol::T_I64, 8);
    xfer += oprot->writeI64(this->nullCount);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.max) {
    xfer += oprot->writeFieldBegin("max", ::apache::thrift::protocol::T_STRING, 9);
    xfer += oprot->writeString(this->max);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.min) {
    xfer += oprot->writeFieldBegin("min", ::apache::thrift::protocol::T_STRING, 10);
    xfer += oprot->writeString(this->min);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.histogram) {
    xfer += oprot->writeFieldBegin("histogram", ::apache::thrift::protocol::T_STRING, 11);
    xfer += oprot->writeString(this->histogram);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.dict) {
    xfer += oprot->writeFieldBegin("dict", ::apache::thrift::protocol::T_STRUCT, 12);
    xfer += this->dict.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.meta_version) {
    xfer += oprot->writeFieldBegin("meta_version", ::apache::thrift::protocol::T_I64, 13);
    xfer += oprot->writeI64(this->meta_version);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.partitionId) {
    xfer += oprot->writeFieldBegin("partitionId", ::apache::thrift::protocol::T_I64, 14);
    xfer += oprot->writeI64(this->partitionId);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.hll) {
    xfer += oprot->writeFieldBegin("hll", ::apache::thrift::protocol::T_STRING, 15);
    xfer += oprot->writeBinary(this->hll);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.partitionName) {
    xfer += oprot->writeFieldBegin("partitionName", ::apache::thrift::protocol::T_STRING, 16);
    xfer += oprot->writeString(this->partitionName);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TStatisticData &a, TStatisticData &b) {
  using ::std::swap;
  swap(a.updateTime, b.updateTime);
  swap(a.dbId, b.dbId);
  swap(a.tableId, b.tableId);
  swap(a.columnName, b.columnName);
  swap(a.rowCount, b.rowCount);
  swap(a.dataSize, b.dataSize);
  swap(a.countDistinct, b.countDistinct);
  swap(a.nullCount, b.nullCount);
  swap(a.max, b.max);
  swap(a.min, b.min);
  swap(a.histogram, b.histogram);
  swap(a.dict, b.dict);
  swap(a.meta_version, b.meta_version);
  swap(a.partitionId, b.partitionId);
  swap(a.hll, b.hll);
  swap(a.partitionName, b.partitionName);
  swap(a.__isset, b.__isset);
}

bool TStatisticData::operator==(const TStatisticData & rhs) const
{
  if (__isset.updateTime != rhs.__isset.updateTime)
    return false;
  else if (__isset.updateTime && !(updateTime == rhs.updateTime))
    return false;
  if (__isset.dbId != rhs.__isset.dbId)
    return false;
  else if (__isset.dbId && !(dbId == rhs.dbId))
    return false;
  if (__isset.tableId != rhs.__isset.tableId)
    return false;
  else if (__isset.tableId && !(tableId == rhs.tableId))
    return false;
  if (__isset.columnName != rhs.__isset.columnName)
    return false;
  else if (__isset.columnName && !(columnName == rhs.columnName))
    return false;
  if (__isset.rowCount != rhs.__isset.rowCount)
    return false;
  else if (__isset.rowCount && !(rowCount == rhs.rowCount))
    return false;
  if (__isset.dataSize != rhs.__isset.dataSize)
    return false;
  else if (__isset.dataSize && !(dataSize == rhs.dataSize))
    return false;
  if (__isset.countDistinct != rhs.__isset.countDistinct)
    return false;
  else if (__isset.countDistinct && !(countDistinct == rhs.countDistinct))
    return false;
  if (__isset.nullCount != rhs.__isset.nullCount)
    return false;
  else if (__isset.nullCount && !(nullCount == rhs.nullCount))
    return false;
  if (__isset.max != rhs.__isset.max)
    return false;
  else if (__isset.max && !(max == rhs.max))
    return false;
  if (__isset.min != rhs.__isset.min)
    return false;
  else if (__isset.min && !(min == rhs.min))
    return false;
  if (__isset.histogram != rhs.__isset.histogram)
    return false;
  else if (__isset.histogram && !(histogram == rhs.histogram))
    return false;
  if (__isset.dict != rhs.__isset.dict)
    return false;
  else if (__isset.dict && !(dict == rhs.dict))
    return false;
  if (__isset.meta_version != rhs.__isset.meta_version)
    return false;
  else if (__isset.meta_version && !(meta_version == rhs.meta_version))
    return false;
  if (__isset.partitionId != rhs.__isset.partitionId)
    return false;
  else if (__isset.partitionId && !(partitionId == rhs.partitionId))
    return false;
  if (__isset.hll != rhs.__isset.hll)
    return false;
  else if (__isset.hll && !(hll == rhs.hll))
    return false;
  if (__isset.partitionName != rhs.__isset.partitionName)
    return false;
  else if (__isset.partitionName && !(partitionName == rhs.partitionName))
    return false;
  return true;
}

TStatisticData::TStatisticData(const TStatisticData& other46) {
  updateTime = other46.updateTime;
  dbId = other46.dbId;
  tableId = other46.tableId;
  columnName = other46.columnName;
  rowCount = other46.rowCount;
  dataSize = other46.dataSize;
  countDistinct = other46.countDistinct;
  nullCount = other46.nullCount;
  max = other46.max;
  min = other46.min;
  histogram = other46.histogram;
  dict = other46.dict;
  meta_version = other46.meta_version;
  partitionId = other46.partitionId;
  hll = other46.hll;
  partitionName = other46.partitionName;
  __isset = other46.__isset;
}
TStatisticData& TStatisticData::operator=(const TStatisticData& other47) {
  updateTime = other47.updateTime;
  dbId = other47.dbId;
  tableId = other47.tableId;
  columnName = other47.columnName;
  rowCount = other47.rowCount;
  dataSize = other47.dataSize;
  countDistinct = other47.countDistinct;
  nullCount = other47.nullCount;
  max = other47.max;
  min = other47.min;
  histogram = other47.histogram;
  dict = other47.dict;
  meta_version = other47.meta_version;
  partitionId = other47.partitionId;
  hll = other47.hll;
  partitionName = other47.partitionName;
  __isset = other47.__isset;
  return *this;
}
void TStatisticData::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TStatisticData(";
  out << "updateTime="; (__isset.updateTime ? (out << to_string(updateTime)) : (out << "<null>"));
  out << ", " << "dbId="; (__isset.dbId ? (out << to_string(dbId)) : (out << "<null>"));
  out << ", " << "tableId="; (__isset.tableId ? (out << to_string(tableId)) : (out << "<null>"));
  out << ", " << "columnName="; (__isset.columnName ? (out << to_string(columnName)) : (out << "<null>"));
  out << ", " << "rowCount="; (__isset.rowCount ? (out << to_string(rowCount)) : (out << "<null>"));
  out << ", " << "dataSize="; (__isset.dataSize ? (out << to_string(dataSize)) : (out << "<null>"));
  out << ", " << "countDistinct="; (__isset.countDistinct ? (out << to_string(countDistinct)) : (out << "<null>"));
  out << ", " << "nullCount="; (__isset.nullCount ? (out << to_string(nullCount)) : (out << "<null>"));
  out << ", " << "max="; (__isset.max ? (out << to_string(max)) : (out << "<null>"));
  out << ", " << "min="; (__isset.min ? (out << to_string(min)) : (out << "<null>"));
  out << ", " << "histogram="; (__isset.histogram ? (out << to_string(histogram)) : (out << "<null>"));
  out << ", " << "dict="; (__isset.dict ? (out << to_string(dict)) : (out << "<null>"));
  out << ", " << "meta_version="; (__isset.meta_version ? (out << to_string(meta_version)) : (out << "<null>"));
  out << ", " << "partitionId="; (__isset.partitionId ? (out << to_string(partitionId)) : (out << "<null>"));
  out << ", " << "hll="; (__isset.hll ? (out << to_string(hll)) : (out << "<null>"));
  out << ", " << "partitionName="; (__isset.partitionName ? (out << to_string(partitionName)) : (out << "<null>"));
  out << ")";
}


TVariableData::~TVariableData() noexcept {
}

TVariableData::TVariableData() noexcept
   : isNull(0),
     result() {
}

void TVariableData::__set_isNull(const bool val) {
  this->isNull = val;
__isset.isNull = true;
}

void TVariableData::__set_result(const std::string& val) {
  this->result = val;
__isset.result = true;
}
std::ostream& operator<<(std::ostream& out, const TVariableData& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TVariableData::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->isNull);
          this->__isset.isNull = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->result);
          this->__isset.result = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TVariableData::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TVariableData");

  if (this->__isset.isNull) {
    xfer += oprot->writeFieldBegin("isNull", ::apache::thrift::protocol::T_BOOL, 1);
    xfer += oprot->writeBool(this->isNull);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.result) {
    xfer += oprot->writeFieldBegin("result", ::apache::thrift::protocol::T_STRING, 2);
    xfer += oprot->writeBinary(this->result);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TVariableData &a, TVariableData &b) {
  using ::std::swap;
  swap(a.isNull, b.isNull);
  swap(a.result, b.result);
  swap(a.__isset, b.__isset);
}

bool TVariableData::operator==(const TVariableData & rhs) const
{
  if (__isset.isNull != rhs.__isset.isNull)
    return false;
  else if (__isset.isNull && !(isNull == rhs.isNull))
    return false;
  if (__isset.result != rhs.__isset.result)
    return false;
  else if (__isset.result && !(result == rhs.result))
    return false;
  return true;
}

TVariableData::TVariableData(const TVariableData& other48) {
  isNull = other48.isNull;
  result = other48.result;
  __isset = other48.__isset;
}
TVariableData& TVariableData::operator=(const TVariableData& other49) {
  isNull = other49.isNull;
  result = other49.result;
  __isset = other49.__isset;
  return *this;
}
void TVariableData::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TVariableData(";
  out << "isNull="; (__isset.isNull ? (out << to_string(isNull)) : (out << "<null>"));
  out << ", " << "result="; (__isset.result ? (out << to_string(result)) : (out << "<null>"));
  out << ")";
}


TIcebergMetadata::~TIcebergMetadata() noexcept {
}

TIcebergMetadata::TIcebergMetadata() noexcept
   : content(0),
     file_path(),
     file_format(),
     spec_id(0),
     partition_data(),
     record_count(0),
     file_size_in_bytes(0),
     sort_id(0),
     file_sequence_number(0),
     data_sequence_number(0),
     column_stats(),
     key_metadata() {
}

void TIcebergMetadata::__set_content(const int32_t val) {
  this->content = val;
__isset.content = true;
}

void TIcebergMetadata::__set_file_path(const std::string& val) {
  this->file_path = val;
__isset.file_path = true;
}

void TIcebergMetadata::__set_file_format(const std::string& val) {
  this->file_format = val;
__isset.file_format = true;
}

void TIcebergMetadata::__set_spec_id(const int32_t val) {
  this->spec_id = val;
__isset.spec_id = true;
}

void TIcebergMetadata::__set_partition_data(const std::string& val) {
  this->partition_data = val;
__isset.partition_data = true;
}

void TIcebergMetadata::__set_record_count(const int64_t val) {
  this->record_count = val;
__isset.record_count = true;
}

void TIcebergMetadata::__set_file_size_in_bytes(const int64_t val) {
  this->file_size_in_bytes = val;
__isset.file_size_in_bytes = true;
}

void TIcebergMetadata::__set_split_offsets(const std::vector<int64_t> & val) {
  this->split_offsets = val;
__isset.split_offsets = true;
}

void TIcebergMetadata::__set_sort_id(const int32_t val) {
  this->sort_id = val;
__isset.sort_id = true;
}

void TIcebergMetadata::__set_equality_ids(const std::vector<int32_t> & val) {
  this->equality_ids = val;
__isset.equality_ids = true;
}

void TIcebergMetadata::__set_file_sequence_number(const int64_t val) {
  this->file_sequence_number = val;
__isset.file_sequence_number = true;
}

void TIcebergMetadata::__set_data_sequence_number(const int64_t val) {
  this->data_sequence_number = val;
__isset.data_sequence_number = true;
}

void TIcebergMetadata::__set_column_stats(const std::string& val) {
  this->column_stats = val;
__isset.column_stats = true;
}

void TIcebergMetadata::__set_key_metadata(const std::string& val) {
  this->key_metadata = val;
__isset.key_metadata = true;
}
std::ostream& operator<<(std::ostream& out, const TIcebergMetadata& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TIcebergMetadata::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->content);
          this->__isset.content = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->file_path);
          this->__isset.file_path = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->file_format);
          this->__isset.file_format = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->spec_id);
          this->__isset.spec_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->partition_data);
          this->__isset.partition_data = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->record_count);
          this->__isset.record_count = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->file_size_in_bytes);
          this->__isset.file_size_in_bytes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->split_offsets.clear();
            uint32_t _size50;
            ::apache::thrift::protocol::TType _etype53;
            xfer += iprot->readListBegin(_etype53, _size50);
            this->split_offsets.resize(_size50);
            uint32_t _i54;
            for (_i54 = 0; _i54 < _size50; ++_i54)
            {
              xfer += iprot->readI64(this->split_offsets[_i54]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.split_offsets = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->sort_id);
          this->__isset.sort_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->equality_ids.clear();
            uint32_t _size55;
            ::apache::thrift::protocol::TType _etype58;
            xfer += iprot->readListBegin(_etype58, _size55);
            this->equality_ids.resize(_size55);
            uint32_t _i59;
            for (_i59 = 0; _i59 < _size55; ++_i59)
            {
              xfer += iprot->readI32(this->equality_ids[_i59]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.equality_ids = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 11:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->file_sequence_number);
          this->__isset.file_sequence_number = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 12:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->data_sequence_number);
          this->__isset.data_sequence_number = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 13:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->column_stats);
          this->__isset.column_stats = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 14:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->key_metadata);
          this->__isset.key_metadata = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TIcebergMetadata::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TIcebergMetadata");

  if (this->__isset.content) {
    xfer += oprot->writeFieldBegin("content", ::apache::thrift::protocol::T_I32, 1);
    xfer += oprot->writeI32(this->content);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.file_path) {
    xfer += oprot->writeFieldBegin("file_path", ::apache::thrift::protocol::T_STRING, 2);
    xfer += oprot->writeString(this->file_path);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.file_format) {
    xfer += oprot->writeFieldBegin("file_format", ::apache::thrift::protocol::T_STRING, 3);
    xfer += oprot->writeString(this->file_format);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.spec_id) {
    xfer += oprot->writeFieldBegin("spec_id", ::apache::thrift::protocol::T_I32, 4);
    xfer += oprot->writeI32(this->spec_id);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.partition_data) {
    xfer += oprot->writeFieldBegin("partition_data", ::apache::thrift::protocol::T_STRING, 5);
    xfer += oprot->writeBinary(this->partition_data);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.record_count) {
    xfer += oprot->writeFieldBegin("record_count", ::apache::thrift::protocol::T_I64, 6);
    xfer += oprot->writeI64(this->record_count);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.file_size_in_bytes) {
    xfer += oprot->writeFieldBegin("file_size_in_bytes", ::apache::thrift::protocol::T_I64, 7);
    xfer += oprot->writeI64(this->file_size_in_bytes);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.split_offsets) {
    xfer += oprot->writeFieldBegin("split_offsets", ::apache::thrift::protocol::T_LIST, 8);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>(this->split_offsets.size()));
      std::vector<int64_t> ::const_iterator _iter60;
      for (_iter60 = this->split_offsets.begin(); _iter60 != this->split_offsets.end(); ++_iter60)
      {
        xfer += oprot->writeI64((*_iter60));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.sort_id) {
    xfer += oprot->writeFieldBegin("sort_id", ::apache::thrift::protocol::T_I32, 9);
    xfer += oprot->writeI32(this->sort_id);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.equality_ids) {
    xfer += oprot->writeFieldBegin("equality_ids", ::apache::thrift::protocol::T_LIST, 10);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->equality_ids.size()));
      std::vector<int32_t> ::const_iterator _iter61;
      for (_iter61 = this->equality_ids.begin(); _iter61 != this->equality_ids.end(); ++_iter61)
      {
        xfer += oprot->writeI32((*_iter61));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.file_sequence_number) {
    xfer += oprot->writeFieldBegin("file_sequence_number", ::apache::thrift::protocol::T_I64, 11);
    xfer += oprot->writeI64(this->file_sequence_number);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.data_sequence_number) {
    xfer += oprot->writeFieldBegin("data_sequence_number", ::apache::thrift::protocol::T_I64, 12);
    xfer += oprot->writeI64(this->data_sequence_number);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.column_stats) {
    xfer += oprot->writeFieldBegin("column_stats", ::apache::thrift::protocol::T_STRING, 13);
    xfer += oprot->writeBinary(this->column_stats);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.key_metadata) {
    xfer += oprot->writeFieldBegin("key_metadata", ::apache::thrift::protocol::T_STRING, 14);
    xfer += oprot->writeBinary(this->key_metadata);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TIcebergMetadata &a, TIcebergMetadata &b) {
  using ::std::swap;
  swap(a.content, b.content);
  swap(a.file_path, b.file_path);
  swap(a.file_format, b.file_format);
  swap(a.spec_id, b.spec_id);
  swap(a.partition_data, b.partition_data);
  swap(a.record_count, b.record_count);
  swap(a.file_size_in_bytes, b.file_size_in_bytes);
  swap(a.split_offsets, b.split_offsets);
  swap(a.sort_id, b.sort_id);
  swap(a.equality_ids, b.equality_ids);
  swap(a.file_sequence_number, b.file_sequence_number);
  swap(a.data_sequence_number, b.data_sequence_number);
  swap(a.column_stats, b.column_stats);
  swap(a.key_metadata, b.key_metadata);
  swap(a.__isset, b.__isset);
}

bool TIcebergMetadata::operator==(const TIcebergMetadata & rhs) const
{
  if (__isset.content != rhs.__isset.content)
    return false;
  else if (__isset.content && !(content == rhs.content))
    return false;
  if (__isset.file_path != rhs.__isset.file_path)
    return false;
  else if (__isset.file_path && !(file_path == rhs.file_path))
    return false;
  if (__isset.file_format != rhs.__isset.file_format)
    return false;
  else if (__isset.file_format && !(file_format == rhs.file_format))
    return false;
  if (__isset.spec_id != rhs.__isset.spec_id)
    return false;
  else if (__isset.spec_id && !(spec_id == rhs.spec_id))
    return false;
  if (__isset.partition_data != rhs.__isset.partition_data)
    return false;
  else if (__isset.partition_data && !(partition_data == rhs.partition_data))
    return false;
  if (__isset.record_count != rhs.__isset.record_count)
    return false;
  else if (__isset.record_count && !(record_count == rhs.record_count))
    return false;
  if (__isset.file_size_in_bytes != rhs.__isset.file_size_in_bytes)
    return false;
  else if (__isset.file_size_in_bytes && !(file_size_in_bytes == rhs.file_size_in_bytes))
    return false;
  if (__isset.split_offsets != rhs.__isset.split_offsets)
    return false;
  else if (__isset.split_offsets && !(split_offsets == rhs.split_offsets))
    return false;
  if (__isset.sort_id != rhs.__isset.sort_id)
    return false;
  else if (__isset.sort_id && !(sort_id == rhs.sort_id))
    return false;
  if (__isset.equality_ids != rhs.__isset.equality_ids)
    return false;
  else if (__isset.equality_ids && !(equality_ids == rhs.equality_ids))
    return false;
  if (__isset.file_sequence_number != rhs.__isset.file_sequence_number)
    return false;
  else if (__isset.file_sequence_number && !(file_sequence_number == rhs.file_sequence_number))
    return false;
  if (__isset.data_sequence_number != rhs.__isset.data_sequence_number)
    return false;
  else if (__isset.data_sequence_number && !(data_sequence_number == rhs.data_sequence_number))
    return false;
  if (__isset.column_stats != rhs.__isset.column_stats)
    return false;
  else if (__isset.column_stats && !(column_stats == rhs.column_stats))
    return false;
  if (__isset.key_metadata != rhs.__isset.key_metadata)
    return false;
  else if (__isset.key_metadata && !(key_metadata == rhs.key_metadata))
    return false;
  return true;
}

TIcebergMetadata::TIcebergMetadata(const TIcebergMetadata& other62) {
  content = other62.content;
  file_path = other62.file_path;
  file_format = other62.file_format;
  spec_id = other62.spec_id;
  partition_data = other62.partition_data;
  record_count = other62.record_count;
  file_size_in_bytes = other62.file_size_in_bytes;
  split_offsets = other62.split_offsets;
  sort_id = other62.sort_id;
  equality_ids = other62.equality_ids;
  file_sequence_number = other62.file_sequence_number;
  data_sequence_number = other62.data_sequence_number;
  column_stats = other62.column_stats;
  key_metadata = other62.key_metadata;
  __isset = other62.__isset;
}
TIcebergMetadata& TIcebergMetadata::operator=(const TIcebergMetadata& other63) {
  content = other63.content;
  file_path = other63.file_path;
  file_format = other63.file_format;
  spec_id = other63.spec_id;
  partition_data = other63.partition_data;
  record_count = other63.record_count;
  file_size_in_bytes = other63.file_size_in_bytes;
  split_offsets = other63.split_offsets;
  sort_id = other63.sort_id;
  equality_ids = other63.equality_ids;
  file_sequence_number = other63.file_sequence_number;
  data_sequence_number = other63.data_sequence_number;
  column_stats = other63.column_stats;
  key_metadata = other63.key_metadata;
  __isset = other63.__isset;
  return *this;
}
void TIcebergMetadata::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TIcebergMetadata(";
  out << "content="; (__isset.content ? (out << to_string(content)) : (out << "<null>"));
  out << ", " << "file_path="; (__isset.file_path ? (out << to_string(file_path)) : (out << "<null>"));
  out << ", " << "file_format="; (__isset.file_format ? (out << to_string(file_format)) : (out << "<null>"));
  out << ", " << "spec_id="; (__isset.spec_id ? (out << to_string(spec_id)) : (out << "<null>"));
  out << ", " << "partition_data="; (__isset.partition_data ? (out << to_string(partition_data)) : (out << "<null>"));
  out << ", " << "record_count="; (__isset.record_count ? (out << to_string(record_count)) : (out << "<null>"));
  out << ", " << "file_size_in_bytes="; (__isset.file_size_in_bytes ? (out << to_string(file_size_in_bytes)) : (out << "<null>"));
  out << ", " << "split_offsets="; (__isset.split_offsets ? (out << to_string(split_offsets)) : (out << "<null>"));
  out << ", " << "sort_id="; (__isset.sort_id ? (out << to_string(sort_id)) : (out << "<null>"));
  out << ", " << "equality_ids="; (__isset.equality_ids ? (out << to_string(equality_ids)) : (out << "<null>"));
  out << ", " << "file_sequence_number="; (__isset.file_sequence_number ? (out << to_string(file_sequence_number)) : (out << "<null>"));
  out << ", " << "data_sequence_number="; (__isset.data_sequence_number ? (out << to_string(data_sequence_number)) : (out << "<null>"));
  out << ", " << "column_stats="; (__isset.column_stats ? (out << to_string(column_stats)) : (out << "<null>"));
  out << ", " << "key_metadata="; (__isset.key_metadata ? (out << to_string(key_metadata)) : (out << "<null>"));
  out << ")";
}


TMetadataEntry::~TMetadataEntry() noexcept {
}

TMetadataEntry::TMetadataEntry() noexcept {
}

void TMetadataEntry::__set_iceberg_metadata(const TIcebergMetadata& val) {
  this->iceberg_metadata = val;
__isset.iceberg_metadata = true;
}
std::ostream& operator<<(std::ostream& out, const TMetadataEntry& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TMetadataEntry::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->iceberg_metadata.read(iprot);
          this->__isset.iceberg_metadata = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TMetadataEntry::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TMetadataEntry");

  if (this->__isset.iceberg_metadata) {
    xfer += oprot->writeFieldBegin("iceberg_metadata", ::apache::thrift::protocol::T_STRUCT, 1);
    xfer += this->iceberg_metadata.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TMetadataEntry &a, TMetadataEntry &b) {
  using ::std::swap;
  swap(a.iceberg_metadata, b.iceberg_metadata);
  swap(a.__isset, b.__isset);
}

bool TMetadataEntry::operator==(const TMetadataEntry & rhs) const
{
  if (__isset.iceberg_metadata != rhs.__isset.iceberg_metadata)
    return false;
  else if (__isset.iceberg_metadata && !(iceberg_metadata == rhs.iceberg_metadata))
    return false;
  return true;
}

TMetadataEntry::TMetadataEntry(const TMetadataEntry& other64) {
  iceberg_metadata = other64.iceberg_metadata;
  __isset = other64.__isset;
}
TMetadataEntry& TMetadataEntry::operator=(const TMetadataEntry& other65) {
  iceberg_metadata = other65.iceberg_metadata;
  __isset = other65.__isset;
  return *this;
}
void TMetadataEntry::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TMetadataEntry(";
  out << "iceberg_metadata="; (__isset.iceberg_metadata ? (out << to_string(iceberg_metadata)) : (out << "<null>"));
  out << ")";
}

} // namespace
