/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "DataCache_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace starrocks {

int _kTDataCacheStatusValues[] = {
  TDataCacheStatus::DISABLED,
  TDataCacheStatus::NORMAL,
  TDataCacheStatus::UPDATING,
  TDataCacheStatus::ABNORMAL,
  TDataCacheStatus::LOADING
};
const char* _kTDataCacheStatusNames[] = {
  "DISABLED",
  "NORMAL",
  "UPDATING",
  "ABNORMAL",
  "LOADING"
};
const std::map<int, const char*> _TDataCacheStatus_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(5, _kTDataCacheStatusValues, _kTDataCacheStatusNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const TDataCacheStatus::type& val) {
  std::map<int, const char*>::const_iterator it = _TDataCacheStatus_VALUES_TO_NAMES.find(val);
  if (it != _TDataCacheStatus_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const TDataCacheStatus::type& val) {
  std::map<int, const char*>::const_iterator it = _TDataCacheStatus_VALUES_TO_NAMES.find(val);
  if (it != _TDataCacheStatus_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


TDataCacheOptions::~TDataCacheOptions() noexcept {
}

TDataCacheOptions::TDataCacheOptions() noexcept
   : enable_populate_datacache(0),
     priority(0) {
}

void TDataCacheOptions::__set_enable_populate_datacache(const bool val) {
  this->enable_populate_datacache = val;
__isset.enable_populate_datacache = true;
}

void TDataCacheOptions::__set_priority(const int32_t val) {
  this->priority = val;
__isset.priority = true;
}
std::ostream& operator<<(std::ostream& out, const TDataCacheOptions& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TDataCacheOptions::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 2:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->enable_populate_datacache);
          this->__isset.enable_populate_datacache = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 100:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->priority);
          this->__isset.priority = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TDataCacheOptions::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TDataCacheOptions");

  if (this->__isset.enable_populate_datacache) {
    xfer += oprot->writeFieldBegin("enable_populate_datacache", ::apache::thrift::protocol::T_BOOL, 2);
    xfer += oprot->writeBool(this->enable_populate_datacache);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.priority) {
    xfer += oprot->writeFieldBegin("priority", ::apache::thrift::protocol::T_I32, 100);
    xfer += oprot->writeI32(this->priority);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TDataCacheOptions &a, TDataCacheOptions &b) {
  using ::std::swap;
  swap(a.enable_populate_datacache, b.enable_populate_datacache);
  swap(a.priority, b.priority);
  swap(a.__isset, b.__isset);
}

bool TDataCacheOptions::operator==(const TDataCacheOptions & rhs) const
{
  if (__isset.enable_populate_datacache != rhs.__isset.enable_populate_datacache)
    return false;
  else if (__isset.enable_populate_datacache && !(enable_populate_datacache == rhs.enable_populate_datacache))
    return false;
  if (__isset.priority != rhs.__isset.priority)
    return false;
  else if (__isset.priority && !(priority == rhs.priority))
    return false;
  return true;
}

TDataCacheOptions::TDataCacheOptions(const TDataCacheOptions& other0) noexcept {
  enable_populate_datacache = other0.enable_populate_datacache;
  priority = other0.priority;
  __isset = other0.__isset;
}
TDataCacheOptions& TDataCacheOptions::operator=(const TDataCacheOptions& other1) noexcept {
  enable_populate_datacache = other1.enable_populate_datacache;
  priority = other1.priority;
  __isset = other1.__isset;
  return *this;
}
void TDataCacheOptions::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TDataCacheOptions(";
  out << "enable_populate_datacache="; (__isset.enable_populate_datacache ? (out << to_string(enable_populate_datacache)) : (out << "<null>"));
  out << ", " << "priority="; (__isset.priority ? (out << to_string(priority)) : (out << "<null>"));
  out << ")";
}


TDataCacheMetrics::~TDataCacheMetrics() noexcept {
}

TDataCacheMetrics::TDataCacheMetrics() noexcept
   : status(static_cast<TDataCacheStatus::type>(0)),
     mem_quota_bytes(0),
     mem_used_bytes(0),
     disk_quota_bytes(0),
     disk_used_bytes(0) {
}

void TDataCacheMetrics::__set_status(const TDataCacheStatus::type val) {
  this->status = val;
__isset.status = true;
}

void TDataCacheMetrics::__set_mem_quota_bytes(const int64_t val) {
  this->mem_quota_bytes = val;
__isset.mem_quota_bytes = true;
}

void TDataCacheMetrics::__set_mem_used_bytes(const int64_t val) {
  this->mem_used_bytes = val;
__isset.mem_used_bytes = true;
}

void TDataCacheMetrics::__set_disk_quota_bytes(const int64_t val) {
  this->disk_quota_bytes = val;
__isset.disk_quota_bytes = true;
}

void TDataCacheMetrics::__set_disk_used_bytes(const int64_t val) {
  this->disk_used_bytes = val;
__isset.disk_used_bytes = true;
}
std::ostream& operator<<(std::ostream& out, const TDataCacheMetrics& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TDataCacheMetrics::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast2;
          xfer += iprot->readI32(ecast2);
          this->status = static_cast<TDataCacheStatus::type>(ecast2);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->mem_quota_bytes);
          this->__isset.mem_quota_bytes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->mem_used_bytes);
          this->__isset.mem_used_bytes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->disk_quota_bytes);
          this->__isset.disk_quota_bytes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->disk_used_bytes);
          this->__isset.disk_used_bytes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TDataCacheMetrics::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TDataCacheMetrics");

  if (this->__isset.status) {
    xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
    xfer += oprot->writeI32(static_cast<int32_t>(this->status));
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.mem_quota_bytes) {
    xfer += oprot->writeFieldBegin("mem_quota_bytes", ::apache::thrift::protocol::T_I64, 2);
    xfer += oprot->writeI64(this->mem_quota_bytes);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.mem_used_bytes) {
    xfer += oprot->writeFieldBegin("mem_used_bytes", ::apache::thrift::protocol::T_I64, 3);
    xfer += oprot->writeI64(this->mem_used_bytes);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.disk_quota_bytes) {
    xfer += oprot->writeFieldBegin("disk_quota_bytes", ::apache::thrift::protocol::T_I64, 4);
    xfer += oprot->writeI64(this->disk_quota_bytes);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.disk_used_bytes) {
    xfer += oprot->writeFieldBegin("disk_used_bytes", ::apache::thrift::protocol::T_I64, 5);
    xfer += oprot->writeI64(this->disk_used_bytes);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TDataCacheMetrics &a, TDataCacheMetrics &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.mem_quota_bytes, b.mem_quota_bytes);
  swap(a.mem_used_bytes, b.mem_used_bytes);
  swap(a.disk_quota_bytes, b.disk_quota_bytes);
  swap(a.disk_used_bytes, b.disk_used_bytes);
  swap(a.__isset, b.__isset);
}

bool TDataCacheMetrics::operator==(const TDataCacheMetrics & rhs) const
{
  if (__isset.status != rhs.__isset.status)
    return false;
  else if (__isset.status && !(status == rhs.status))
    return false;
  if (__isset.mem_quota_bytes != rhs.__isset.mem_quota_bytes)
    return false;
  else if (__isset.mem_quota_bytes && !(mem_quota_bytes == rhs.mem_quota_bytes))
    return false;
  if (__isset.mem_used_bytes != rhs.__isset.mem_used_bytes)
    return false;
  else if (__isset.mem_used_bytes && !(mem_used_bytes == rhs.mem_used_bytes))
    return false;
  if (__isset.disk_quota_bytes != rhs.__isset.disk_quota_bytes)
    return false;
  else if (__isset.disk_quota_bytes && !(disk_quota_bytes == rhs.disk_quota_bytes))
    return false;
  if (__isset.disk_used_bytes != rhs.__isset.disk_used_bytes)
    return false;
  else if (__isset.disk_used_bytes && !(disk_used_bytes == rhs.disk_used_bytes))
    return false;
  return true;
}

TDataCacheMetrics::TDataCacheMetrics(const TDataCacheMetrics& other3) noexcept {
  status = other3.status;
  mem_quota_bytes = other3.mem_quota_bytes;
  mem_used_bytes = other3.mem_used_bytes;
  disk_quota_bytes = other3.disk_quota_bytes;
  disk_used_bytes = other3.disk_used_bytes;
  __isset = other3.__isset;
}
TDataCacheMetrics& TDataCacheMetrics::operator=(const TDataCacheMetrics& other4) noexcept {
  status = other4.status;
  mem_quota_bytes = other4.mem_quota_bytes;
  mem_used_bytes = other4.mem_used_bytes;
  disk_quota_bytes = other4.disk_quota_bytes;
  disk_used_bytes = other4.disk_used_bytes;
  __isset = other4.__isset;
  return *this;
}
void TDataCacheMetrics::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TDataCacheMetrics(";
  out << "status="; (__isset.status ? (out << to_string(status)) : (out << "<null>"));
  out << ", " << "mem_quota_bytes="; (__isset.mem_quota_bytes ? (out << to_string(mem_quota_bytes)) : (out << "<null>"));
  out << ", " << "mem_used_bytes="; (__isset.mem_used_bytes ? (out << to_string(mem_used_bytes)) : (out << "<null>"));
  out << ", " << "disk_quota_bytes="; (__isset.disk_quota_bytes ? (out << to_string(disk_quota_bytes)) : (out << "<null>"));
  out << ", " << "disk_used_bytes="; (__isset.disk_used_bytes ? (out << to_string(disk_used_bytes)) : (out << "<null>"));
  out << ")";
}


TLoadDataCacheMetrics::~TLoadDataCacheMetrics() noexcept {
}

TLoadDataCacheMetrics::TLoadDataCacheMetrics() noexcept
   : read_bytes(0),
     read_time_ns(0),
     write_bytes(0),
     write_time_ns(0),
     count(0) {
}

void TLoadDataCacheMetrics::__set_read_bytes(const int64_t val) {
  this->read_bytes = val;
__isset.read_bytes = true;
}

void TLoadDataCacheMetrics::__set_read_time_ns(const int64_t val) {
  this->read_time_ns = val;
__isset.read_time_ns = true;
}

void TLoadDataCacheMetrics::__set_write_bytes(const int64_t val) {
  this->write_bytes = val;
__isset.write_bytes = true;
}

void TLoadDataCacheMetrics::__set_write_time_ns(const int64_t val) {
  this->write_time_ns = val;
__isset.write_time_ns = true;
}

void TLoadDataCacheMetrics::__set_count(const int64_t val) {
  this->count = val;
__isset.count = true;
}

void TLoadDataCacheMetrics::__set_metrics(const TDataCacheMetrics& val) {
  this->metrics = val;
__isset.metrics = true;
}
std::ostream& operator<<(std::ostream& out, const TLoadDataCacheMetrics& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TLoadDataCacheMetrics::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->read_bytes);
          this->__isset.read_bytes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->read_time_ns);
          this->__isset.read_time_ns = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->write_bytes);
          this->__isset.write_bytes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->write_time_ns);
          this->__isset.write_time_ns = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->count);
          this->__isset.count = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->metrics.read(iprot);
          this->__isset.metrics = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TLoadDataCacheMetrics::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TLoadDataCacheMetrics");

  if (this->__isset.read_bytes) {
    xfer += oprot->writeFieldBegin("read_bytes", ::apache::thrift::protocol::T_I64, 1);
    xfer += oprot->writeI64(this->read_bytes);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.read_time_ns) {
    xfer += oprot->writeFieldBegin("read_time_ns", ::apache::thrift::protocol::T_I64, 2);
    xfer += oprot->writeI64(this->read_time_ns);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.write_bytes) {
    xfer += oprot->writeFieldBegin("write_bytes", ::apache::thrift::protocol::T_I64, 3);
    xfer += oprot->writeI64(this->write_bytes);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.write_time_ns) {
    xfer += oprot->writeFieldBegin("write_time_ns", ::apache::thrift::protocol::T_I64, 4);
    xfer += oprot->writeI64(this->write_time_ns);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.count) {
    xfer += oprot->writeFieldBegin("count", ::apache::thrift::protocol::T_I64, 5);
    xfer += oprot->writeI64(this->count);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.metrics) {
    xfer += oprot->writeFieldBegin("metrics", ::apache::thrift::protocol::T_STRUCT, 6);
    xfer += this->metrics.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TLoadDataCacheMetrics &a, TLoadDataCacheMetrics &b) {
  using ::std::swap;
  swap(a.read_bytes, b.read_bytes);
  swap(a.read_time_ns, b.read_time_ns);
  swap(a.write_bytes, b.write_bytes);
  swap(a.write_time_ns, b.write_time_ns);
  swap(a.count, b.count);
  swap(a.metrics, b.metrics);
  swap(a.__isset, b.__isset);
}

bool TLoadDataCacheMetrics::operator==(const TLoadDataCacheMetrics & rhs) const
{
  if (__isset.read_bytes != rhs.__isset.read_bytes)
    return false;
  else if (__isset.read_bytes && !(read_bytes == rhs.read_bytes))
    return false;
  if (__isset.read_time_ns != rhs.__isset.read_time_ns)
    return false;
  else if (__isset.read_time_ns && !(read_time_ns == rhs.read_time_ns))
    return false;
  if (__isset.write_bytes != rhs.__isset.write_bytes)
    return false;
  else if (__isset.write_bytes && !(write_bytes == rhs.write_bytes))
    return false;
  if (__isset.write_time_ns != rhs.__isset.write_time_ns)
    return false;
  else if (__isset.write_time_ns && !(write_time_ns == rhs.write_time_ns))
    return false;
  if (__isset.count != rhs.__isset.count)
    return false;
  else if (__isset.count && !(count == rhs.count))
    return false;
  if (__isset.metrics != rhs.__isset.metrics)
    return false;
  else if (__isset.metrics && !(metrics == rhs.metrics))
    return false;
  return true;
}

TLoadDataCacheMetrics::TLoadDataCacheMetrics(const TLoadDataCacheMetrics& other5) noexcept {
  read_bytes = other5.read_bytes;
  read_time_ns = other5.read_time_ns;
  write_bytes = other5.write_bytes;
  write_time_ns = other5.write_time_ns;
  count = other5.count;
  metrics = other5.metrics;
  __isset = other5.__isset;
}
TLoadDataCacheMetrics& TLoadDataCacheMetrics::operator=(const TLoadDataCacheMetrics& other6) noexcept {
  read_bytes = other6.read_bytes;
  read_time_ns = other6.read_time_ns;
  write_bytes = other6.write_bytes;
  write_time_ns = other6.write_time_ns;
  count = other6.count;
  metrics = other6.metrics;
  __isset = other6.__isset;
  return *this;
}
void TLoadDataCacheMetrics::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TLoadDataCacheMetrics(";
  out << "read_bytes="; (__isset.read_bytes ? (out << to_string(read_bytes)) : (out << "<null>"));
  out << ", " << "read_time_ns="; (__isset.read_time_ns ? (out << to_string(read_time_ns)) : (out << "<null>"));
  out << ", " << "write_bytes="; (__isset.write_bytes ? (out << to_string(write_bytes)) : (out << "<null>"));
  out << ", " << "write_time_ns="; (__isset.write_time_ns ? (out << to_string(write_time_ns)) : (out << "<null>"));
  out << ", " << "count="; (__isset.count ? (out << to_string(count)) : (out << "<null>"));
  out << ", " << "metrics="; (__isset.metrics ? (out << to_string(metrics)) : (out << "<null>"));
  out << ")";
}

} // namespace
