/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DataCache_TYPES_H
#define DataCache_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace starrocks {

struct TDataCacheStatus {
  enum type {
    DISABLED = 0,
    NORMAL = 1,
    UPDATING = 2,
    ABNORMAL = 3,
    LOADING = 4
  };
};

extern const std::map<int, const char*> _TDataCacheStatus_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TDataCacheStatus::type& val);

std::string to_string(const TDataCacheStatus::type& val);

class TDataCacheOptions;

class TDataCacheMetrics;

class TLoadDataCacheMetrics;

typedef struct _TDataCacheOptions__isset {
  _TDataCacheOptions__isset() : enable_populate_datacache(false), priority(false) {}
  bool enable_populate_datacache :1;
  bool priority :1;
} _TDataCacheOptions__isset;

class TDataCacheOptions : public virtual ::apache::thrift::TBase {
 public:

  TDataCacheOptions(const TDataCacheOptions&) noexcept;
  TDataCacheOptions& operator=(const TDataCacheOptions&) noexcept;
  TDataCacheOptions() noexcept;

  virtual ~TDataCacheOptions() noexcept;
  bool enable_populate_datacache;
  int32_t priority;

  _TDataCacheOptions__isset __isset;

  void __set_enable_populate_datacache(const bool val);

  void __set_priority(const int32_t val);

  bool operator == (const TDataCacheOptions & rhs) const;
  bool operator != (const TDataCacheOptions &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDataCacheOptions & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TDataCacheOptions &a, TDataCacheOptions &b);

std::ostream& operator<<(std::ostream& out, const TDataCacheOptions& obj);

typedef struct _TDataCacheMetrics__isset {
  _TDataCacheMetrics__isset() : status(false), mem_quota_bytes(false), mem_used_bytes(false), disk_quota_bytes(false), disk_used_bytes(false) {}
  bool status :1;
  bool mem_quota_bytes :1;
  bool mem_used_bytes :1;
  bool disk_quota_bytes :1;
  bool disk_used_bytes :1;
} _TDataCacheMetrics__isset;

class TDataCacheMetrics : public virtual ::apache::thrift::TBase {
 public:

  TDataCacheMetrics(const TDataCacheMetrics&) noexcept;
  TDataCacheMetrics& operator=(const TDataCacheMetrics&) noexcept;
  TDataCacheMetrics() noexcept;

  virtual ~TDataCacheMetrics() noexcept;
  /**
   * 
   * @see TDataCacheStatus
   */
  TDataCacheStatus::type status;
  int64_t mem_quota_bytes;
  int64_t mem_used_bytes;
  int64_t disk_quota_bytes;
  int64_t disk_used_bytes;

  _TDataCacheMetrics__isset __isset;

  void __set_status(const TDataCacheStatus::type val);

  void __set_mem_quota_bytes(const int64_t val);

  void __set_mem_used_bytes(const int64_t val);

  void __set_disk_quota_bytes(const int64_t val);

  void __set_disk_used_bytes(const int64_t val);

  bool operator == (const TDataCacheMetrics & rhs) const;
  bool operator != (const TDataCacheMetrics &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDataCacheMetrics & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TDataCacheMetrics &a, TDataCacheMetrics &b);

std::ostream& operator<<(std::ostream& out, const TDataCacheMetrics& obj);

typedef struct _TLoadDataCacheMetrics__isset {
  _TLoadDataCacheMetrics__isset() : read_bytes(false), read_time_ns(false), write_bytes(false), write_time_ns(false), count(false), metrics(false) {}
  bool read_bytes :1;
  bool read_time_ns :1;
  bool write_bytes :1;
  bool write_time_ns :1;
  bool count :1;
  bool metrics :1;
} _TLoadDataCacheMetrics__isset;

class TLoadDataCacheMetrics : public virtual ::apache::thrift::TBase {
 public:

  TLoadDataCacheMetrics(const TLoadDataCacheMetrics&) noexcept;
  TLoadDataCacheMetrics& operator=(const TLoadDataCacheMetrics&) noexcept;
  TLoadDataCacheMetrics() noexcept;

  virtual ~TLoadDataCacheMetrics() noexcept;
  int64_t read_bytes;
  int64_t read_time_ns;
  int64_t write_bytes;
  int64_t write_time_ns;
  int64_t count;
  TDataCacheMetrics metrics;

  _TLoadDataCacheMetrics__isset __isset;

  void __set_read_bytes(const int64_t val);

  void __set_read_time_ns(const int64_t val);

  void __set_write_bytes(const int64_t val);

  void __set_write_time_ns(const int64_t val);

  void __set_count(const int64_t val);

  void __set_metrics(const TDataCacheMetrics& val);

  bool operator == (const TLoadDataCacheMetrics & rhs) const;
  bool operator != (const TLoadDataCacheMetrics &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TLoadDataCacheMetrics & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TLoadDataCacheMetrics &a, TLoadDataCacheMetrics &b);

std::ostream& operator<<(std::ostream& out, const TLoadDataCacheMetrics& obj);

} // namespace

#endif
