/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Descriptors_TYPES_H
#define Descriptors_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>
#include "Types_types.h"
#include "Exprs_types.h"


namespace starrocks {

struct THdfsFileFormat {
  enum type {
    TEXT = 0,
    LZO_TEXT = 1,
    RC_BINARY = 2,
    RC_TEXT = 3,
    AVRO = 4,
    PARQUET = 5,
    ORC = 6,
    SEQUENCE_FILE = 7,
    UNKNOWN = 100
  };
};

extern const std::map<int, const char*> _THdfsFileFormat_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const THdfsFileFormat::type& val);

std::string to_string(const THdfsFileFormat::type& val);

struct TSchemaTableType {
  enum type {
    SCH_AUTHORS = 0,
    SCH_CHARSETS = 1,
    SCH_COLLATIONS = 2,
    SCH_COLLATION_CHARACTER_SET_APPLICABILITY = 3,
    SCH_COLUMNS = 4,
    SCH_COLUMN_PRIVILEGES = 5,
    SCH_CREATE_TABLE = 6,
    SCH_ENGINES = 7,
    SCH_EVENTS = 8,
    SCH_FILES = 9,
    SCH_GLOBAL_STATUS = 10,
    SCH_GLOBAL_VARIABLES = 11,
    SCH_KEY_COLUMN_USAGE = 12,
    SCH_MATERIALIZED_VIEWS = 13,
    SCH_OPEN_TABLES = 14,
    SCH_PARTITIONS = 15,
    SCH_PLUGINS = 16,
    SCH_PROCESSLIST = 17,
    SCH_PROFILES = 18,
    SCH_REFERENTIAL_CONSTRAINTS = 19,
    SCH_PROCEDURES = 20,
    SCH_SCHEMATA = 21,
    SCH_SCHEMA_PRIVILEGES = 22,
    SCH_SESSION_STATUS = 23,
    SCH_SESSION_VARIABLES = 24,
    SCH_STATISTICS = 25,
    SCH_STATUS = 26,
    SCH_TABLES = 27,
    SCH_TABLES_CONFIG = 28,
    SCH_TABLE_CONSTRAINTS = 29,
    SCH_TABLE_NAMES = 30,
    SCH_TABLE_PRIVILEGES = 31,
    SCH_TRIGGERS = 32,
    SCH_USER_PRIVILEGES = 33,
    SCH_VARIABLES = 34,
    SCH_VIEWS = 35,
    SCH_TASKS = 36,
    SCH_TASK_RUNS = 37,
    SCH_VERBOSE_SESSION_VARIABLES = 38,
    SCH_BE_TABLETS = 39,
    SCH_BE_METRICS = 40,
    SCH_BE_TXNS = 41,
    SCH_BE_CONFIGS = 42,
    SCH_LOADS = 43,
    SCH_LOAD_TRACKING_LOGS = 44,
    SCH_FE_TABLET_SCHEDULES = 45,
    SCH_BE_COMPACTIONS = 46,
    SCH_BE_THREADS = 47,
    SCH_BE_LOGS = 48,
    SCH_BE_BVARS = 49,
    SCH_BE_CLOUD_NATIVE_COMPACTIONS = 50,
    STARROCKS_ROLE_EDGES = 51,
    STARROCKS_GRANT_TO_ROLES = 52,
    STARROCKS_GRANT_TO_USERS = 53,
    SCH_ROUTINE_LOAD_JOBS = 54,
    SCH_STREAM_LOADS = 55,
    SCH_PIPE_FILES = 56,
    SCH_PIPES = 57,
    SCH_FE_METRICS = 58,
    STARROCKS_OBJECT_DEPENDENCIES = 59,
    SYS_FE_LOCKS = 60,
    SYS_FE_MEMORY_USAGE = 61,
    SCH_PARTITIONS_META = 62,
    SCH_BE_DATACACHE_METRICS = 63,
    SCH_TEMP_TABLES = 64
  };
};

extern const std::map<int, const char*> _TSchemaTableType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TSchemaTableType::type& val);

std::string to_string(const TSchemaTableType::type& val);

struct THdfsCompression {
  enum type {
    NONE = 0,
    DEFAULT = 1,
    GZIP = 2,
    DEFLATE = 3,
    BZIP2 = 4,
    SNAPPY = 5,
    SNAPPY_BLOCKED = 6
  };
};

extern const std::map<int, const char*> _THdfsCompression_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const THdfsCompression::type& val);

std::string to_string(const THdfsCompression::type& val);

struct TIndexType {
  enum type {
    BITMAP = 0,
    GIN = 1,
    NGRAMBF = 2
  };
};

extern const std::map<int, const char*> _TIndexType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TIndexType::type& val);

std::string to_string(const TIndexType::type& val);

struct TIMTType {
  enum type {
    OLAP_TABLE = 0,
    ROWSTORE_TABLE = 1
  };
};

extern const std::map<int, const char*> _TIMTType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TIMTType::type& val);

std::string to_string(const TIMTType::type& val);

class TSlotDescriptor;

class TTupleDescriptor;

class TTextFileDesc;

class TColumn;

class TOlapTableIndexTablets;

class TOlapTablePartition;

class TOlapTablePartitionParam;

class TOlapTableColumnParam;

class TOlapTableIndexSchema;

class TOlapTableSchemaParam;

class TOlapTableIndex;

class TTabletLocation;

class TOlapTableLocationParam;

class TNodeInfo;

class TNodesInfo;

class TOlapTable;

class TMySQLTable;

class TEsTable;

class TSchemaTable;

class TBrokerTable;

class THdfsPartitionLocation;

class THdfsPartition;

class THdfsTable;

class TFileTable;

class TTableFunctionTable;

class TIcebergSchema;

class TIcebergSchemaField;

class TPartitionMap;

class TCompressedPartitionMap;

class TIcebergTable;

class THudiTable;

class TPaimonTable;

class TDeltaLakeTable;

class TJDBCTable;

class TTableDescriptor;

class TDescriptorTable;

class TOlapTableRouteInfo;

class TIMTDescriptor;

typedef struct _TSlotDescriptor__isset {
  _TSlotDescriptor__isset() : id(false), parent(false), slotType(false), columnPos(false), byteOffset(false), nullIndicatorByte(false), nullIndicatorBit(false), colName(false), slotIdx(false), isMaterialized(false), isOutputColumn(false), isNullable(false), col_unique_id(true) {}
  bool id :1;
  bool parent :1;
  bool slotType :1;
  bool columnPos :1;
  bool byteOffset :1;
  bool nullIndicatorByte :1;
  bool nullIndicatorBit :1;
  bool colName :1;
  bool slotIdx :1;
  bool isMaterialized :1;
  bool isOutputColumn :1;
  bool isNullable :1;
  bool col_unique_id :1;
} _TSlotDescriptor__isset;

class TSlotDescriptor : public virtual ::apache::thrift::TBase {
 public:

  TSlotDescriptor(const TSlotDescriptor&);
  TSlotDescriptor& operator=(const TSlotDescriptor&);
  TSlotDescriptor() noexcept;

  virtual ~TSlotDescriptor() noexcept;
   ::starrocks::TSlotId id;
   ::starrocks::TTupleId parent;
   ::starrocks::TTypeDesc slotType;
  int32_t columnPos;
  int32_t byteOffset;
  int32_t nullIndicatorByte;
  int32_t nullIndicatorBit;
  std::string colName;
  int32_t slotIdx;
  bool isMaterialized;
  bool isOutputColumn;
  bool isNullable;
  int32_t col_unique_id;

  _TSlotDescriptor__isset __isset;

  void __set_id(const  ::starrocks::TSlotId val);

  void __set_parent(const  ::starrocks::TTupleId val);

  void __set_slotType(const  ::starrocks::TTypeDesc& val);

  void __set_columnPos(const int32_t val);

  void __set_byteOffset(const int32_t val);

  void __set_nullIndicatorByte(const int32_t val);

  void __set_nullIndicatorBit(const int32_t val);

  void __set_colName(const std::string& val);

  void __set_slotIdx(const int32_t val);

  void __set_isMaterialized(const bool val);

  void __set_isOutputColumn(const bool val);

  void __set_isNullable(const bool val);

  void __set_col_unique_id(const int32_t val);

  bool operator == (const TSlotDescriptor & rhs) const;
  bool operator != (const TSlotDescriptor &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TSlotDescriptor & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TSlotDescriptor &a, TSlotDescriptor &b);

std::ostream& operator<<(std::ostream& out, const TSlotDescriptor& obj);

typedef struct _TTupleDescriptor__isset {
  _TTupleDescriptor__isset() : id(false), byteSize(false), numNullBytes(false), tableId(false), numNullSlots(false) {}
  bool id :1;
  bool byteSize :1;
  bool numNullBytes :1;
  bool tableId :1;
  bool numNullSlots :1;
} _TTupleDescriptor__isset;

class TTupleDescriptor : public virtual ::apache::thrift::TBase {
 public:

  TTupleDescriptor(const TTupleDescriptor&) noexcept;
  TTupleDescriptor& operator=(const TTupleDescriptor&) noexcept;
  TTupleDescriptor() noexcept;

  virtual ~TTupleDescriptor() noexcept;
   ::starrocks::TTupleId id;
  int32_t byteSize;
  int32_t numNullBytes;
   ::starrocks::TTableId tableId;
  int32_t numNullSlots;

  _TTupleDescriptor__isset __isset;

  void __set_id(const  ::starrocks::TTupleId val);

  void __set_byteSize(const int32_t val);

  void __set_numNullBytes(const int32_t val);

  void __set_tableId(const  ::starrocks::TTableId val);

  void __set_numNullSlots(const int32_t val);

  bool operator == (const TTupleDescriptor & rhs) const;
  bool operator != (const TTupleDescriptor &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TTupleDescriptor & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TTupleDescriptor &a, TTupleDescriptor &b);

std::ostream& operator<<(std::ostream& out, const TTupleDescriptor& obj);

typedef struct _TTextFileDesc__isset {
  _TTextFileDesc__isset() : field_delim(false), line_delim(false), collection_delim(false), mapkey_delim(false), compression_type(false), trim_space(false), enclose(false), escape(false), skip_header_line_count(false) {}
  bool field_delim :1;
  bool line_delim :1;
  bool collection_delim :1;
  bool mapkey_delim :1;
  bool compression_type :1;
  bool trim_space :1;
  bool enclose :1;
  bool escape :1;
  bool skip_header_line_count :1;
} _TTextFileDesc__isset;

class TTextFileDesc : public virtual ::apache::thrift::TBase {
 public:

  TTextFileDesc(const TTextFileDesc&);
  TTextFileDesc& operator=(const TTextFileDesc&);
  TTextFileDesc() noexcept;

  virtual ~TTextFileDesc() noexcept;
  std::string field_delim;
  std::string line_delim;
  std::string collection_delim;
  std::string mapkey_delim;
  /**
   * 
   * @see com.starrocks.thrift.TCompressionType
   */
   ::starrocks::TCompressionType::type compression_type;
  bool trim_space;
  int8_t enclose;
  int8_t escape;
  int32_t skip_header_line_count;

  _TTextFileDesc__isset __isset;

  void __set_field_delim(const std::string& val);

  void __set_line_delim(const std::string& val);

  void __set_collection_delim(const std::string& val);

  void __set_mapkey_delim(const std::string& val);

  void __set_compression_type(const  ::starrocks::TCompressionType::type val);

  void __set_trim_space(const bool val);

  void __set_enclose(const int8_t val);

  void __set_escape(const int8_t val);

  void __set_skip_header_line_count(const int32_t val);

  bool operator == (const TTextFileDesc & rhs) const;
  bool operator != (const TTextFileDesc &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TTextFileDesc & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TTextFileDesc &a, TTextFileDesc &b);

std::ostream& operator<<(std::ostream& out, const TTextFileDesc& obj);

typedef struct _TColumn__isset {
  _TColumn__isset() : column_type(false), aggregation_type(false), is_key(false), is_allow_null(false), default_value(false), is_bloom_filter_column(false), define_expr(false), is_auto_increment(false), col_unique_id(true), has_bitmap_index(true), index_len(false), type_desc(false) {}
  bool column_type :1;
  bool aggregation_type :1;
  bool is_key :1;
  bool is_allow_null :1;
  bool default_value :1;
  bool is_bloom_filter_column :1;
  bool define_expr :1;
  bool is_auto_increment :1;
  bool col_unique_id :1;
  bool has_bitmap_index :1;
  bool index_len :1;
  bool type_desc :1;
} _TColumn__isset;

class TColumn : public virtual ::apache::thrift::TBase {
 public:

  TColumn(const TColumn&);
  TColumn& operator=(const TColumn&);
  TColumn() noexcept;

  virtual ~TColumn() noexcept;
  std::string column_name;
   ::starrocks::TColumnType column_type;
  /**
   * 
   * @see com.starrocks.thrift.TAggregationType
   */
   ::starrocks::TAggregationType::type aggregation_type;
  bool is_key;
  bool is_allow_null;
  std::string default_value;
  bool is_bloom_filter_column;
   ::starrocks::TExpr define_expr;
  bool is_auto_increment;
  int32_t col_unique_id;
  bool has_bitmap_index;
  int32_t index_len;
   ::starrocks::TTypeDesc type_desc;

  _TColumn__isset __isset;

  void __set_column_name(const std::string& val);

  void __set_column_type(const  ::starrocks::TColumnType& val);

  void __set_aggregation_type(const  ::starrocks::TAggregationType::type val);

  void __set_is_key(const bool val);

  void __set_is_allow_null(const bool val);

  void __set_default_value(const std::string& val);

  void __set_is_bloom_filter_column(const bool val);

  void __set_define_expr(const  ::starrocks::TExpr& val);

  void __set_is_auto_increment(const bool val);

  void __set_col_unique_id(const int32_t val);

  void __set_has_bitmap_index(const bool val);

  void __set_index_len(const int32_t val);

  void __set_type_desc(const  ::starrocks::TTypeDesc& val);

  bool operator == (const TColumn & rhs) const;
  bool operator != (const TColumn &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TColumn & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TColumn &a, TColumn &b);

std::ostream& operator<<(std::ostream& out, const TColumn& obj);


class TOlapTableIndexTablets : public virtual ::apache::thrift::TBase {
 public:

  TOlapTableIndexTablets(const TOlapTableIndexTablets&);
  TOlapTableIndexTablets& operator=(const TOlapTableIndexTablets&);
  TOlapTableIndexTablets() noexcept;

  virtual ~TOlapTableIndexTablets() noexcept;
  int64_t index_id;
  std::vector<int64_t>  tablets;

  void __set_index_id(const int64_t val);

  void __set_tablets(const std::vector<int64_t> & val);

  bool operator == (const TOlapTableIndexTablets & rhs) const;
  bool operator != (const TOlapTableIndexTablets &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TOlapTableIndexTablets & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TOlapTableIndexTablets &a, TOlapTableIndexTablets &b);

std::ostream& operator<<(std::ostream& out, const TOlapTableIndexTablets& obj);

typedef struct _TOlapTablePartition__isset {
  _TOlapTablePartition__isset() : start_key(false), end_key(false), start_keys(false), end_keys(false), in_keys(false), is_shadow_partition(true) {}
  bool start_key :1;
  bool end_key :1;
  bool start_keys :1;
  bool end_keys :1;
  bool in_keys :1;
  bool is_shadow_partition :1;
} _TOlapTablePartition__isset;

class TOlapTablePartition : public virtual ::apache::thrift::TBase {
 public:

  TOlapTablePartition(const TOlapTablePartition&);
  TOlapTablePartition& operator=(const TOlapTablePartition&);
  TOlapTablePartition() noexcept;

  virtual ~TOlapTablePartition() noexcept;
  int64_t id;
   ::starrocks::TExprNode start_key;
   ::starrocks::TExprNode end_key;
  int32_t num_buckets;
  std::vector<TOlapTableIndexTablets>  indexes;
  std::vector< ::starrocks::TExprNode>  start_keys;
  std::vector< ::starrocks::TExprNode>  end_keys;
  std::vector<std::vector< ::starrocks::TExprNode> >  in_keys;
  bool is_shadow_partition;

  _TOlapTablePartition__isset __isset;

  void __set_id(const int64_t val);

  void __set_start_key(const  ::starrocks::TExprNode& val);

  void __set_end_key(const  ::starrocks::TExprNode& val);

  void __set_num_buckets(const int32_t val);

  void __set_indexes(const std::vector<TOlapTableIndexTablets> & val);

  void __set_start_keys(const std::vector< ::starrocks::TExprNode> & val);

  void __set_end_keys(const std::vector< ::starrocks::TExprNode> & val);

  void __set_in_keys(const std::vector<std::vector< ::starrocks::TExprNode> > & val);

  void __set_is_shadow_partition(const bool val);

  bool operator == (const TOlapTablePartition & rhs) const;
  bool operator != (const TOlapTablePartition &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TOlapTablePartition & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TOlapTablePartition &a, TOlapTablePartition &b);

std::ostream& operator<<(std::ostream& out, const TOlapTablePartition& obj);

typedef struct _TOlapTablePartitionParam__isset {
  _TOlapTablePartitionParam__isset() : partition_column(false), distributed_columns(false), partition_columns(false), partition_exprs(false), enable_automatic_partition(false) {}
  bool partition_column :1;
  bool distributed_columns :1;
  bool partition_columns :1;
  bool partition_exprs :1;
  bool enable_automatic_partition :1;
} _TOlapTablePartitionParam__isset;

class TOlapTablePartitionParam : public virtual ::apache::thrift::TBase {
 public:

  TOlapTablePartitionParam(const TOlapTablePartitionParam&);
  TOlapTablePartitionParam& operator=(const TOlapTablePartitionParam&);
  TOlapTablePartitionParam() noexcept;

  virtual ~TOlapTablePartitionParam() noexcept;
  int64_t db_id;
  int64_t table_id;
  int64_t version;
  std::string partition_column;
  std::vector<std::string>  distributed_columns;
  std::vector<TOlapTablePartition>  partitions;
  std::vector<std::string>  partition_columns;
  std::vector< ::starrocks::TExpr>  partition_exprs;
  bool enable_automatic_partition;

  _TOlapTablePartitionParam__isset __isset;

  void __set_db_id(const int64_t val);

  void __set_table_id(const int64_t val);

  void __set_version(const int64_t val);

  void __set_partition_column(const std::string& val);

  void __set_distributed_columns(const std::vector<std::string> & val);

  void __set_partitions(const std::vector<TOlapTablePartition> & val);

  void __set_partition_columns(const std::vector<std::string> & val);

  void __set_partition_exprs(const std::vector< ::starrocks::TExpr> & val);

  void __set_enable_automatic_partition(const bool val);

  bool operator == (const TOlapTablePartitionParam & rhs) const;
  bool operator != (const TOlapTablePartitionParam &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TOlapTablePartitionParam & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TOlapTablePartitionParam &a, TOlapTablePartitionParam &b);

std::ostream& operator<<(std::ostream& out, const TOlapTablePartitionParam& obj);


class TOlapTableColumnParam : public virtual ::apache::thrift::TBase {
 public:

  TOlapTableColumnParam(const TOlapTableColumnParam&);
  TOlapTableColumnParam& operator=(const TOlapTableColumnParam&);
  TOlapTableColumnParam() noexcept;

  virtual ~TOlapTableColumnParam() noexcept;
  std::vector<TColumn>  columns;
  std::vector<int32_t>  sort_key_uid;
  int32_t short_key_column_count;

  void __set_columns(const std::vector<TColumn> & val);

  void __set_sort_key_uid(const std::vector<int32_t> & val);

  void __set_short_key_column_count(const int32_t val);

  bool operator == (const TOlapTableColumnParam & rhs) const;
  bool operator != (const TOlapTableColumnParam &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TOlapTableColumnParam & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TOlapTableColumnParam &a, TOlapTableColumnParam &b);

std::ostream& operator<<(std::ostream& out, const TOlapTableColumnParam& obj);

typedef struct _TOlapTableIndexSchema__isset {
  _TOlapTableIndexSchema__isset() : column_param(false), where_clause(false), schema_id(false) {}
  bool column_param :1;
  bool where_clause :1;
  bool schema_id :1;
} _TOlapTableIndexSchema__isset;

class TOlapTableIndexSchema : public virtual ::apache::thrift::TBase {
 public:

  TOlapTableIndexSchema(const TOlapTableIndexSchema&);
  TOlapTableIndexSchema& operator=(const TOlapTableIndexSchema&);
  TOlapTableIndexSchema() noexcept;

  virtual ~TOlapTableIndexSchema() noexcept;
  int64_t id;
  std::vector<std::string>  columns;
  int32_t schema_hash;
  TOlapTableColumnParam column_param;
   ::starrocks::TExpr where_clause;
  int64_t schema_id;

  _TOlapTableIndexSchema__isset __isset;

  void __set_id(const int64_t val);

  void __set_columns(const std::vector<std::string> & val);

  void __set_schema_hash(const int32_t val);

  void __set_column_param(const TOlapTableColumnParam& val);

  void __set_where_clause(const  ::starrocks::TExpr& val);

  void __set_schema_id(const int64_t val);

  bool operator == (const TOlapTableIndexSchema & rhs) const;
  bool operator != (const TOlapTableIndexSchema &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TOlapTableIndexSchema & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TOlapTableIndexSchema &a, TOlapTableIndexSchema &b);

std::ostream& operator<<(std::ostream& out, const TOlapTableIndexSchema& obj);


class TOlapTableSchemaParam : public virtual ::apache::thrift::TBase {
 public:

  TOlapTableSchemaParam(const TOlapTableSchemaParam&);
  TOlapTableSchemaParam& operator=(const TOlapTableSchemaParam&);
  TOlapTableSchemaParam() noexcept;

  virtual ~TOlapTableSchemaParam() noexcept;
  int64_t db_id;
  int64_t table_id;
  int64_t version;
  std::vector<TSlotDescriptor>  slot_descs;
  TTupleDescriptor tuple_desc;
  std::vector<TOlapTableIndexSchema>  indexes;

  void __set_db_id(const int64_t val);

  void __set_table_id(const int64_t val);

  void __set_version(const int64_t val);

  void __set_slot_descs(const std::vector<TSlotDescriptor> & val);

  void __set_tuple_desc(const TTupleDescriptor& val);

  void __set_indexes(const std::vector<TOlapTableIndexSchema> & val);

  bool operator == (const TOlapTableSchemaParam & rhs) const;
  bool operator != (const TOlapTableSchemaParam &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TOlapTableSchemaParam & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TOlapTableSchemaParam &a, TOlapTableSchemaParam &b);

std::ostream& operator<<(std::ostream& out, const TOlapTableSchemaParam& obj);

typedef struct _TOlapTableIndex__isset {
  _TOlapTableIndex__isset() : index_name(false), columns(false), index_type(false), comment(false), index_id(false), common_properties(false), index_properties(false), search_properties(false), extra_properties(false) {}
  bool index_name :1;
  bool columns :1;
  bool index_type :1;
  bool comment :1;
  bool index_id :1;
  bool common_properties :1;
  bool index_properties :1;
  bool search_properties :1;
  bool extra_properties :1;
} _TOlapTableIndex__isset;

class TOlapTableIndex : public virtual ::apache::thrift::TBase {
 public:

  TOlapTableIndex(const TOlapTableIndex&);
  TOlapTableIndex& operator=(const TOlapTableIndex&);
  TOlapTableIndex() noexcept;

  virtual ~TOlapTableIndex() noexcept;
  std::string index_name;
  std::vector<std::string>  columns;
  /**
   * 
   * @see TIndexType
   */
  TIndexType::type index_type;
  std::string comment;
  int64_t index_id;
  std::map<std::string, std::string>  common_properties;
  std::map<std::string, std::string>  index_properties;
  std::map<std::string, std::string>  search_properties;
  std::map<std::string, std::string>  extra_properties;

  _TOlapTableIndex__isset __isset;

  void __set_index_name(const std::string& val);

  void __set_columns(const std::vector<std::string> & val);

  void __set_index_type(const TIndexType::type val);

  void __set_comment(const std::string& val);

  void __set_index_id(const int64_t val);

  void __set_common_properties(const std::map<std::string, std::string> & val);

  void __set_index_properties(const std::map<std::string, std::string> & val);

  void __set_search_properties(const std::map<std::string, std::string> & val);

  void __set_extra_properties(const std::map<std::string, std::string> & val);

  bool operator == (const TOlapTableIndex & rhs) const;
  bool operator != (const TOlapTableIndex &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TOlapTableIndex & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TOlapTableIndex &a, TOlapTableIndex &b);

std::ostream& operator<<(std::ostream& out, const TOlapTableIndex& obj);


class TTabletLocation : public virtual ::apache::thrift::TBase {
 public:

  TTabletLocation(const TTabletLocation&);
  TTabletLocation& operator=(const TTabletLocation&);
  TTabletLocation() noexcept;

  virtual ~TTabletLocation() noexcept;
  int64_t tablet_id;
  std::vector<int64_t>  node_ids;

  void __set_tablet_id(const int64_t val);

  void __set_node_ids(const std::vector<int64_t> & val);

  bool operator == (const TTabletLocation & rhs) const;
  bool operator != (const TTabletLocation &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TTabletLocation & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TTabletLocation &a, TTabletLocation &b);

std::ostream& operator<<(std::ostream& out, const TTabletLocation& obj);


class TOlapTableLocationParam : public virtual ::apache::thrift::TBase {
 public:

  TOlapTableLocationParam(const TOlapTableLocationParam&);
  TOlapTableLocationParam& operator=(const TOlapTableLocationParam&);
  TOlapTableLocationParam() noexcept;

  virtual ~TOlapTableLocationParam() noexcept;
  int64_t db_id;
  int64_t table_id;
  int64_t version;
  std::vector<TTabletLocation>  tablets;

  void __set_db_id(const int64_t val);

  void __set_table_id(const int64_t val);

  void __set_version(const int64_t val);

  void __set_tablets(const std::vector<TTabletLocation> & val);

  bool operator == (const TOlapTableLocationParam & rhs) const;
  bool operator != (const TOlapTableLocationParam &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TOlapTableLocationParam & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TOlapTableLocationParam &a, TOlapTableLocationParam &b);

std::ostream& operator<<(std::ostream& out, const TOlapTableLocationParam& obj);


class TNodeInfo : public virtual ::apache::thrift::TBase {
 public:

  TNodeInfo(const TNodeInfo&);
  TNodeInfo& operator=(const TNodeInfo&);
  TNodeInfo() noexcept;

  virtual ~TNodeInfo() noexcept;
  int64_t id;
  int64_t option;
  std::string host;
  int32_t async_internal_port;

  void __set_id(const int64_t val);

  void __set_option(const int64_t val);

  void __set_host(const std::string& val);

  void __set_async_internal_port(const int32_t val);

  bool operator == (const TNodeInfo & rhs) const;
  bool operator != (const TNodeInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TNodeInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TNodeInfo &a, TNodeInfo &b);

std::ostream& operator<<(std::ostream& out, const TNodeInfo& obj);


class TNodesInfo : public virtual ::apache::thrift::TBase {
 public:

  TNodesInfo(const TNodesInfo&);
  TNodesInfo& operator=(const TNodesInfo&);
  TNodesInfo() noexcept;

  virtual ~TNodesInfo() noexcept;
  int64_t version;
  std::vector<TNodeInfo>  nodes;

  void __set_version(const int64_t val);

  void __set_nodes(const std::vector<TNodeInfo> & val);

  bool operator == (const TNodesInfo & rhs) const;
  bool operator != (const TNodesInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TNodesInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TNodesInfo &a, TNodesInfo &b);

std::ostream& operator<<(std::ostream& out, const TNodesInfo& obj);


class TOlapTable : public virtual ::apache::thrift::TBase {
 public:

  TOlapTable(const TOlapTable&);
  TOlapTable& operator=(const TOlapTable&);
  TOlapTable() noexcept;

  virtual ~TOlapTable() noexcept;
  std::string tableName;

  void __set_tableName(const std::string& val);

  bool operator == (const TOlapTable & rhs) const;
  bool operator != (const TOlapTable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TOlapTable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TOlapTable &a, TOlapTable &b);

std::ostream& operator<<(std::ostream& out, const TOlapTable& obj);


class TMySQLTable : public virtual ::apache::thrift::TBase {
 public:

  TMySQLTable(const TMySQLTable&);
  TMySQLTable& operator=(const TMySQLTable&);
  TMySQLTable() noexcept;

  virtual ~TMySQLTable() noexcept;
  std::string host;
  std::string port;
  std::string user;
  std::string passwd;
  std::string db;
  std::string table;

  void __set_host(const std::string& val);

  void __set_port(const std::string& val);

  void __set_user(const std::string& val);

  void __set_passwd(const std::string& val);

  void __set_db(const std::string& val);

  void __set_table(const std::string& val);

  bool operator == (const TMySQLTable & rhs) const;
  bool operator != (const TMySQLTable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TMySQLTable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TMySQLTable &a, TMySQLTable &b);

std::ostream& operator<<(std::ostream& out, const TMySQLTable& obj);


class TEsTable : public virtual ::apache::thrift::TBase {
 public:

  TEsTable(const TEsTable&) noexcept;
  TEsTable& operator=(const TEsTable&) noexcept;
  TEsTable() noexcept;

  virtual ~TEsTable() noexcept;

  bool operator == (const TEsTable & /* rhs */) const;
  bool operator != (const TEsTable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TEsTable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TEsTable &a, TEsTable &b);

std::ostream& operator<<(std::ostream& out, const TEsTable& obj);


class TSchemaTable : public virtual ::apache::thrift::TBase {
 public:

  TSchemaTable(const TSchemaTable&) noexcept;
  TSchemaTable& operator=(const TSchemaTable&) noexcept;
  TSchemaTable() noexcept;

  virtual ~TSchemaTable() noexcept;
  /**
   * 
   * @see TSchemaTableType
   */
  TSchemaTableType::type tableType;

  void __set_tableType(const TSchemaTableType::type val);

  bool operator == (const TSchemaTable & rhs) const;
  bool operator != (const TSchemaTable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TSchemaTable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TSchemaTable &a, TSchemaTable &b);

std::ostream& operator<<(std::ostream& out, const TSchemaTable& obj);


class TBrokerTable : public virtual ::apache::thrift::TBase {
 public:

  TBrokerTable(const TBrokerTable&) noexcept;
  TBrokerTable& operator=(const TBrokerTable&) noexcept;
  TBrokerTable() noexcept;

  virtual ~TBrokerTable() noexcept;

  bool operator == (const TBrokerTable & /* rhs */) const;
  bool operator != (const TBrokerTable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerTable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerTable &a, TBrokerTable &b);

std::ostream& operator<<(std::ostream& out, const TBrokerTable& obj);

typedef struct _THdfsPartitionLocation__isset {
  _THdfsPartitionLocation__isset() : prefix_index(true), suffix(false) {}
  bool prefix_index :1;
  bool suffix :1;
} _THdfsPartitionLocation__isset;

class THdfsPartitionLocation : public virtual ::apache::thrift::TBase {
 public:

  THdfsPartitionLocation(const THdfsPartitionLocation&);
  THdfsPartitionLocation& operator=(const THdfsPartitionLocation&);
  THdfsPartitionLocation() noexcept;

  virtual ~THdfsPartitionLocation() noexcept;
  int32_t prefix_index;
  std::string suffix;

  _THdfsPartitionLocation__isset __isset;

  void __set_prefix_index(const int32_t val);

  void __set_suffix(const std::string& val);

  bool operator == (const THdfsPartitionLocation & rhs) const;
  bool operator != (const THdfsPartitionLocation &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const THdfsPartitionLocation & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(THdfsPartitionLocation &a, THdfsPartitionLocation &b);

std::ostream& operator<<(std::ostream& out, const THdfsPartitionLocation& obj);

typedef struct _THdfsPartition__isset {
  _THdfsPartition__isset() : file_format(false), partition_key_exprs(false), location(false) {}
  bool file_format :1;
  bool partition_key_exprs :1;
  bool location :1;
} _THdfsPartition__isset;

class THdfsPartition : public virtual ::apache::thrift::TBase {
 public:

  THdfsPartition(const THdfsPartition&);
  THdfsPartition& operator=(const THdfsPartition&);
  THdfsPartition() noexcept;

  virtual ~THdfsPartition() noexcept;
  /**
   * 
   * @see THdfsFileFormat
   */
  THdfsFileFormat::type file_format;
  std::vector< ::starrocks::TExpr>  partition_key_exprs;
  THdfsPartitionLocation location;

  _THdfsPartition__isset __isset;

  void __set_file_format(const THdfsFileFormat::type val);

  void __set_partition_key_exprs(const std::vector< ::starrocks::TExpr> & val);

  void __set_location(const THdfsPartitionLocation& val);

  bool operator == (const THdfsPartition & rhs) const;
  bool operator != (const THdfsPartition &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const THdfsPartition & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(THdfsPartition &a, THdfsPartition &b);

std::ostream& operator<<(std::ostream& out, const THdfsPartition& obj);

typedef struct _THdfsTable__isset {
  _THdfsTable__isset() : hdfs_base_dir(false), columns(false), partition_columns(false), partitions(false), partition_prefixes(false), hive_column_names(false), hive_column_types(false), input_format(false), serde_lib(false), serde_properties(false), time_zone(false) {}
  bool hdfs_base_dir :1;
  bool columns :1;
  bool partition_columns :1;
  bool partitions :1;
  bool partition_prefixes :1;
  bool hive_column_names :1;
  bool hive_column_types :1;
  bool input_format :1;
  bool serde_lib :1;
  bool serde_properties :1;
  bool time_zone :1;
} _THdfsTable__isset;

class THdfsTable : public virtual ::apache::thrift::TBase {
 public:

  THdfsTable(const THdfsTable&);
  THdfsTable& operator=(const THdfsTable&);
  THdfsTable() noexcept;

  virtual ~THdfsTable() noexcept;
  std::string hdfs_base_dir;
  std::vector<TColumn>  columns;
  std::vector<TColumn>  partition_columns;
  std::map<int64_t, THdfsPartition>  partitions;
  std::vector<std::string>  partition_prefixes;
  std::string hive_column_names;
  std::string hive_column_types;
  std::string input_format;
  std::string serde_lib;
  std::map<std::string, std::string>  serde_properties;
  std::string time_zone;

  _THdfsTable__isset __isset;

  void __set_hdfs_base_dir(const std::string& val);

  void __set_columns(const std::vector<TColumn> & val);

  void __set_partition_columns(const std::vector<TColumn> & val);

  void __set_partitions(const std::map<int64_t, THdfsPartition> & val);

  void __set_partition_prefixes(const std::vector<std::string> & val);

  void __set_hive_column_names(const std::string& val);

  void __set_hive_column_types(const std::string& val);

  void __set_input_format(const std::string& val);

  void __set_serde_lib(const std::string& val);

  void __set_serde_properties(const std::map<std::string, std::string> & val);

  void __set_time_zone(const std::string& val);

  bool operator == (const THdfsTable & rhs) const;
  bool operator != (const THdfsTable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const THdfsTable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(THdfsTable &a, THdfsTable &b);

std::ostream& operator<<(std::ostream& out, const THdfsTable& obj);

typedef struct _TFileTable__isset {
  _TFileTable__isset() : location(false), columns(false), hive_column_names(false), hive_column_types(false), input_format(false), serde_lib(false), time_zone(false) {}
  bool location :1;
  bool columns :1;
  bool hive_column_names :1;
  bool hive_column_types :1;
  bool input_format :1;
  bool serde_lib :1;
  bool time_zone :1;
} _TFileTable__isset;

class TFileTable : public virtual ::apache::thrift::TBase {
 public:

  TFileTable(const TFileTable&);
  TFileTable& operator=(const TFileTable&);
  TFileTable() noexcept;

  virtual ~TFileTable() noexcept;
  std::string location;
  std::vector<TColumn>  columns;
  std::string hive_column_names;
  std::string hive_column_types;
  std::string input_format;
  std::string serde_lib;
  std::string time_zone;

  _TFileTable__isset __isset;

  void __set_location(const std::string& val);

  void __set_columns(const std::vector<TColumn> & val);

  void __set_hive_column_names(const std::string& val);

  void __set_hive_column_types(const std::string& val);

  void __set_input_format(const std::string& val);

  void __set_serde_lib(const std::string& val);

  void __set_time_zone(const std::string& val);

  bool operator == (const TFileTable & rhs) const;
  bool operator != (const TFileTable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TFileTable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TFileTable &a, TFileTable &b);

std::ostream& operator<<(std::ostream& out, const TFileTable& obj);

typedef struct _TTableFunctionTable__isset {
  _TTableFunctionTable__isset() : path(false), columns(false), file_format(false), compression_type(false), partition_column_ids(false), write_single_file(false), target_max_file_size(false), csv_row_delimiter(false), csv_column_seperator(false), parquet_use_legacy_encoding(false) {}
  bool path :1;
  bool columns :1;
  bool file_format :1;
  bool compression_type :1;
  bool partition_column_ids :1;
  bool write_single_file :1;
  bool target_max_file_size :1;
  bool csv_row_delimiter :1;
  bool csv_column_seperator :1;
  bool parquet_use_legacy_encoding :1;
} _TTableFunctionTable__isset;

class TTableFunctionTable : public virtual ::apache::thrift::TBase {
 public:

  TTableFunctionTable(const TTableFunctionTable&);
  TTableFunctionTable& operator=(const TTableFunctionTable&);
  TTableFunctionTable() noexcept;

  virtual ~TTableFunctionTable() noexcept;
  std::string path;
  std::vector<TColumn>  columns;
  std::string file_format;
  /**
   * 
   * @see com.starrocks.thrift.TCompressionType
   */
   ::starrocks::TCompressionType::type compression_type;
  std::vector<int32_t>  partition_column_ids;
  bool write_single_file;
  int64_t target_max_file_size;
  std::string csv_row_delimiter;
  std::string csv_column_seperator;
  bool parquet_use_legacy_encoding;

  _TTableFunctionTable__isset __isset;

  void __set_path(const std::string& val);

  void __set_columns(const std::vector<TColumn> & val);

  void __set_file_format(const std::string& val);

  void __set_compression_type(const  ::starrocks::TCompressionType::type val);

  void __set_partition_column_ids(const std::vector<int32_t> & val);

  void __set_write_single_file(const bool val);

  void __set_target_max_file_size(const int64_t val);

  void __set_csv_row_delimiter(const std::string& val);

  void __set_csv_column_seperator(const std::string& val);

  void __set_parquet_use_legacy_encoding(const bool val);

  bool operator == (const TTableFunctionTable & rhs) const;
  bool operator != (const TTableFunctionTable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TTableFunctionTable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TTableFunctionTable &a, TTableFunctionTable &b);

std::ostream& operator<<(std::ostream& out, const TTableFunctionTable& obj);

typedef struct _TIcebergSchema__isset {
  _TIcebergSchema__isset() : fields(false) {}
  bool fields :1;
} _TIcebergSchema__isset;

class TIcebergSchema : public virtual ::apache::thrift::TBase {
 public:

  TIcebergSchema(const TIcebergSchema&);
  TIcebergSchema& operator=(const TIcebergSchema&);
  TIcebergSchema() noexcept;

  virtual ~TIcebergSchema() noexcept;
  std::vector<TIcebergSchemaField>  fields;

  _TIcebergSchema__isset __isset;

  void __set_fields(const std::vector<TIcebergSchemaField> & val);

  bool operator == (const TIcebergSchema & rhs) const;
  bool operator != (const TIcebergSchema &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TIcebergSchema & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TIcebergSchema &a, TIcebergSchema &b);

std::ostream& operator<<(std::ostream& out, const TIcebergSchema& obj);

typedef struct _TIcebergSchemaField__isset {
  _TIcebergSchemaField__isset() : field_id(false), name(false), children(false) {}
  bool field_id :1;
  bool name :1;
  bool children :1;
} _TIcebergSchemaField__isset;

class TIcebergSchemaField : public virtual ::apache::thrift::TBase {
 public:

  TIcebergSchemaField(const TIcebergSchemaField&);
  TIcebergSchemaField& operator=(const TIcebergSchemaField&);
  TIcebergSchemaField() noexcept;

  virtual ~TIcebergSchemaField() noexcept;
  int32_t field_id;
  std::string name;
  std::vector<TIcebergSchemaField>  children;

  _TIcebergSchemaField__isset __isset;

  void __set_field_id(const int32_t val);

  void __set_name(const std::string& val);

  void __set_children(const std::vector<TIcebergSchemaField> & val);

  bool operator == (const TIcebergSchemaField & rhs) const;
  bool operator != (const TIcebergSchemaField &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TIcebergSchemaField & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TIcebergSchemaField &a, TIcebergSchemaField &b);

std::ostream& operator<<(std::ostream& out, const TIcebergSchemaField& obj);

typedef struct _TPartitionMap__isset {
  _TPartitionMap__isset() : partitions(false) {}
  bool partitions :1;
} _TPartitionMap__isset;

class TPartitionMap : public virtual ::apache::thrift::TBase {
 public:

  TPartitionMap(const TPartitionMap&);
  TPartitionMap& operator=(const TPartitionMap&);
  TPartitionMap() noexcept;

  virtual ~TPartitionMap() noexcept;
  std::map<int64_t, THdfsPartition>  partitions;

  _TPartitionMap__isset __isset;

  void __set_partitions(const std::map<int64_t, THdfsPartition> & val);

  bool operator == (const TPartitionMap & rhs) const;
  bool operator != (const TPartitionMap &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TPartitionMap & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TPartitionMap &a, TPartitionMap &b);

std::ostream& operator<<(std::ostream& out, const TPartitionMap& obj);

typedef struct _TCompressedPartitionMap__isset {
  _TCompressedPartitionMap__isset() : original_len(false), compressed_len(false), compressed_serialized_partitions(false) {}
  bool original_len :1;
  bool compressed_len :1;
  bool compressed_serialized_partitions :1;
} _TCompressedPartitionMap__isset;

class TCompressedPartitionMap : public virtual ::apache::thrift::TBase {
 public:

  TCompressedPartitionMap(const TCompressedPartitionMap&);
  TCompressedPartitionMap& operator=(const TCompressedPartitionMap&);
  TCompressedPartitionMap() noexcept;

  virtual ~TCompressedPartitionMap() noexcept;
  int32_t original_len;
  int32_t compressed_len;
  std::string compressed_serialized_partitions;

  _TCompressedPartitionMap__isset __isset;

  void __set_original_len(const int32_t val);

  void __set_compressed_len(const int32_t val);

  void __set_compressed_serialized_partitions(const std::string& val);

  bool operator == (const TCompressedPartitionMap & rhs) const;
  bool operator != (const TCompressedPartitionMap &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TCompressedPartitionMap & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TCompressedPartitionMap &a, TCompressedPartitionMap &b);

std::ostream& operator<<(std::ostream& out, const TCompressedPartitionMap& obj);

typedef struct _TIcebergTable__isset {
  _TIcebergTable__isset() : location(false), columns(false), iceberg_schema(false), partition_column_names(false), compressed_partitions(false), partitions(false), iceberg_equal_delete_schema(false) {}
  bool location :1;
  bool columns :1;
  bool iceberg_schema :1;
  bool partition_column_names :1;
  bool compressed_partitions :1;
  bool partitions :1;
  bool iceberg_equal_delete_schema :1;
} _TIcebergTable__isset;

class TIcebergTable : public virtual ::apache::thrift::TBase {
 public:

  TIcebergTable(const TIcebergTable&);
  TIcebergTable& operator=(const TIcebergTable&);
  TIcebergTable() noexcept;

  virtual ~TIcebergTable() noexcept;
  std::string location;
  std::vector<TColumn>  columns;
  TIcebergSchema iceberg_schema;
  std::vector<std::string>  partition_column_names;
  TCompressedPartitionMap compressed_partitions;
  std::map<int64_t, THdfsPartition>  partitions;
  TIcebergSchema iceberg_equal_delete_schema;

  _TIcebergTable__isset __isset;

  void __set_location(const std::string& val);

  void __set_columns(const std::vector<TColumn> & val);

  void __set_iceberg_schema(const TIcebergSchema& val);

  void __set_partition_column_names(const std::vector<std::string> & val);

  void __set_compressed_partitions(const TCompressedPartitionMap& val);

  void __set_partitions(const std::map<int64_t, THdfsPartition> & val);

  void __set_iceberg_equal_delete_schema(const TIcebergSchema& val);

  bool operator == (const TIcebergTable & rhs) const;
  bool operator != (const TIcebergTable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TIcebergTable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TIcebergTable &a, TIcebergTable &b);

std::ostream& operator<<(std::ostream& out, const TIcebergTable& obj);

typedef struct _THudiTable__isset {
  _THudiTable__isset() : location(false), columns(false), partition_columns(false), partitions(false), partition_prefixes(false), instant_time(false), hive_column_names(false), hive_column_types(false), input_format(false), serde_lib(false), time_zone(false) {}
  bool location :1;
  bool columns :1;
  bool partition_columns :1;
  bool partitions :1;
  bool partition_prefixes :1;
  bool instant_time :1;
  bool hive_column_names :1;
  bool hive_column_types :1;
  bool input_format :1;
  bool serde_lib :1;
  bool time_zone :1;
} _THudiTable__isset;

class THudiTable : public virtual ::apache::thrift::TBase {
 public:

  THudiTable(const THudiTable&);
  THudiTable& operator=(const THudiTable&);
  THudiTable() noexcept;

  virtual ~THudiTable() noexcept;
  std::string location;
  std::vector<TColumn>  columns;
  std::vector<TColumn>  partition_columns;
  std::map<int64_t, THdfsPartition>  partitions;
  std::vector<std::string>  partition_prefixes;
  std::string instant_time;
  std::string hive_column_names;
  std::string hive_column_types;
  std::string input_format;
  std::string serde_lib;
  std::string time_zone;

  _THudiTable__isset __isset;

  void __set_location(const std::string& val);

  void __set_columns(const std::vector<TColumn> & val);

  void __set_partition_columns(const std::vector<TColumn> & val);

  void __set_partitions(const std::map<int64_t, THdfsPartition> & val);

  void __set_partition_prefixes(const std::vector<std::string> & val);

  void __set_instant_time(const std::string& val);

  void __set_hive_column_names(const std::string& val);

  void __set_hive_column_types(const std::string& val);

  void __set_input_format(const std::string& val);

  void __set_serde_lib(const std::string& val);

  void __set_time_zone(const std::string& val);

  bool operator == (const THudiTable & rhs) const;
  bool operator != (const THudiTable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const THudiTable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(THudiTable &a, THudiTable &b);

std::ostream& operator<<(std::ostream& out, const THudiTable& obj);

typedef struct _TPaimonTable__isset {
  _TPaimonTable__isset() : paimon_options(false), paimon_native_table(false), time_zone(false) {}
  bool paimon_options :1;
  bool paimon_native_table :1;
  bool time_zone :1;
} _TPaimonTable__isset;

class TPaimonTable : public virtual ::apache::thrift::TBase {
 public:

  TPaimonTable(const TPaimonTable&);
  TPaimonTable& operator=(const TPaimonTable&);
  TPaimonTable() noexcept;

  virtual ~TPaimonTable() noexcept;
  std::string paimon_options;
  std::string paimon_native_table;
  std::string time_zone;

  _TPaimonTable__isset __isset;

  void __set_paimon_options(const std::string& val);

  void __set_paimon_native_table(const std::string& val);

  void __set_time_zone(const std::string& val);

  bool operator == (const TPaimonTable & rhs) const;
  bool operator != (const TPaimonTable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TPaimonTable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TPaimonTable &a, TPaimonTable &b);

std::ostream& operator<<(std::ostream& out, const TPaimonTable& obj);

typedef struct _TDeltaLakeTable__isset {
  _TDeltaLakeTable__isset() : location(false), columns(false), partition_columns(false), partitions(false), partition_prefixes(false) {}
  bool location :1;
  bool columns :1;
  bool partition_columns :1;
  bool partitions :1;
  bool partition_prefixes :1;
} _TDeltaLakeTable__isset;

class TDeltaLakeTable : public virtual ::apache::thrift::TBase {
 public:

  TDeltaLakeTable(const TDeltaLakeTable&);
  TDeltaLakeTable& operator=(const TDeltaLakeTable&);
  TDeltaLakeTable() noexcept;

  virtual ~TDeltaLakeTable() noexcept;
  std::string location;
  std::vector<TColumn>  columns;
  std::vector<TColumn>  partition_columns;
  std::map<int64_t, THdfsPartition>  partitions;
  std::vector<std::string>  partition_prefixes;

  _TDeltaLakeTable__isset __isset;

  void __set_location(const std::string& val);

  void __set_columns(const std::vector<TColumn> & val);

  void __set_partition_columns(const std::vector<TColumn> & val);

  void __set_partitions(const std::map<int64_t, THdfsPartition> & val);

  void __set_partition_prefixes(const std::vector<std::string> & val);

  bool operator == (const TDeltaLakeTable & rhs) const;
  bool operator != (const TDeltaLakeTable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDeltaLakeTable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TDeltaLakeTable &a, TDeltaLakeTable &b);

std::ostream& operator<<(std::ostream& out, const TDeltaLakeTable& obj);

typedef struct _TJDBCTable__isset {
  _TJDBCTable__isset() : jdbc_driver_name(false), jdbc_driver_url(false), jdbc_driver_checksum(false), jdbc_driver_class(false), jdbc_url(false), jdbc_table(false), jdbc_user(false), jdbc_passwd(false) {}
  bool jdbc_driver_name :1;
  bool jdbc_driver_url :1;
  bool jdbc_driver_checksum :1;
  bool jdbc_driver_class :1;
  bool jdbc_url :1;
  bool jdbc_table :1;
  bool jdbc_user :1;
  bool jdbc_passwd :1;
} _TJDBCTable__isset;

class TJDBCTable : public virtual ::apache::thrift::TBase {
 public:

  TJDBCTable(const TJDBCTable&);
  TJDBCTable& operator=(const TJDBCTable&);
  TJDBCTable() noexcept;

  virtual ~TJDBCTable() noexcept;
  std::string jdbc_driver_name;
  std::string jdbc_driver_url;
  std::string jdbc_driver_checksum;
  std::string jdbc_driver_class;
  std::string jdbc_url;
  std::string jdbc_table;
  std::string jdbc_user;
  std::string jdbc_passwd;

  _TJDBCTable__isset __isset;

  void __set_jdbc_driver_name(const std::string& val);

  void __set_jdbc_driver_url(const std::string& val);

  void __set_jdbc_driver_checksum(const std::string& val);

  void __set_jdbc_driver_class(const std::string& val);

  void __set_jdbc_url(const std::string& val);

  void __set_jdbc_table(const std::string& val);

  void __set_jdbc_user(const std::string& val);

  void __set_jdbc_passwd(const std::string& val);

  bool operator == (const TJDBCTable & rhs) const;
  bool operator != (const TJDBCTable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TJDBCTable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TJDBCTable &a, TJDBCTable &b);

std::ostream& operator<<(std::ostream& out, const TJDBCTable& obj);

typedef struct _TTableDescriptor__isset {
  _TTableDescriptor__isset() : mysqlTable(false), olapTable(false), schemaTable(false), BrokerTable(false), esTable(false), jdbcTable(false), hdfsTable(false), icebergTable(false), hudiTable(false), deltaLakeTable(false), fileTable(false), tableFunctionTable(false), paimonTable(false) {}
  bool mysqlTable :1;
  bool olapTable :1;
  bool schemaTable :1;
  bool BrokerTable :1;
  bool esTable :1;
  bool jdbcTable :1;
  bool hdfsTable :1;
  bool icebergTable :1;
  bool hudiTable :1;
  bool deltaLakeTable :1;
  bool fileTable :1;
  bool tableFunctionTable :1;
  bool paimonTable :1;
} _TTableDescriptor__isset;

class TTableDescriptor : public virtual ::apache::thrift::TBase {
 public:

  TTableDescriptor(const TTableDescriptor&);
  TTableDescriptor& operator=(const TTableDescriptor&);
  TTableDescriptor() noexcept;

  virtual ~TTableDescriptor() noexcept;
   ::starrocks::TTableId id;
  /**
   * 
   * @see com.starrocks.thrift.TTableType
   */
   ::starrocks::TTableType::type tableType;
  int32_t numCols;
  int32_t numClusteringCols;
  std::string tableName;
  std::string dbName;
  TMySQLTable mysqlTable;
  TOlapTable olapTable;
  TSchemaTable schemaTable;
  TBrokerTable BrokerTable;
  TEsTable esTable;
  TJDBCTable jdbcTable;
  THdfsTable hdfsTable;
  TIcebergTable icebergTable;
  THudiTable hudiTable;
  TDeltaLakeTable deltaLakeTable;
  TFileTable fileTable;
  TTableFunctionTable tableFunctionTable;
  TPaimonTable paimonTable;

  _TTableDescriptor__isset __isset;

  void __set_id(const  ::starrocks::TTableId val);

  void __set_tableType(const  ::starrocks::TTableType::type val);

  void __set_numCols(const int32_t val);

  void __set_numClusteringCols(const int32_t val);

  void __set_tableName(const std::string& val);

  void __set_dbName(const std::string& val);

  void __set_mysqlTable(const TMySQLTable& val);

  void __set_olapTable(const TOlapTable& val);

  void __set_schemaTable(const TSchemaTable& val);

  void __set_BrokerTable(const TBrokerTable& val);

  void __set_esTable(const TEsTable& val);

  void __set_jdbcTable(const TJDBCTable& val);

  void __set_hdfsTable(const THdfsTable& val);

  void __set_icebergTable(const TIcebergTable& val);

  void __set_hudiTable(const THudiTable& val);

  void __set_deltaLakeTable(const TDeltaLakeTable& val);

  void __set_fileTable(const TFileTable& val);

  void __set_tableFunctionTable(const TTableFunctionTable& val);

  void __set_paimonTable(const TPaimonTable& val);

  bool operator == (const TTableDescriptor & rhs) const;
  bool operator != (const TTableDescriptor &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TTableDescriptor & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TTableDescriptor &a, TTableDescriptor &b);

std::ostream& operator<<(std::ostream& out, const TTableDescriptor& obj);

typedef struct _TDescriptorTable__isset {
  _TDescriptorTable__isset() : slotDescriptors(false), tableDescriptors(false), is_cached(false) {}
  bool slotDescriptors :1;
  bool tableDescriptors :1;
  bool is_cached :1;
} _TDescriptorTable__isset;

class TDescriptorTable : public virtual ::apache::thrift::TBase {
 public:

  TDescriptorTable(const TDescriptorTable&);
  TDescriptorTable& operator=(const TDescriptorTable&);
  TDescriptorTable() noexcept;

  virtual ~TDescriptorTable() noexcept;
  std::vector<TSlotDescriptor>  slotDescriptors;
  std::vector<TTupleDescriptor>  tupleDescriptors;
  std::vector<TTableDescriptor>  tableDescriptors;
  bool is_cached;

  _TDescriptorTable__isset __isset;

  void __set_slotDescriptors(const std::vector<TSlotDescriptor> & val);

  void __set_tupleDescriptors(const std::vector<TTupleDescriptor> & val);

  void __set_tableDescriptors(const std::vector<TTableDescriptor> & val);

  void __set_is_cached(const bool val);

  bool operator == (const TDescriptorTable & rhs) const;
  bool operator != (const TDescriptorTable &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDescriptorTable & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TDescriptorTable &a, TDescriptorTable &b);

std::ostream& operator<<(std::ostream& out, const TDescriptorTable& obj);

typedef struct _TOlapTableRouteInfo__isset {
  _TOlapTableRouteInfo__isset() : schema(false), partition(false), location(false), num_replicas(false), db_name(false), table_name(false), nodes_info(false), keys_type(false) {}
  bool schema :1;
  bool partition :1;
  bool location :1;
  bool num_replicas :1;
  bool db_name :1;
  bool table_name :1;
  bool nodes_info :1;
  bool keys_type :1;
} _TOlapTableRouteInfo__isset;

class TOlapTableRouteInfo : public virtual ::apache::thrift::TBase {
 public:

  TOlapTableRouteInfo(const TOlapTableRouteInfo&);
  TOlapTableRouteInfo& operator=(const TOlapTableRouteInfo&);
  TOlapTableRouteInfo() noexcept;

  virtual ~TOlapTableRouteInfo() noexcept;
  TOlapTableSchemaParam schema;
  TOlapTablePartitionParam partition;
  TOlapTableLocationParam location;
  int32_t num_replicas;
  std::string db_name;
  std::string table_name;
  TNodesInfo nodes_info;
  /**
   * 
   * @see com.starrocks.thrift.TKeysType
   */
   ::starrocks::TKeysType::type keys_type;

  _TOlapTableRouteInfo__isset __isset;

  void __set_schema(const TOlapTableSchemaParam& val);

  void __set_partition(const TOlapTablePartitionParam& val);

  void __set_location(const TOlapTableLocationParam& val);

  void __set_num_replicas(const int32_t val);

  void __set_db_name(const std::string& val);

  void __set_table_name(const std::string& val);

  void __set_nodes_info(const TNodesInfo& val);

  void __set_keys_type(const  ::starrocks::TKeysType::type val);

  bool operator == (const TOlapTableRouteInfo & rhs) const;
  bool operator != (const TOlapTableRouteInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TOlapTableRouteInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TOlapTableRouteInfo &a, TOlapTableRouteInfo &b);

std::ostream& operator<<(std::ostream& out, const TOlapTableRouteInfo& obj);

typedef struct _TIMTDescriptor__isset {
  _TIMTDescriptor__isset() : imt_type(false), olap_table(false), need_maintain(false), load_id(false), txn_id(false) {}
  bool imt_type :1;
  bool olap_table :1;
  bool need_maintain :1;
  bool load_id :1;
  bool txn_id :1;
} _TIMTDescriptor__isset;

class TIMTDescriptor : public virtual ::apache::thrift::TBase {
 public:

  TIMTDescriptor(const TIMTDescriptor&);
  TIMTDescriptor& operator=(const TIMTDescriptor&);
  TIMTDescriptor() noexcept;

  virtual ~TIMTDescriptor() noexcept;
  /**
   * 
   * @see TIMTType
   */
  TIMTType::type imt_type;
  TOlapTableRouteInfo olap_table;
  bool need_maintain;
   ::starrocks::TUniqueId load_id;
  int64_t txn_id;

  _TIMTDescriptor__isset __isset;

  void __set_imt_type(const TIMTType::type val);

  void __set_olap_table(const TOlapTableRouteInfo& val);

  void __set_need_maintain(const bool val);

  void __set_load_id(const  ::starrocks::TUniqueId& val);

  void __set_txn_id(const int64_t val);

  bool operator == (const TIMTDescriptor & rhs) const;
  bool operator != (const TIMTDescriptor &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TIMTDescriptor & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TIMTDescriptor &a, TIMTDescriptor &b);

std::ostream& operator<<(std::ostream& out, const TIMTDescriptor& obj);

} // namespace

#endif
