/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef FileBrokerService_TYPES_H
#define FileBrokerService_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace starrocks {

struct TBrokerOperationStatusCode {
  enum type {
    OK = 0,
    END_OF_FILE = 301,
    NOT_AUTHORIZED = 401,
    DUPLICATE_REQUEST = 402,
    INVALID_INPUT_OFFSET = 403,
    INVALID_INPUT_FILE_PATH = 404,
    INVALID_ARGUMENT = 405,
    FILE_NOT_FOUND = 501,
    TARGET_STORAGE_SERVICE_ERROR = 502,
    OPERATION_NOT_SUPPORTED = 503
  };
};

extern const std::map<int, const char*> _TBrokerOperationStatusCode_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TBrokerOperationStatusCode::type& val);

std::string to_string(const TBrokerOperationStatusCode::type& val);

struct TBrokerVersion {
  enum type {
    VERSION_ONE = 1
  };
};

extern const std::map<int, const char*> _TBrokerVersion_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TBrokerVersion::type& val);

std::string to_string(const TBrokerVersion::type& val);

struct TBrokerOpenMode {
  enum type {
    APPEND = 1
  };
};

extern const std::map<int, const char*> _TBrokerOpenMode_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TBrokerOpenMode::type& val);

std::string to_string(const TBrokerOpenMode::type& val);

class TBrokerOperationStatus;

class TBrokerFileStatus;

class TBrokerFD;

class TBrokerListResponse;

class TBrokerOpenReaderResponse;

class TBrokerReadResponse;

class TBrokerOpenWriterResponse;

class TBrokerCheckPathExistResponse;

class TBrokerListPathRequest;

class TBrokerDeletePathRequest;

class TBrokerRenamePathRequest;

class TBrokerCheckPathExistRequest;

class TBrokerOpenReaderRequest;

class TBrokerPReadRequest;

class TBrokerSeekRequest;

class TBrokerCloseReaderRequest;

class TBrokerOpenWriterRequest;

class TBrokerPWriteRequest;

class TBrokerCloseWriterRequest;

class TBrokerPingBrokerRequest;

typedef struct _TBrokerOperationStatus__isset {
  _TBrokerOperationStatus__isset() : message(false) {}
  bool message :1;
} _TBrokerOperationStatus__isset;

class TBrokerOperationStatus : public virtual ::apache::thrift::TBase {
 public:

  TBrokerOperationStatus(const TBrokerOperationStatus&);
  TBrokerOperationStatus& operator=(const TBrokerOperationStatus&);
  TBrokerOperationStatus() noexcept;

  virtual ~TBrokerOperationStatus() noexcept;
  /**
   * 
   * @see TBrokerOperationStatusCode
   */
  TBrokerOperationStatusCode::type statusCode;
  std::string message;

  _TBrokerOperationStatus__isset __isset;

  void __set_statusCode(const TBrokerOperationStatusCode::type val);

  void __set_message(const std::string& val);

  bool operator == (const TBrokerOperationStatus & rhs) const;
  bool operator != (const TBrokerOperationStatus &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerOperationStatus & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerOperationStatus &a, TBrokerOperationStatus &b);

std::ostream& operator<<(std::ostream& out, const TBrokerOperationStatus& obj);


class TBrokerFileStatus : public virtual ::apache::thrift::TBase {
 public:

  TBrokerFileStatus(const TBrokerFileStatus&);
  TBrokerFileStatus& operator=(const TBrokerFileStatus&);
  TBrokerFileStatus() noexcept;

  virtual ~TBrokerFileStatus() noexcept;
  std::string path;
  bool isDir;
  int64_t size;
  bool isSplitable;

  void __set_path(const std::string& val);

  void __set_isDir(const bool val);

  void __set_size(const int64_t val);

  void __set_isSplitable(const bool val);

  bool operator == (const TBrokerFileStatus & rhs) const;
  bool operator != (const TBrokerFileStatus &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerFileStatus & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerFileStatus &a, TBrokerFileStatus &b);

std::ostream& operator<<(std::ostream& out, const TBrokerFileStatus& obj);


class TBrokerFD : public virtual ::apache::thrift::TBase {
 public:

  TBrokerFD(const TBrokerFD&) noexcept;
  TBrokerFD& operator=(const TBrokerFD&) noexcept;
  TBrokerFD() noexcept;

  virtual ~TBrokerFD() noexcept;
  int64_t high;
  int64_t low;

  void __set_high(const int64_t val);

  void __set_low(const int64_t val);

  bool operator == (const TBrokerFD & rhs) const;
  bool operator != (const TBrokerFD &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerFD & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerFD &a, TBrokerFD &b);

std::ostream& operator<<(std::ostream& out, const TBrokerFD& obj);

typedef struct _TBrokerListResponse__isset {
  _TBrokerListResponse__isset() : files(false) {}
  bool files :1;
} _TBrokerListResponse__isset;

class TBrokerListResponse : public virtual ::apache::thrift::TBase {
 public:

  TBrokerListResponse(const TBrokerListResponse&);
  TBrokerListResponse& operator=(const TBrokerListResponse&);
  TBrokerListResponse() noexcept;

  virtual ~TBrokerListResponse() noexcept;
  TBrokerOperationStatus opStatus;
  std::vector<TBrokerFileStatus>  files;

  _TBrokerListResponse__isset __isset;

  void __set_opStatus(const TBrokerOperationStatus& val);

  void __set_files(const std::vector<TBrokerFileStatus> & val);

  bool operator == (const TBrokerListResponse & rhs) const;
  bool operator != (const TBrokerListResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerListResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerListResponse &a, TBrokerListResponse &b);

std::ostream& operator<<(std::ostream& out, const TBrokerListResponse& obj);

typedef struct _TBrokerOpenReaderResponse__isset {
  _TBrokerOpenReaderResponse__isset() : fd(false), size(false) {}
  bool fd :1;
  bool size :1;
} _TBrokerOpenReaderResponse__isset;

class TBrokerOpenReaderResponse : public virtual ::apache::thrift::TBase {
 public:

  TBrokerOpenReaderResponse(const TBrokerOpenReaderResponse&);
  TBrokerOpenReaderResponse& operator=(const TBrokerOpenReaderResponse&);
  TBrokerOpenReaderResponse() noexcept;

  virtual ~TBrokerOpenReaderResponse() noexcept;
  TBrokerOperationStatus opStatus;
  TBrokerFD fd;
  int64_t size;

  _TBrokerOpenReaderResponse__isset __isset;

  void __set_opStatus(const TBrokerOperationStatus& val);

  void __set_fd(const TBrokerFD& val);

  void __set_size(const int64_t val);

  bool operator == (const TBrokerOpenReaderResponse & rhs) const;
  bool operator != (const TBrokerOpenReaderResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerOpenReaderResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerOpenReaderResponse &a, TBrokerOpenReaderResponse &b);

std::ostream& operator<<(std::ostream& out, const TBrokerOpenReaderResponse& obj);

typedef struct _TBrokerReadResponse__isset {
  _TBrokerReadResponse__isset() : data(false) {}
  bool data :1;
} _TBrokerReadResponse__isset;

class TBrokerReadResponse : public virtual ::apache::thrift::TBase {
 public:

  TBrokerReadResponse(const TBrokerReadResponse&);
  TBrokerReadResponse& operator=(const TBrokerReadResponse&);
  TBrokerReadResponse() noexcept;

  virtual ~TBrokerReadResponse() noexcept;
  TBrokerOperationStatus opStatus;
  std::string data;

  _TBrokerReadResponse__isset __isset;

  void __set_opStatus(const TBrokerOperationStatus& val);

  void __set_data(const std::string& val);

  bool operator == (const TBrokerReadResponse & rhs) const;
  bool operator != (const TBrokerReadResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerReadResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerReadResponse &a, TBrokerReadResponse &b);

std::ostream& operator<<(std::ostream& out, const TBrokerReadResponse& obj);

typedef struct _TBrokerOpenWriterResponse__isset {
  _TBrokerOpenWriterResponse__isset() : fd(false) {}
  bool fd :1;
} _TBrokerOpenWriterResponse__isset;

class TBrokerOpenWriterResponse : public virtual ::apache::thrift::TBase {
 public:

  TBrokerOpenWriterResponse(const TBrokerOpenWriterResponse&);
  TBrokerOpenWriterResponse& operator=(const TBrokerOpenWriterResponse&);
  TBrokerOpenWriterResponse() noexcept;

  virtual ~TBrokerOpenWriterResponse() noexcept;
  TBrokerOperationStatus opStatus;
  TBrokerFD fd;

  _TBrokerOpenWriterResponse__isset __isset;

  void __set_opStatus(const TBrokerOperationStatus& val);

  void __set_fd(const TBrokerFD& val);

  bool operator == (const TBrokerOpenWriterResponse & rhs) const;
  bool operator != (const TBrokerOpenWriterResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerOpenWriterResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerOpenWriterResponse &a, TBrokerOpenWriterResponse &b);

std::ostream& operator<<(std::ostream& out, const TBrokerOpenWriterResponse& obj);


class TBrokerCheckPathExistResponse : public virtual ::apache::thrift::TBase {
 public:

  TBrokerCheckPathExistResponse(const TBrokerCheckPathExistResponse&);
  TBrokerCheckPathExistResponse& operator=(const TBrokerCheckPathExistResponse&);
  TBrokerCheckPathExistResponse() noexcept;

  virtual ~TBrokerCheckPathExistResponse() noexcept;
  TBrokerOperationStatus opStatus;
  bool isPathExist;

  void __set_opStatus(const TBrokerOperationStatus& val);

  void __set_isPathExist(const bool val);

  bool operator == (const TBrokerCheckPathExistResponse & rhs) const;
  bool operator != (const TBrokerCheckPathExistResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerCheckPathExistResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerCheckPathExistResponse &a, TBrokerCheckPathExistResponse &b);

std::ostream& operator<<(std::ostream& out, const TBrokerCheckPathExistResponse& obj);

typedef struct _TBrokerListPathRequest__isset {
  _TBrokerListPathRequest__isset() : fileNameOnly(false) {}
  bool fileNameOnly :1;
} _TBrokerListPathRequest__isset;

class TBrokerListPathRequest : public virtual ::apache::thrift::TBase {
 public:

  TBrokerListPathRequest(const TBrokerListPathRequest&);
  TBrokerListPathRequest& operator=(const TBrokerListPathRequest&);
  TBrokerListPathRequest() noexcept;

  virtual ~TBrokerListPathRequest() noexcept;
  /**
   * 
   * @see TBrokerVersion
   */
  TBrokerVersion::type version;
  std::string path;
  bool isRecursive;
  std::map<std::string, std::string>  properties;
  bool fileNameOnly;

  _TBrokerListPathRequest__isset __isset;

  void __set_version(const TBrokerVersion::type val);

  void __set_path(const std::string& val);

  void __set_isRecursive(const bool val);

  void __set_properties(const std::map<std::string, std::string> & val);

  void __set_fileNameOnly(const bool val);

  bool operator == (const TBrokerListPathRequest & rhs) const;
  bool operator != (const TBrokerListPathRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerListPathRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerListPathRequest &a, TBrokerListPathRequest &b);

std::ostream& operator<<(std::ostream& out, const TBrokerListPathRequest& obj);


class TBrokerDeletePathRequest : public virtual ::apache::thrift::TBase {
 public:

  TBrokerDeletePathRequest(const TBrokerDeletePathRequest&);
  TBrokerDeletePathRequest& operator=(const TBrokerDeletePathRequest&);
  TBrokerDeletePathRequest() noexcept;

  virtual ~TBrokerDeletePathRequest() noexcept;
  /**
   * 
   * @see TBrokerVersion
   */
  TBrokerVersion::type version;
  std::string path;
  std::map<std::string, std::string>  properties;

  void __set_version(const TBrokerVersion::type val);

  void __set_path(const std::string& val);

  void __set_properties(const std::map<std::string, std::string> & val);

  bool operator == (const TBrokerDeletePathRequest & rhs) const;
  bool operator != (const TBrokerDeletePathRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerDeletePathRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerDeletePathRequest &a, TBrokerDeletePathRequest &b);

std::ostream& operator<<(std::ostream& out, const TBrokerDeletePathRequest& obj);


class TBrokerRenamePathRequest : public virtual ::apache::thrift::TBase {
 public:

  TBrokerRenamePathRequest(const TBrokerRenamePathRequest&);
  TBrokerRenamePathRequest& operator=(const TBrokerRenamePathRequest&);
  TBrokerRenamePathRequest() noexcept;

  virtual ~TBrokerRenamePathRequest() noexcept;
  /**
   * 
   * @see TBrokerVersion
   */
  TBrokerVersion::type version;
  std::string srcPath;
  std::string destPath;
  std::map<std::string, std::string>  properties;

  void __set_version(const TBrokerVersion::type val);

  void __set_srcPath(const std::string& val);

  void __set_destPath(const std::string& val);

  void __set_properties(const std::map<std::string, std::string> & val);

  bool operator == (const TBrokerRenamePathRequest & rhs) const;
  bool operator != (const TBrokerRenamePathRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerRenamePathRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerRenamePathRequest &a, TBrokerRenamePathRequest &b);

std::ostream& operator<<(std::ostream& out, const TBrokerRenamePathRequest& obj);


class TBrokerCheckPathExistRequest : public virtual ::apache::thrift::TBase {
 public:

  TBrokerCheckPathExistRequest(const TBrokerCheckPathExistRequest&);
  TBrokerCheckPathExistRequest& operator=(const TBrokerCheckPathExistRequest&);
  TBrokerCheckPathExistRequest() noexcept;

  virtual ~TBrokerCheckPathExistRequest() noexcept;
  /**
   * 
   * @see TBrokerVersion
   */
  TBrokerVersion::type version;
  std::string path;
  std::map<std::string, std::string>  properties;

  void __set_version(const TBrokerVersion::type val);

  void __set_path(const std::string& val);

  void __set_properties(const std::map<std::string, std::string> & val);

  bool operator == (const TBrokerCheckPathExistRequest & rhs) const;
  bool operator != (const TBrokerCheckPathExistRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerCheckPathExistRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerCheckPathExistRequest &a, TBrokerCheckPathExistRequest &b);

std::ostream& operator<<(std::ostream& out, const TBrokerCheckPathExistRequest& obj);


class TBrokerOpenReaderRequest : public virtual ::apache::thrift::TBase {
 public:

  TBrokerOpenReaderRequest(const TBrokerOpenReaderRequest&);
  TBrokerOpenReaderRequest& operator=(const TBrokerOpenReaderRequest&);
  TBrokerOpenReaderRequest() noexcept;

  virtual ~TBrokerOpenReaderRequest() noexcept;
  /**
   * 
   * @see TBrokerVersion
   */
  TBrokerVersion::type version;
  std::string path;
  int64_t startOffset;
  std::string clientId;
  std::map<std::string, std::string>  properties;

  void __set_version(const TBrokerVersion::type val);

  void __set_path(const std::string& val);

  void __set_startOffset(const int64_t val);

  void __set_clientId(const std::string& val);

  void __set_properties(const std::map<std::string, std::string> & val);

  bool operator == (const TBrokerOpenReaderRequest & rhs) const;
  bool operator != (const TBrokerOpenReaderRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerOpenReaderRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerOpenReaderRequest &a, TBrokerOpenReaderRequest &b);

std::ostream& operator<<(std::ostream& out, const TBrokerOpenReaderRequest& obj);


class TBrokerPReadRequest : public virtual ::apache::thrift::TBase {
 public:

  TBrokerPReadRequest(const TBrokerPReadRequest&) noexcept;
  TBrokerPReadRequest& operator=(const TBrokerPReadRequest&) noexcept;
  TBrokerPReadRequest() noexcept;

  virtual ~TBrokerPReadRequest() noexcept;
  /**
   * 
   * @see TBrokerVersion
   */
  TBrokerVersion::type version;
  TBrokerFD fd;
  int64_t offset;
  int64_t length;

  void __set_version(const TBrokerVersion::type val);

  void __set_fd(const TBrokerFD& val);

  void __set_offset(const int64_t val);

  void __set_length(const int64_t val);

  bool operator == (const TBrokerPReadRequest & rhs) const;
  bool operator != (const TBrokerPReadRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerPReadRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerPReadRequest &a, TBrokerPReadRequest &b);

std::ostream& operator<<(std::ostream& out, const TBrokerPReadRequest& obj);


class TBrokerSeekRequest : public virtual ::apache::thrift::TBase {
 public:

  TBrokerSeekRequest(const TBrokerSeekRequest&) noexcept;
  TBrokerSeekRequest& operator=(const TBrokerSeekRequest&) noexcept;
  TBrokerSeekRequest() noexcept;

  virtual ~TBrokerSeekRequest() noexcept;
  /**
   * 
   * @see TBrokerVersion
   */
  TBrokerVersion::type version;
  TBrokerFD fd;
  int64_t offset;

  void __set_version(const TBrokerVersion::type val);

  void __set_fd(const TBrokerFD& val);

  void __set_offset(const int64_t val);

  bool operator == (const TBrokerSeekRequest & rhs) const;
  bool operator != (const TBrokerSeekRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerSeekRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerSeekRequest &a, TBrokerSeekRequest &b);

std::ostream& operator<<(std::ostream& out, const TBrokerSeekRequest& obj);


class TBrokerCloseReaderRequest : public virtual ::apache::thrift::TBase {
 public:

  TBrokerCloseReaderRequest(const TBrokerCloseReaderRequest&) noexcept;
  TBrokerCloseReaderRequest& operator=(const TBrokerCloseReaderRequest&) noexcept;
  TBrokerCloseReaderRequest() noexcept;

  virtual ~TBrokerCloseReaderRequest() noexcept;
  /**
   * 
   * @see TBrokerVersion
   */
  TBrokerVersion::type version;
  TBrokerFD fd;

  void __set_version(const TBrokerVersion::type val);

  void __set_fd(const TBrokerFD& val);

  bool operator == (const TBrokerCloseReaderRequest & rhs) const;
  bool operator != (const TBrokerCloseReaderRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerCloseReaderRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerCloseReaderRequest &a, TBrokerCloseReaderRequest &b);

std::ostream& operator<<(std::ostream& out, const TBrokerCloseReaderRequest& obj);


class TBrokerOpenWriterRequest : public virtual ::apache::thrift::TBase {
 public:

  TBrokerOpenWriterRequest(const TBrokerOpenWriterRequest&);
  TBrokerOpenWriterRequest& operator=(const TBrokerOpenWriterRequest&);
  TBrokerOpenWriterRequest() noexcept;

  virtual ~TBrokerOpenWriterRequest() noexcept;
  /**
   * 
   * @see TBrokerVersion
   */
  TBrokerVersion::type version;
  std::string path;
  /**
   * 
   * @see TBrokerOpenMode
   */
  TBrokerOpenMode::type openMode;
  std::string clientId;
  std::map<std::string, std::string>  properties;

  void __set_version(const TBrokerVersion::type val);

  void __set_path(const std::string& val);

  void __set_openMode(const TBrokerOpenMode::type val);

  void __set_clientId(const std::string& val);

  void __set_properties(const std::map<std::string, std::string> & val);

  bool operator == (const TBrokerOpenWriterRequest & rhs) const;
  bool operator != (const TBrokerOpenWriterRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerOpenWriterRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerOpenWriterRequest &a, TBrokerOpenWriterRequest &b);

std::ostream& operator<<(std::ostream& out, const TBrokerOpenWriterRequest& obj);


class TBrokerPWriteRequest : public virtual ::apache::thrift::TBase {
 public:

  TBrokerPWriteRequest(const TBrokerPWriteRequest&);
  TBrokerPWriteRequest& operator=(const TBrokerPWriteRequest&);
  TBrokerPWriteRequest() noexcept;

  virtual ~TBrokerPWriteRequest() noexcept;
  /**
   * 
   * @see TBrokerVersion
   */
  TBrokerVersion::type version;
  TBrokerFD fd;
  int64_t offset;
  std::string data;

  void __set_version(const TBrokerVersion::type val);

  void __set_fd(const TBrokerFD& val);

  void __set_offset(const int64_t val);

  void __set_data(const std::string& val);

  bool operator == (const TBrokerPWriteRequest & rhs) const;
  bool operator != (const TBrokerPWriteRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerPWriteRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerPWriteRequest &a, TBrokerPWriteRequest &b);

std::ostream& operator<<(std::ostream& out, const TBrokerPWriteRequest& obj);


class TBrokerCloseWriterRequest : public virtual ::apache::thrift::TBase {
 public:

  TBrokerCloseWriterRequest(const TBrokerCloseWriterRequest&) noexcept;
  TBrokerCloseWriterRequest& operator=(const TBrokerCloseWriterRequest&) noexcept;
  TBrokerCloseWriterRequest() noexcept;

  virtual ~TBrokerCloseWriterRequest() noexcept;
  /**
   * 
   * @see TBrokerVersion
   */
  TBrokerVersion::type version;
  TBrokerFD fd;

  void __set_version(const TBrokerVersion::type val);

  void __set_fd(const TBrokerFD& val);

  bool operator == (const TBrokerCloseWriterRequest & rhs) const;
  bool operator != (const TBrokerCloseWriterRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerCloseWriterRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerCloseWriterRequest &a, TBrokerCloseWriterRequest &b);

std::ostream& operator<<(std::ostream& out, const TBrokerCloseWriterRequest& obj);


class TBrokerPingBrokerRequest : public virtual ::apache::thrift::TBase {
 public:

  TBrokerPingBrokerRequest(const TBrokerPingBrokerRequest&);
  TBrokerPingBrokerRequest& operator=(const TBrokerPingBrokerRequest&);
  TBrokerPingBrokerRequest() noexcept;

  virtual ~TBrokerPingBrokerRequest() noexcept;
  /**
   * 
   * @see TBrokerVersion
   */
  TBrokerVersion::type version;
  std::string clientId;

  void __set_version(const TBrokerVersion::type val);

  void __set_clientId(const std::string& val);

  bool operator == (const TBrokerPingBrokerRequest & rhs) const;
  bool operator != (const TBrokerPingBrokerRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBrokerPingBrokerRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBrokerPingBrokerRequest &a, TBrokerPingBrokerRequest &b);

std::ostream& operator<<(std::ostream& out, const TBrokerPingBrokerRequest& obj);

} // namespace

#endif
