/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "HeartbeatService_constants.h"

namespace starrocks {

const HeartbeatServiceConstants g_HeartbeatService_constants;

HeartbeatServiceConstants::HeartbeatServiceConstants() {
  IS_SET_DEFAULT_ROWSET_TO_BETA_BIT = 1LL;

}

} // namespace

