/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "HeartbeatService_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace starrocks {


TMasterInfo::~TMasterInfo() noexcept {
}

TMasterInfo::TMasterInfo() noexcept
   : cluster_id(0),
     epoch(0),
     token(),
     backend_ip(),
     http_port(0),
     heartbeat_flags(0),
     backend_id(0),
     min_active_txn_id(0LL),
     run_mode(static_cast< ::starrocks::TRunMode::type>(0)),
     encrypted(0) {
}

void TMasterInfo::__set_network_address(const  ::starrocks::TNetworkAddress& val) {
  this->network_address = val;
}

void TMasterInfo::__set_cluster_id(const  ::starrocks::TClusterId val) {
  this->cluster_id = val;
__isset.cluster_id = true;
}

void TMasterInfo::__set_epoch(const  ::starrocks::TEpoch val) {
  this->epoch = val;
}

void TMasterInfo::__set_token(const std::string& val) {
  this->token = val;
__isset.token = true;
}

void TMasterInfo::__set_backend_ip(const std::string& val) {
  this->backend_ip = val;
__isset.backend_ip = true;
}

void TMasterInfo::__set_http_port(const  ::starrocks::TPort val) {
  this->http_port = val;
__isset.http_port = true;
}

void TMasterInfo::__set_heartbeat_flags(const int64_t val) {
  this->heartbeat_flags = val;
__isset.heartbeat_flags = true;
}

void TMasterInfo::__set_backend_id(const int64_t val) {
  this->backend_id = val;
__isset.backend_id = true;
}

void TMasterInfo::__set_min_active_txn_id(const int64_t val) {
  this->min_active_txn_id = val;
__isset.min_active_txn_id = true;
}

void TMasterInfo::__set_run_mode(const  ::starrocks::TRunMode::type val) {
  this->run_mode = val;
__isset.run_mode = true;
}

void TMasterInfo::__set_disabled_disks(const std::vector<std::string> & val) {
  this->disabled_disks = val;
__isset.disabled_disks = true;
}

void TMasterInfo::__set_decommissioned_disks(const std::vector<std::string> & val) {
  this->decommissioned_disks = val;
__isset.decommissioned_disks = true;
}

void TMasterInfo::__set_encrypted(const bool val) {
  this->encrypted = val;
__isset.encrypted = true;
}
std::ostream& operator<<(std::ostream& out, const TMasterInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TMasterInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_network_address = false;
  bool isset_epoch = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->network_address.read(iprot);
          isset_network_address = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->cluster_id);
          this->__isset.cluster_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->epoch);
          isset_epoch = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->token);
          this->__isset.token = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->backend_ip);
          this->__isset.backend_ip = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->http_port);
          this->__isset.http_port = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->heartbeat_flags);
          this->__isset.heartbeat_flags = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->backend_id);
          this->__isset.backend_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->min_active_txn_id);
          this->__isset.min_active_txn_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast0;
          xfer += iprot->readI32(ecast0);
          this->run_mode = static_cast< ::starrocks::TRunMode::type>(ecast0);
          this->__isset.run_mode = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 11:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->disabled_disks.clear();
            uint32_t _size1;
            ::apache::thrift::protocol::TType _etype4;
            xfer += iprot->readListBegin(_etype4, _size1);
            this->disabled_disks.resize(_size1);
            uint32_t _i5;
            for (_i5 = 0; _i5 < _size1; ++_i5)
            {
              xfer += iprot->readString(this->disabled_disks[_i5]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.disabled_disks = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 12:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->decommissioned_disks.clear();
            uint32_t _size6;
            ::apache::thrift::protocol::TType _etype9;
            xfer += iprot->readListBegin(_etype9, _size6);
            this->decommissioned_disks.resize(_size6);
            uint32_t _i10;
            for (_i10 = 0; _i10 < _size6; ++_i10)
            {
              xfer += iprot->readString(this->decommissioned_disks[_i10]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.decommissioned_disks = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 13:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->encrypted);
          this->__isset.encrypted = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_network_address)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_epoch)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TMasterInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TMasterInfo");

  xfer += oprot->writeFieldBegin("network_address", ::apache::thrift::protocol::T_STRUCT, 1);
  xfer += this->network_address.write(oprot);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.cluster_id) {
    xfer += oprot->writeFieldBegin("cluster_id", ::apache::thrift::protocol::T_I32, 2);
    xfer += oprot->writeI32(this->cluster_id);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldBegin("epoch", ::apache::thrift::protocol::T_I64, 3);
  xfer += oprot->writeI64(this->epoch);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.token) {
    xfer += oprot->writeFieldBegin("token", ::apache::thrift::protocol::T_STRING, 4);
    xfer += oprot->writeString(this->token);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.backend_ip) {
    xfer += oprot->writeFieldBegin("backend_ip", ::apache::thrift::protocol::T_STRING, 5);
    xfer += oprot->writeString(this->backend_ip);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.http_port) {
    xfer += oprot->writeFieldBegin("http_port", ::apache::thrift::protocol::T_I32, 6);
    xfer += oprot->writeI32(this->http_port);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.heartbeat_flags) {
    xfer += oprot->writeFieldBegin("heartbeat_flags", ::apache::thrift::protocol::T_I64, 7);
    xfer += oprot->writeI64(this->heartbeat_flags);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.backend_id) {
    xfer += oprot->writeFieldBegin("backend_id", ::apache::thrift::protocol::T_I64, 8);
    xfer += oprot->writeI64(this->backend_id);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.min_active_txn_id) {
    xfer += oprot->writeFieldBegin("min_active_txn_id", ::apache::thrift::protocol::T_I64, 9);
    xfer += oprot->writeI64(this->min_active_txn_id);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.run_mode) {
    xfer += oprot->writeFieldBegin("run_mode", ::apache::thrift::protocol::T_I32, 10);
    xfer += oprot->writeI32(static_cast<int32_t>(this->run_mode));
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.disabled_disks) {
    xfer += oprot->writeFieldBegin("disabled_disks", ::apache::thrift::protocol::T_LIST, 11);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->disabled_disks.size()));
      std::vector<std::string> ::const_iterator _iter11;
      for (_iter11 = this->disabled_disks.begin(); _iter11 != this->disabled_disks.end(); ++_iter11)
      {
        xfer += oprot->writeString((*_iter11));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.decommissioned_disks) {
    xfer += oprot->writeFieldBegin("decommissioned_disks", ::apache::thrift::protocol::T_LIST, 12);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->decommissioned_disks.size()));
      std::vector<std::string> ::const_iterator _iter12;
      for (_iter12 = this->decommissioned_disks.begin(); _iter12 != this->decommissioned_disks.end(); ++_iter12)
      {
        xfer += oprot->writeString((*_iter12));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.encrypted) {
    xfer += oprot->writeFieldBegin("encrypted", ::apache::thrift::protocol::T_BOOL, 13);
    xfer += oprot->writeBool(this->encrypted);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TMasterInfo &a, TMasterInfo &b) {
  using ::std::swap;
  swap(a.network_address, b.network_address);
  swap(a.cluster_id, b.cluster_id);
  swap(a.epoch, b.epoch);
  swap(a.token, b.token);
  swap(a.backend_ip, b.backend_ip);
  swap(a.http_port, b.http_port);
  swap(a.heartbeat_flags, b.heartbeat_flags);
  swap(a.backend_id, b.backend_id);
  swap(a.min_active_txn_id, b.min_active_txn_id);
  swap(a.run_mode, b.run_mode);
  swap(a.disabled_disks, b.disabled_disks);
  swap(a.decommissioned_disks, b.decommissioned_disks);
  swap(a.encrypted, b.encrypted);
  swap(a.__isset, b.__isset);
}

bool TMasterInfo::operator==(const TMasterInfo & rhs) const
{
  if (!(network_address == rhs.network_address))
    return false;
  if (__isset.cluster_id != rhs.__isset.cluster_id)
    return false;
  else if (__isset.cluster_id && !(cluster_id == rhs.cluster_id))
    return false;
  if (!(epoch == rhs.epoch))
    return false;
  if (__isset.token != rhs.__isset.token)
    return false;
  else if (__isset.token && !(token == rhs.token))
    return false;
  if (__isset.backend_ip != rhs.__isset.backend_ip)
    return false;
  else if (__isset.backend_ip && !(backend_ip == rhs.backend_ip))
    return false;
  if (__isset.http_port != rhs.__isset.http_port)
    return false;
  else if (__isset.http_port && !(http_port == rhs.http_port))
    return false;
  if (__isset.heartbeat_flags != rhs.__isset.heartbeat_flags)
    return false;
  else if (__isset.heartbeat_flags && !(heartbeat_flags == rhs.heartbeat_flags))
    return false;
  if (__isset.backend_id != rhs.__isset.backend_id)
    return false;
  else if (__isset.backend_id && !(backend_id == rhs.backend_id))
    return false;
  if (__isset.min_active_txn_id != rhs.__isset.min_active_txn_id)
    return false;
  else if (__isset.min_active_txn_id && !(min_active_txn_id == rhs.min_active_txn_id))
    return false;
  if (__isset.run_mode != rhs.__isset.run_mode)
    return false;
  else if (__isset.run_mode && !(run_mode == rhs.run_mode))
    return false;
  if (__isset.disabled_disks != rhs.__isset.disabled_disks)
    return false;
  else if (__isset.disabled_disks && !(disabled_disks == rhs.disabled_disks))
    return false;
  if (__isset.decommissioned_disks != rhs.__isset.decommissioned_disks)
    return false;
  else if (__isset.decommissioned_disks && !(decommissioned_disks == rhs.decommissioned_disks))
    return false;
  if (__isset.encrypted != rhs.__isset.encrypted)
    return false;
  else if (__isset.encrypted && !(encrypted == rhs.encrypted))
    return false;
  return true;
}

TMasterInfo::TMasterInfo(const TMasterInfo& other13) {
  network_address = other13.network_address;
  cluster_id = other13.cluster_id;
  epoch = other13.epoch;
  token = other13.token;
  backend_ip = other13.backend_ip;
  http_port = other13.http_port;
  heartbeat_flags = other13.heartbeat_flags;
  backend_id = other13.backend_id;
  min_active_txn_id = other13.min_active_txn_id;
  run_mode = other13.run_mode;
  disabled_disks = other13.disabled_disks;
  decommissioned_disks = other13.decommissioned_disks;
  encrypted = other13.encrypted;
  __isset = other13.__isset;
}
TMasterInfo& TMasterInfo::operator=(const TMasterInfo& other14) {
  network_address = other14.network_address;
  cluster_id = other14.cluster_id;
  epoch = other14.epoch;
  token = other14.token;
  backend_ip = other14.backend_ip;
  http_port = other14.http_port;
  heartbeat_flags = other14.heartbeat_flags;
  backend_id = other14.backend_id;
  min_active_txn_id = other14.min_active_txn_id;
  run_mode = other14.run_mode;
  disabled_disks = other14.disabled_disks;
  decommissioned_disks = other14.decommissioned_disks;
  encrypted = other14.encrypted;
  __isset = other14.__isset;
  return *this;
}
void TMasterInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TMasterInfo(";
  out << "network_address=" << to_string(network_address);
  out << ", " << "cluster_id="; (__isset.cluster_id ? (out << to_string(cluster_id)) : (out << "<null>"));
  out << ", " << "epoch=" << to_string(epoch);
  out << ", " << "token="; (__isset.token ? (out << to_string(token)) : (out << "<null>"));
  out << ", " << "backend_ip="; (__isset.backend_ip ? (out << to_string(backend_ip)) : (out << "<null>"));
  out << ", " << "http_port="; (__isset.http_port ? (out << to_string(http_port)) : (out << "<null>"));
  out << ", " << "heartbeat_flags="; (__isset.heartbeat_flags ? (out << to_string(heartbeat_flags)) : (out << "<null>"));
  out << ", " << "backend_id="; (__isset.backend_id ? (out << to_string(backend_id)) : (out << "<null>"));
  out << ", " << "min_active_txn_id="; (__isset.min_active_txn_id ? (out << to_string(min_active_txn_id)) : (out << "<null>"));
  out << ", " << "run_mode="; (__isset.run_mode ? (out << to_string(run_mode)) : (out << "<null>"));
  out << ", " << "disabled_disks="; (__isset.disabled_disks ? (out << to_string(disabled_disks)) : (out << "<null>"));
  out << ", " << "decommissioned_disks="; (__isset.decommissioned_disks ? (out << to_string(decommissioned_disks)) : (out << "<null>"));
  out << ", " << "encrypted="; (__isset.encrypted ? (out << to_string(encrypted)) : (out << "<null>"));
  out << ")";
}


TBackendInfo::~TBackendInfo() noexcept {
}

TBackendInfo::TBackendInfo() noexcept
   : be_port(0),
     http_port(0),
     be_rpc_port(0),
     brpc_port(0),
     version(),
     num_hardware_cores(0),
     starlet_port(0),
     reboot_time(0),
     is_set_storage_path(0),
     mem_limit_bytes(0) {
}

void TBackendInfo::__set_be_port(const  ::starrocks::TPort val) {
  this->be_port = val;
}

void TBackendInfo::__set_http_port(const  ::starrocks::TPort val) {
  this->http_port = val;
}

void TBackendInfo::__set_be_rpc_port(const  ::starrocks::TPort val) {
  this->be_rpc_port = val;
__isset.be_rpc_port = true;
}

void TBackendInfo::__set_brpc_port(const  ::starrocks::TPort val) {
  this->brpc_port = val;
__isset.brpc_port = true;
}

void TBackendInfo::__set_version(const std::string& val) {
  this->version = val;
__isset.version = true;
}

void TBackendInfo::__set_num_hardware_cores(const int32_t val) {
  this->num_hardware_cores = val;
__isset.num_hardware_cores = true;
}

void TBackendInfo::__set_starlet_port(const  ::starrocks::TPort val) {
  this->starlet_port = val;
__isset.starlet_port = true;
}

void TBackendInfo::__set_reboot_time(const int64_t val) {
  this->reboot_time = val;
__isset.reboot_time = true;
}

void TBackendInfo::__set_is_set_storage_path(const bool val) {
  this->is_set_storage_path = val;
__isset.is_set_storage_path = true;
}

void TBackendInfo::__set_mem_limit_bytes(const int64_t val) {
  this->mem_limit_bytes = val;
__isset.mem_limit_bytes = true;
}
std::ostream& operator<<(std::ostream& out, const TBackendInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TBackendInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_be_port = false;
  bool isset_http_port = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->be_port);
          isset_be_port = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->http_port);
          isset_http_port = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->be_rpc_port);
          this->__isset.be_rpc_port = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->brpc_port);
          this->__isset.brpc_port = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->version);
          this->__isset.version = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->num_hardware_cores);
          this->__isset.num_hardware_cores = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->starlet_port);
          this->__isset.starlet_port = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->reboot_time);
          this->__isset.reboot_time = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->is_set_storage_path);
          this->__isset.is_set_storage_path = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->mem_limit_bytes);
          this->__isset.mem_limit_bytes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_be_port)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_http_port)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TBackendInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TBackendInfo");

  xfer += oprot->writeFieldBegin("be_port", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->be_port);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("http_port", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->http_port);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.be_rpc_port) {
    xfer += oprot->writeFieldBegin("be_rpc_port", ::apache::thrift::protocol::T_I32, 3);
    xfer += oprot->writeI32(this->be_rpc_port);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.brpc_port) {
    xfer += oprot->writeFieldBegin("brpc_port", ::apache::thrift::protocol::T_I32, 4);
    xfer += oprot->writeI32(this->brpc_port);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.version) {
    xfer += oprot->writeFieldBegin("version", ::apache::thrift::protocol::T_STRING, 5);
    xfer += oprot->writeString(this->version);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.num_hardware_cores) {
    xfer += oprot->writeFieldBegin("num_hardware_cores", ::apache::thrift::protocol::T_I32, 6);
    xfer += oprot->writeI32(this->num_hardware_cores);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.starlet_port) {
    xfer += oprot->writeFieldBegin("starlet_port", ::apache::thrift::protocol::T_I32, 7);
    xfer += oprot->writeI32(this->starlet_port);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.reboot_time) {
    xfer += oprot->writeFieldBegin("reboot_time", ::apache::thrift::protocol::T_I64, 8);
    xfer += oprot->writeI64(this->reboot_time);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.is_set_storage_path) {
    xfer += oprot->writeFieldBegin("is_set_storage_path", ::apache::thrift::protocol::T_BOOL, 9);
    xfer += oprot->writeBool(this->is_set_storage_path);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.mem_limit_bytes) {
    xfer += oprot->writeFieldBegin("mem_limit_bytes", ::apache::thrift::protocol::T_I64, 10);
    xfer += oprot->writeI64(this->mem_limit_bytes);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TBackendInfo &a, TBackendInfo &b) {
  using ::std::swap;
  swap(a.be_port, b.be_port);
  swap(a.http_port, b.http_port);
  swap(a.be_rpc_port, b.be_rpc_port);
  swap(a.brpc_port, b.brpc_port);
  swap(a.version, b.version);
  swap(a.num_hardware_cores, b.num_hardware_cores);
  swap(a.starlet_port, b.starlet_port);
  swap(a.reboot_time, b.reboot_time);
  swap(a.is_set_storage_path, b.is_set_storage_path);
  swap(a.mem_limit_bytes, b.mem_limit_bytes);
  swap(a.__isset, b.__isset);
}

bool TBackendInfo::operator==(const TBackendInfo & rhs) const
{
  if (!(be_port == rhs.be_port))
    return false;
  if (!(http_port == rhs.http_port))
    return false;
  if (__isset.be_rpc_port != rhs.__isset.be_rpc_port)
    return false;
  else if (__isset.be_rpc_port && !(be_rpc_port == rhs.be_rpc_port))
    return false;
  if (__isset.brpc_port != rhs.__isset.brpc_port)
    return false;
  else if (__isset.brpc_port && !(brpc_port == rhs.brpc_port))
    return false;
  if (__isset.version != rhs.__isset.version)
    return false;
  else if (__isset.version && !(version == rhs.version))
    return false;
  if (__isset.num_hardware_cores != rhs.__isset.num_hardware_cores)
    return false;
  else if (__isset.num_hardware_cores && !(num_hardware_cores == rhs.num_hardware_cores))
    return false;
  if (__isset.starlet_port != rhs.__isset.starlet_port)
    return false;
  else if (__isset.starlet_port && !(starlet_port == rhs.starlet_port))
    return false;
  if (__isset.reboot_time != rhs.__isset.reboot_time)
    return false;
  else if (__isset.reboot_time && !(reboot_time == rhs.reboot_time))
    return false;
  if (__isset.is_set_storage_path != rhs.__isset.is_set_storage_path)
    return false;
  else if (__isset.is_set_storage_path && !(is_set_storage_path == rhs.is_set_storage_path))
    return false;
  if (__isset.mem_limit_bytes != rhs.__isset.mem_limit_bytes)
    return false;
  else if (__isset.mem_limit_bytes && !(mem_limit_bytes == rhs.mem_limit_bytes))
    return false;
  return true;
}

TBackendInfo::TBackendInfo(const TBackendInfo& other15) {
  be_port = other15.be_port;
  http_port = other15.http_port;
  be_rpc_port = other15.be_rpc_port;
  brpc_port = other15.brpc_port;
  version = other15.version;
  num_hardware_cores = other15.num_hardware_cores;
  starlet_port = other15.starlet_port;
  reboot_time = other15.reboot_time;
  is_set_storage_path = other15.is_set_storage_path;
  mem_limit_bytes = other15.mem_limit_bytes;
  __isset = other15.__isset;
}
TBackendInfo& TBackendInfo::operator=(const TBackendInfo& other16) {
  be_port = other16.be_port;
  http_port = other16.http_port;
  be_rpc_port = other16.be_rpc_port;
  brpc_port = other16.brpc_port;
  version = other16.version;
  num_hardware_cores = other16.num_hardware_cores;
  starlet_port = other16.starlet_port;
  reboot_time = other16.reboot_time;
  is_set_storage_path = other16.is_set_storage_path;
  mem_limit_bytes = other16.mem_limit_bytes;
  __isset = other16.__isset;
  return *this;
}
void TBackendInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TBackendInfo(";
  out << "be_port=" << to_string(be_port);
  out << ", " << "http_port=" << to_string(http_port);
  out << ", " << "be_rpc_port="; (__isset.be_rpc_port ? (out << to_string(be_rpc_port)) : (out << "<null>"));
  out << ", " << "brpc_port="; (__isset.brpc_port ? (out << to_string(brpc_port)) : (out << "<null>"));
  out << ", " << "version="; (__isset.version ? (out << to_string(version)) : (out << "<null>"));
  out << ", " << "num_hardware_cores="; (__isset.num_hardware_cores ? (out << to_string(num_hardware_cores)) : (out << "<null>"));
  out << ", " << "starlet_port="; (__isset.starlet_port ? (out << to_string(starlet_port)) : (out << "<null>"));
  out << ", " << "reboot_time="; (__isset.reboot_time ? (out << to_string(reboot_time)) : (out << "<null>"));
  out << ", " << "is_set_storage_path="; (__isset.is_set_storage_path ? (out << to_string(is_set_storage_path)) : (out << "<null>"));
  out << ", " << "mem_limit_bytes="; (__isset.mem_limit_bytes ? (out << to_string(mem_limit_bytes)) : (out << "<null>"));
  out << ")";
}


THeartbeatResult::~THeartbeatResult() noexcept {
}

THeartbeatResult::THeartbeatResult() noexcept {
}

void THeartbeatResult::__set_status(const  ::starrocks::TStatus& val) {
  this->status = val;
}

void THeartbeatResult::__set_backend_info(const TBackendInfo& val) {
  this->backend_info = val;
}
std::ostream& operator<<(std::ostream& out, const THeartbeatResult& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t THeartbeatResult::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_status = false;
  bool isset_backend_info = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->status.read(iprot);
          isset_status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->backend_info.read(iprot);
          isset_backend_info = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_status)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_backend_info)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t THeartbeatResult::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("THeartbeatResult");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_STRUCT, 1);
  xfer += this->status.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("backend_info", ::apache::thrift::protocol::T_STRUCT, 2);
  xfer += this->backend_info.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(THeartbeatResult &a, THeartbeatResult &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.backend_info, b.backend_info);
}

bool THeartbeatResult::operator==(const THeartbeatResult & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(backend_info == rhs.backend_info))
    return false;
  return true;
}

THeartbeatResult::THeartbeatResult(const THeartbeatResult& other17) {
  status = other17.status;
  backend_info = other17.backend_info;
}
THeartbeatResult& THeartbeatResult::operator=(const THeartbeatResult& other18) {
  status = other18.status;
  backend_info = other18.backend_info;
  return *this;
}
void THeartbeatResult::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "THeartbeatResult(";
  out << "status=" << to_string(status);
  out << ", " << "backend_info=" << to_string(backend_info);
  out << ")";
}

} // namespace
