/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Opcodes_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>



int _kTExprOpcodeValues[] = {
  TExprOpcode::INVALID_OPCODE,
  TExprOpcode::COMPOUND_NOT,
  TExprOpcode::COMPOUND_AND,
  TExprOpcode::COMPOUND_OR,
  TExprOpcode::CAST,
  TExprOpcode::FILTER_IN,
  TExprOpcode::FILTER_NOT_IN,
  TExprOpcode::FILTER_NEW_IN,
  TExprOpcode::FILTER_NEW_NOT_IN,
  TExprOpcode::EQ,
  TExprOpcode::NE,
  TExprOpcode::LT,
  TExprOpcode::LE,
  TExprOpcode::GT,
  TExprOpcode::GE,
  TExprOpcode::CONDITION_IF,
  TExprOpcode::CONDITION_NULLIF,
  TExprOpcode::CONDITION_IFNULL,
  TExprOpcode::CONDITION_COALESCE,
  TExprOpcode::TIMESTAMP_DATE_FORMAT,
  TExprOpcode::TIMESTAMP_DAYOFMONTH,
  TExprOpcode::TIMESTAMP_DAYOFYEAR,
  TExprOpcode::TIMESTAMP_DAYS_ADD,
  TExprOpcode::TIMESTAMP_DAYS_SUB,
  TExprOpcode::TIMESTAMP_DAY_NAME,
  TExprOpcode::TIMESTAMP_DIFF,
  TExprOpcode::TIMESTAMP_FROM_DAYS,
  TExprOpcode::TIMESTAMP_HOUR,
  TExprOpcode::TIMESTAMP_HOURS_ADD,
  TExprOpcode::TIMESTAMP_HOURS_SUB,
  TExprOpcode::TIMESTAMP_MICROSECONDS_ADD,
  TExprOpcode::TIMESTAMP_MICROSECONDS_SUB,
  TExprOpcode::TIMESTAMP_MINUTE,
  TExprOpcode::TIMESTAMP_MINUTES_ADD,
  TExprOpcode::TIMESTAMP_MINUTES_SUB,
  TExprOpcode::TIMESTAMP_MONTH,
  TExprOpcode::TIMESTAMP_MONTHS_ADD,
  TExprOpcode::TIMESTAMP_MONTHS_SUB,
  TExprOpcode::TIMESTAMP_MONT_NAME,
  TExprOpcode::TIMESTAMP_NOW,
  TExprOpcode::TIMESTAMP_SECOND,
  TExprOpcode::TIMESTAMP_SECONDS_ADD,
  TExprOpcode::TIMESTAMP_SECONDS_SUB,
  TExprOpcode::TIMESTAMP_STR_TO_DATE,
  TExprOpcode::TIMESTAMP_TO_DATE,
  TExprOpcode::TIMESTAMP_TO_DAYS,
  TExprOpcode::TIMESTAMP_WEEKOFYEAR,
  TExprOpcode::TIMESTAMP_WEEKS_ADD,
  TExprOpcode::TIMESTAMP_WEEKS_SUB,
  TExprOpcode::TIMESTAMP_YEAR,
  TExprOpcode::TIMESTAMP_YEARS_ADD,
  TExprOpcode::TIMESTAMP_YEARS_SUB,
  TExprOpcode::ADD,
  TExprOpcode::SUBTRACT,
  TExprOpcode::MULTIPLY,
  TExprOpcode::DIVIDE,
  TExprOpcode::INT_DIVIDE,
  TExprOpcode::MOD,
  TExprOpcode::BITAND,
  TExprOpcode::BITOR,
  TExprOpcode::BITXOR,
  TExprOpcode::BITNOT,
  TExprOpcode::FACTORIAL,
  TExprOpcode::LAST_OPCODE,
  TExprOpcode::EQ_FOR_NULL,
  TExprOpcode::BIT_SHIFT_LEFT,
  TExprOpcode::BIT_SHIFT_RIGHT,
  TExprOpcode::BIT_SHIFT_RIGHT_LOGICAL,
  TExprOpcode::JIT
};
const char* _kTExprOpcodeNames[] = {
  "INVALID_OPCODE",
  "COMPOUND_NOT",
  "COMPOUND_AND",
  "COMPOUND_OR",
  "CAST",
  "FILTER_IN",
  "FILTER_NOT_IN",
  "FILTER_NEW_IN",
  "FILTER_NEW_NOT_IN",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "CONDITION_IF",
  "CONDITION_NULLIF",
  "CONDITION_IFNULL",
  "CONDITION_COALESCE",
  "TIMESTAMP_DATE_FORMAT",
  "TIMESTAMP_DAYOFMONTH",
  "TIMESTAMP_DAYOFYEAR",
  "TIMESTAMP_DAYS_ADD",
  "TIMESTAMP_DAYS_SUB",
  "TIMESTAMP_DAY_NAME",
  "TIMESTAMP_DIFF",
  "TIMESTAMP_FROM_DAYS",
  "TIMESTAMP_HOUR",
  "TIMESTAMP_HOURS_ADD",
  "TIMESTAMP_HOURS_SUB",
  "TIMESTAMP_MICROSECONDS_ADD",
  "TIMESTAMP_MICROSECONDS_SUB",
  "TIMESTAMP_MINUTE",
  "TIMESTAMP_MINUTES_ADD",
  "TIMESTAMP_MINUTES_SUB",
  "TIMESTAMP_MONTH",
  "TIMESTAMP_MONTHS_ADD",
  "TIMESTAMP_MONTHS_SUB",
  "TIMESTAMP_MONT_NAME",
  "TIMESTAMP_NOW",
  "TIMESTAMP_SECOND",
  "TIMESTAMP_SECONDS_ADD",
  "TIMESTAMP_SECONDS_SUB",
  "TIMESTAMP_STR_TO_DATE",
  "TIMESTAMP_TO_DATE",
  "TIMESTAMP_TO_DAYS",
  "TIMESTAMP_WEEKOFYEAR",
  "TIMESTAMP_WEEKS_ADD",
  "TIMESTAMP_WEEKS_SUB",
  "TIMESTAMP_YEAR",
  "TIMESTAMP_YEARS_ADD",
  "TIMESTAMP_YEARS_SUB",
  "ADD",
  "SUBTRACT",
  "MULTIPLY",
  "DIVIDE",
  "INT_DIVIDE",
  "MOD",
  "BITAND",
  "BITOR",
  "BITXOR",
  "BITNOT",
  "FACTORIAL",
  "LAST_OPCODE",
  "EQ_FOR_NULL",
  "BIT_SHIFT_LEFT",
  "BIT_SHIFT_RIGHT",
  "BIT_SHIFT_RIGHT_LOGICAL",
  "JIT"
};
const std::map<int, const char*> _TExprOpcode_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(69, _kTExprOpcodeValues, _kTExprOpcodeNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const TExprOpcode::type& val) {
  std::map<int, const char*>::const_iterator it = _TExprOpcode_VALUES_TO_NAMES.find(val);
  if (it != _TExprOpcode_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const TExprOpcode::type& val) {
  std::map<int, const char*>::const_iterator it = _TExprOpcode_VALUES_TO_NAMES.find(val);
  if (it != _TExprOpcode_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kTStreamOpTypeValues[] = {
  TStreamOpType::INSERT,
  TStreamOpType::UPDATE_BEFORE,
  TStreamOpType::UPDATE_AFTER,
  TStreamOpType::DELETE
};
const char* _kTStreamOpTypeNames[] = {
  "INSERT",
  "UPDATE_BEFORE",
  "UPDATE_AFTER",
  "DELETE"
};
const std::map<int, const char*> _TStreamOpType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kTStreamOpTypeValues, _kTStreamOpTypeNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const TStreamOpType::type& val) {
  std::map<int, const char*>::const_iterator it = _TStreamOpType_VALUES_TO_NAMES.find(val);
  if (it != _TStreamOpType_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const TStreamOpType::type& val) {
  std::map<int, const char*>::const_iterator it = _TStreamOpType_VALUES_TO_NAMES.find(val);
  if (it != _TStreamOpType_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


