/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Partitions_TYPES_H
#define Partitions_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>
#include "Exprs_types.h"
#include "Types_types.h"


namespace starrocks {

struct TPartitionType {
  enum type {
    UNPARTITIONED = 0,
    RANDOM = 1,
    HASH_PARTITIONED = 2,
    RANGE_PARTITIONED = 3,
    BUCKET_SHUFFLE_HASH_PARTITIONED = 4
  };
};

extern const std::map<int, const char*> _TPartitionType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TPartitionType::type& val);

std::string to_string(const TPartitionType::type& val);

struct TDistributionType {
  enum type {
    ANY = 0,
    BROADCAST = 1,
    SHUFFLE = 2,
    GATHER = 3
  };
};

extern const std::map<int, const char*> _TDistributionType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TDistributionType::type& val);

std::string to_string(const TDistributionType::type& val);

class TPartitionKey;

class TPartitionRange;

class TRangePartition;

class TDataPartition;

typedef struct _TPartitionKey__isset {
  _TPartitionKey__isset() : type(false), key(false) {}
  bool type :1;
  bool key :1;
} _TPartitionKey__isset;

class TPartitionKey : public virtual ::apache::thrift::TBase {
 public:

  TPartitionKey(const TPartitionKey&);
  TPartitionKey& operator=(const TPartitionKey&);
  TPartitionKey() noexcept;

  virtual ~TPartitionKey() noexcept;
  int16_t sign;
  /**
   * 
   * @see com.starrocks.thrift.TPrimitiveType
   */
   ::starrocks::TPrimitiveType::type type;
  std::string key;

  _TPartitionKey__isset __isset;

  void __set_sign(const int16_t val);

  void __set_type(const  ::starrocks::TPrimitiveType::type val);

  void __set_key(const std::string& val);

  bool operator == (const TPartitionKey & rhs) const;
  bool operator != (const TPartitionKey &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TPartitionKey & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TPartitionKey &a, TPartitionKey &b);

std::ostream& operator<<(std::ostream& out, const TPartitionKey& obj);


class TPartitionRange : public virtual ::apache::thrift::TBase {
 public:

  TPartitionRange(const TPartitionRange&);
  TPartitionRange& operator=(const TPartitionRange&);
  TPartitionRange() noexcept;

  virtual ~TPartitionRange() noexcept;
  TPartitionKey start_key;
  TPartitionKey end_key;
  bool include_start_key;
  bool include_end_key;

  void __set_start_key(const TPartitionKey& val);

  void __set_end_key(const TPartitionKey& val);

  void __set_include_start_key(const bool val);

  void __set_include_end_key(const bool val);

  bool operator == (const TPartitionRange & rhs) const;
  bool operator != (const TPartitionRange &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TPartitionRange & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TPartitionRange &a, TPartitionRange &b);

std::ostream& operator<<(std::ostream& out, const TPartitionRange& obj);

typedef struct _TRangePartition__isset {
  _TRangePartition__isset() : distributed_exprs(false), distribute_bucket(false) {}
  bool distributed_exprs :1;
  bool distribute_bucket :1;
} _TRangePartition__isset;

class TRangePartition : public virtual ::apache::thrift::TBase {
 public:

  TRangePartition(const TRangePartition&);
  TRangePartition& operator=(const TRangePartition&);
  TRangePartition() noexcept;

  virtual ~TRangePartition() noexcept;
  int64_t partition_id;
  TPartitionRange range;
  std::vector< ::starrocks::TExpr>  distributed_exprs;
  int32_t distribute_bucket;

  _TRangePartition__isset __isset;

  void __set_partition_id(const int64_t val);

  void __set_range(const TPartitionRange& val);

  void __set_distributed_exprs(const std::vector< ::starrocks::TExpr> & val);

  void __set_distribute_bucket(const int32_t val);

  bool operator == (const TRangePartition & rhs) const;
  bool operator != (const TRangePartition &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TRangePartition & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TRangePartition &a, TRangePartition &b);

std::ostream& operator<<(std::ostream& out, const TRangePartition& obj);

typedef struct _TDataPartition__isset {
  _TDataPartition__isset() : partition_exprs(false), partition_infos(false) {}
  bool partition_exprs :1;
  bool partition_infos :1;
} _TDataPartition__isset;

class TDataPartition : public virtual ::apache::thrift::TBase {
 public:

  TDataPartition(const TDataPartition&);
  TDataPartition& operator=(const TDataPartition&);
  TDataPartition() noexcept;

  virtual ~TDataPartition() noexcept;
  /**
   * 
   * @see TPartitionType
   */
  TPartitionType::type type;
  std::vector< ::starrocks::TExpr>  partition_exprs;
  std::vector<TRangePartition>  partition_infos;

  _TDataPartition__isset __isset;

  void __set_type(const TPartitionType::type val);

  void __set_partition_exprs(const std::vector< ::starrocks::TExpr> & val);

  void __set_partition_infos(const std::vector<TRangePartition> & val);

  bool operator == (const TDataPartition & rhs) const;
  bool operator != (const TDataPartition &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDataPartition & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TDataPartition &a, TDataPartition &b);

std::ostream& operator<<(std::ostream& out, const TDataPartition& obj);

} // namespace

#endif
