/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RuntimeFilter_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace starrocks {

int _kTRuntimeFilterBuildJoinModeValues[] = {
  TRuntimeFilterBuildJoinMode::NONE,
  TRuntimeFilterBuildJoinMode::BORADCAST,
  TRuntimeFilterBuildJoinMode::PARTITIONED,
  TRuntimeFilterBuildJoinMode::LOCAL_HASH_BUCKET,
  TRuntimeFilterBuildJoinMode::COLOCATE,
  TRuntimeFilterBuildJoinMode::SHUFFLE_HASH_BUCKET,
  TRuntimeFilterBuildJoinMode::REPLICATED
};
const char* _kTRuntimeFilterBuildJoinModeNames[] = {
  "NONE",
  "BORADCAST",
  "PARTITIONED",
  "LOCAL_HASH_BUCKET",
  "COLOCATE",
  "SHUFFLE_HASH_BUCKET",
  "REPLICATED"
};
const std::map<int, const char*> _TRuntimeFilterBuildJoinMode_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(7, _kTRuntimeFilterBuildJoinModeValues, _kTRuntimeFilterBuildJoinModeNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const TRuntimeFilterBuildJoinMode::type& val) {
  std::map<int, const char*>::const_iterator it = _TRuntimeFilterBuildJoinMode_VALUES_TO_NAMES.find(val);
  if (it != _TRuntimeFilterBuildJoinMode_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const TRuntimeFilterBuildJoinMode::type& val) {
  std::map<int, const char*>::const_iterator it = _TRuntimeFilterBuildJoinMode_VALUES_TO_NAMES.find(val);
  if (it != _TRuntimeFilterBuildJoinMode_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kTRuntimeFilterBuildTypeValues[] = {
  TRuntimeFilterBuildType::JOIN_FILTER,
  TRuntimeFilterBuildType::TOPN_FILTER
};
const char* _kTRuntimeFilterBuildTypeNames[] = {
  "JOIN_FILTER",
  "TOPN_FILTER"
};
const std::map<int, const char*> _TRuntimeFilterBuildType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(2, _kTRuntimeFilterBuildTypeValues, _kTRuntimeFilterBuildTypeNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const TRuntimeFilterBuildType::type& val) {
  std::map<int, const char*>::const_iterator it = _TRuntimeFilterBuildType_VALUES_TO_NAMES.find(val);
  if (it != _TRuntimeFilterBuildType_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const TRuntimeFilterBuildType::type& val) {
  std::map<int, const char*>::const_iterator it = _TRuntimeFilterBuildType_VALUES_TO_NAMES.find(val);
  if (it != _TRuntimeFilterBuildType_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kTRuntimeFilterLayoutModeValues[] = {
  TRuntimeFilterLayoutMode::NONE,
  TRuntimeFilterLayoutMode::SINGLETON,
  TRuntimeFilterLayoutMode::PIPELINE_SHUFFLE,
  TRuntimeFilterLayoutMode::GLOBAL_SHUFFLE_2L,
  TRuntimeFilterLayoutMode::GLOBAL_SHUFFLE_1L,
  TRuntimeFilterLayoutMode::PIPELINE_BUCKET_LX,
  TRuntimeFilterLayoutMode::PIPELINE_BUCKET,
  TRuntimeFilterLayoutMode::GLOBAL_BUCKET_2L_LX,
  TRuntimeFilterLayoutMode::GLOBAL_BUCKET_2L,
  TRuntimeFilterLayoutMode::GLOBAL_BUCKET_1L
};
const char* _kTRuntimeFilterLayoutModeNames[] = {
  "NONE",
  "SINGLETON",
  "PIPELINE_SHUFFLE",
  "GLOBAL_SHUFFLE_2L",
  "GLOBAL_SHUFFLE_1L",
  "PIPELINE_BUCKET_LX",
  "PIPELINE_BUCKET",
  "GLOBAL_BUCKET_2L_LX",
  "GLOBAL_BUCKET_2L",
  "GLOBAL_BUCKET_1L"
};
const std::map<int, const char*> _TRuntimeFilterLayoutMode_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(10, _kTRuntimeFilterLayoutModeValues, _kTRuntimeFilterLayoutModeNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const TRuntimeFilterLayoutMode::type& val) {
  std::map<int, const char*>::const_iterator it = _TRuntimeFilterLayoutMode_VALUES_TO_NAMES.find(val);
  if (it != _TRuntimeFilterLayoutMode_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const TRuntimeFilterLayoutMode::type& val) {
  std::map<int, const char*>::const_iterator it = _TRuntimeFilterLayoutMode_VALUES_TO_NAMES.find(val);
  if (it != _TRuntimeFilterLayoutMode_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


TRuntimeFilterDestination::~TRuntimeFilterDestination() noexcept {
}

TRuntimeFilterDestination::TRuntimeFilterDestination() noexcept {
}

void TRuntimeFilterDestination::__set_address(const  ::starrocks::TNetworkAddress& val) {
  this->address = val;
__isset.address = true;
}

void TRuntimeFilterDestination::__set_finstance_ids(const std::vector< ::starrocks::TUniqueId> & val) {
  this->finstance_ids = val;
__isset.finstance_ids = true;
}
std::ostream& operator<<(std::ostream& out, const TRuntimeFilterDestination& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TRuntimeFilterDestination::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->address.read(iprot);
          this->__isset.address = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->finstance_ids.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->finstance_ids.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += this->finstance_ids[_i4].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.finstance_ids = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TRuntimeFilterDestination::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TRuntimeFilterDestination");

  if (this->__isset.address) {
    xfer += oprot->writeFieldBegin("address", ::apache::thrift::protocol::T_STRUCT, 1);
    xfer += this->address.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.finstance_ids) {
    xfer += oprot->writeFieldBegin("finstance_ids", ::apache::thrift::protocol::T_LIST, 2);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->finstance_ids.size()));
      std::vector< ::starrocks::TUniqueId> ::const_iterator _iter5;
      for (_iter5 = this->finstance_ids.begin(); _iter5 != this->finstance_ids.end(); ++_iter5)
      {
        xfer += (*_iter5).write(oprot);
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TRuntimeFilterDestination &a, TRuntimeFilterDestination &b) {
  using ::std::swap;
  swap(a.address, b.address);
  swap(a.finstance_ids, b.finstance_ids);
  swap(a.__isset, b.__isset);
}

bool TRuntimeFilterDestination::operator==(const TRuntimeFilterDestination & rhs) const
{
  if (__isset.address != rhs.__isset.address)
    return false;
  else if (__isset.address && !(address == rhs.address))
    return false;
  if (__isset.finstance_ids != rhs.__isset.finstance_ids)
    return false;
  else if (__isset.finstance_ids && !(finstance_ids == rhs.finstance_ids))
    return false;
  return true;
}

TRuntimeFilterDestination::TRuntimeFilterDestination(const TRuntimeFilterDestination& other6) {
  address = other6.address;
  finstance_ids = other6.finstance_ids;
  __isset = other6.__isset;
}
TRuntimeFilterDestination& TRuntimeFilterDestination::operator=(const TRuntimeFilterDestination& other7) {
  address = other7.address;
  finstance_ids = other7.finstance_ids;
  __isset = other7.__isset;
  return *this;
}
void TRuntimeFilterDestination::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TRuntimeFilterDestination(";
  out << "address="; (__isset.address ? (out << to_string(address)) : (out << "<null>"));
  out << ", " << "finstance_ids="; (__isset.finstance_ids ? (out << to_string(finstance_ids)) : (out << "<null>"));
  out << ")";
}


TRuntimeFilterLayout::~TRuntimeFilterLayout() noexcept {
}

TRuntimeFilterLayout::TRuntimeFilterLayout() noexcept
   : filter_id(0),
     local_layout(static_cast<TRuntimeFilterLayoutMode::type>(0)),
     global_layout(static_cast<TRuntimeFilterLayoutMode::type>(0)),
     pipeline_level_multi_partitioned(0),
     num_instances(0),
     num_drivers_per_instance(0) {
}

void TRuntimeFilterLayout::__set_filter_id(const int32_t val) {
  this->filter_id = val;
__isset.filter_id = true;
}

void TRuntimeFilterLayout::__set_local_layout(const TRuntimeFilterLayoutMode::type val) {
  this->local_layout = val;
__isset.local_layout = true;
}

void TRuntimeFilterLayout::__set_global_layout(const TRuntimeFilterLayoutMode::type val) {
  this->global_layout = val;
__isset.global_layout = true;
}

void TRuntimeFilterLayout::__set_pipeline_level_multi_partitioned(const bool val) {
  this->pipeline_level_multi_partitioned = val;
__isset.pipeline_level_multi_partitioned = true;
}

void TRuntimeFilterLayout::__set_num_instances(const int32_t val) {
  this->num_instances = val;
__isset.num_instances = true;
}

void TRuntimeFilterLayout::__set_num_drivers_per_instance(const int32_t val) {
  this->num_drivers_per_instance = val;
__isset.num_drivers_per_instance = true;
}

void TRuntimeFilterLayout::__set_bucketseq_to_instance(const std::vector<int32_t> & val) {
  this->bucketseq_to_instance = val;
__isset.bucketseq_to_instance = true;
}

void TRuntimeFilterLayout::__set_bucketseq_to_driverseq(const std::vector<int32_t> & val) {
  this->bucketseq_to_driverseq = val;
__isset.bucketseq_to_driverseq = true;
}

void TRuntimeFilterLayout::__set_bucketseq_to_partition(const std::vector<int32_t> & val) {
  this->bucketseq_to_partition = val;
__isset.bucketseq_to_partition = true;
}
std::ostream& operator<<(std::ostream& out, const TRuntimeFilterLayout& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TRuntimeFilterLayout::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->filter_id);
          this->__isset.filter_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast8;
          xfer += iprot->readI32(ecast8);
          this->local_layout = static_cast<TRuntimeFilterLayoutMode::type>(ecast8);
          this->__isset.local_layout = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast9;
          xfer += iprot->readI32(ecast9);
          this->global_layout = static_cast<TRuntimeFilterLayoutMode::type>(ecast9);
          this->__isset.global_layout = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->pipeline_level_multi_partitioned);
          this->__isset.pipeline_level_multi_partitioned = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->num_instances);
          this->__isset.num_instances = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->num_drivers_per_instance);
          this->__isset.num_drivers_per_instance = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->bucketseq_to_instance.clear();
            uint32_t _size10;
            ::apache::thrift::protocol::TType _etype13;
            xfer += iprot->readListBegin(_etype13, _size10);
            this->bucketseq_to_instance.resize(_size10);
            uint32_t _i14;
            for (_i14 = 0; _i14 < _size10; ++_i14)
            {
              xfer += iprot->readI32(this->bucketseq_to_instance[_i14]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.bucketseq_to_instance = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->bucketseq_to_driverseq.clear();
            uint32_t _size15;
            ::apache::thrift::protocol::TType _etype18;
            xfer += iprot->readListBegin(_etype18, _size15);
            this->bucketseq_to_driverseq.resize(_size15);
            uint32_t _i19;
            for (_i19 = 0; _i19 < _size15; ++_i19)
            {
              xfer += iprot->readI32(this->bucketseq_to_driverseq[_i19]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.bucketseq_to_driverseq = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->bucketseq_to_partition.clear();
            uint32_t _size20;
            ::apache::thrift::protocol::TType _etype23;
            xfer += iprot->readListBegin(_etype23, _size20);
            this->bucketseq_to_partition.resize(_size20);
            uint32_t _i24;
            for (_i24 = 0; _i24 < _size20; ++_i24)
            {
              xfer += iprot->readI32(this->bucketseq_to_partition[_i24]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.bucketseq_to_partition = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TRuntimeFilterLayout::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TRuntimeFilterLayout");

  if (this->__isset.filter_id) {
    xfer += oprot->writeFieldBegin("filter_id", ::apache::thrift::protocol::T_I32, 1);
    xfer += oprot->writeI32(this->filter_id);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.local_layout) {
    xfer += oprot->writeFieldBegin("local_layout", ::apache::thrift::protocol::T_I32, 2);
    xfer += oprot->writeI32(static_cast<int32_t>(this->local_layout));
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.global_layout) {
    xfer += oprot->writeFieldBegin("global_layout", ::apache::thrift::protocol::T_I32, 3);
    xfer += oprot->writeI32(static_cast<int32_t>(this->global_layout));
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.pipeline_level_multi_partitioned) {
    xfer += oprot->writeFieldBegin("pipeline_level_multi_partitioned", ::apache::thrift::protocol::T_BOOL, 4);
    xfer += oprot->writeBool(this->pipeline_level_multi_partitioned);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.num_instances) {
    xfer += oprot->writeFieldBegin("num_instances", ::apache::thrift::protocol::T_I32, 5);
    xfer += oprot->writeI32(this->num_instances);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.num_drivers_per_instance) {
    xfer += oprot->writeFieldBegin("num_drivers_per_instance", ::apache::thrift::protocol::T_I32, 6);
    xfer += oprot->writeI32(this->num_drivers_per_instance);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.bucketseq_to_instance) {
    xfer += oprot->writeFieldBegin("bucketseq_to_instance", ::apache::thrift::protocol::T_LIST, 7);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->bucketseq_to_instance.size()));
      std::vector<int32_t> ::const_iterator _iter25;
      for (_iter25 = this->bucketseq_to_instance.begin(); _iter25 != this->bucketseq_to_instance.end(); ++_iter25)
      {
        xfer += oprot->writeI32((*_iter25));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.bucketseq_to_driverseq) {
    xfer += oprot->writeFieldBegin("bucketseq_to_driverseq", ::apache::thrift::protocol::T_LIST, 8);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->bucketseq_to_driverseq.size()));
      std::vector<int32_t> ::const_iterator _iter26;
      for (_iter26 = this->bucketseq_to_driverseq.begin(); _iter26 != this->bucketseq_to_driverseq.end(); ++_iter26)
      {
        xfer += oprot->writeI32((*_iter26));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.bucketseq_to_partition) {
    xfer += oprot->writeFieldBegin("bucketseq_to_partition", ::apache::thrift::protocol::T_LIST, 9);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->bucketseq_to_partition.size()));
      std::vector<int32_t> ::const_iterator _iter27;
      for (_iter27 = this->bucketseq_to_partition.begin(); _iter27 != this->bucketseq_to_partition.end(); ++_iter27)
      {
        xfer += oprot->writeI32((*_iter27));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TRuntimeFilterLayout &a, TRuntimeFilterLayout &b) {
  using ::std::swap;
  swap(a.filter_id, b.filter_id);
  swap(a.local_layout, b.local_layout);
  swap(a.global_layout, b.global_layout);
  swap(a.pipeline_level_multi_partitioned, b.pipeline_level_multi_partitioned);
  swap(a.num_instances, b.num_instances);
  swap(a.num_drivers_per_instance, b.num_drivers_per_instance);
  swap(a.bucketseq_to_instance, b.bucketseq_to_instance);
  swap(a.bucketseq_to_driverseq, b.bucketseq_to_driverseq);
  swap(a.bucketseq_to_partition, b.bucketseq_to_partition);
  swap(a.__isset, b.__isset);
}

bool TRuntimeFilterLayout::operator==(const TRuntimeFilterLayout & rhs) const
{
  if (__isset.filter_id != rhs.__isset.filter_id)
    return false;
  else if (__isset.filter_id && !(filter_id == rhs.filter_id))
    return false;
  if (__isset.local_layout != rhs.__isset.local_layout)
    return false;
  else if (__isset.local_layout && !(local_layout == rhs.local_layout))
    return false;
  if (__isset.global_layout != rhs.__isset.global_layout)
    return false;
  else if (__isset.global_layout && !(global_layout == rhs.global_layout))
    return false;
  if (__isset.pipeline_level_multi_partitioned != rhs.__isset.pipeline_level_multi_partitioned)
    return false;
  else if (__isset.pipeline_level_multi_partitioned && !(pipeline_level_multi_partitioned == rhs.pipeline_level_multi_partitioned))
    return false;
  if (__isset.num_instances != rhs.__isset.num_instances)
    return false;
  else if (__isset.num_instances && !(num_instances == rhs.num_instances))
    return false;
  if (__isset.num_drivers_per_instance != rhs.__isset.num_drivers_per_instance)
    return false;
  else if (__isset.num_drivers_per_instance && !(num_drivers_per_instance == rhs.num_drivers_per_instance))
    return false;
  if (__isset.bucketseq_to_instance != rhs.__isset.bucketseq_to_instance)
    return false;
  else if (__isset.bucketseq_to_instance && !(bucketseq_to_instance == rhs.bucketseq_to_instance))
    return false;
  if (__isset.bucketseq_to_driverseq != rhs.__isset.bucketseq_to_driverseq)
    return false;
  else if (__isset.bucketseq_to_driverseq && !(bucketseq_to_driverseq == rhs.bucketseq_to_driverseq))
    return false;
  if (__isset.bucketseq_to_partition != rhs.__isset.bucketseq_to_partition)
    return false;
  else if (__isset.bucketseq_to_partition && !(bucketseq_to_partition == rhs.bucketseq_to_partition))
    return false;
  return true;
}

TRuntimeFilterLayout::TRuntimeFilterLayout(const TRuntimeFilterLayout& other28) {
  filter_id = other28.filter_id;
  local_layout = other28.local_layout;
  global_layout = other28.global_layout;
  pipeline_level_multi_partitioned = other28.pipeline_level_multi_partitioned;
  num_instances = other28.num_instances;
  num_drivers_per_instance = other28.num_drivers_per_instance;
  bucketseq_to_instance = other28.bucketseq_to_instance;
  bucketseq_to_driverseq = other28.bucketseq_to_driverseq;
  bucketseq_to_partition = other28.bucketseq_to_partition;
  __isset = other28.__isset;
}
TRuntimeFilterLayout& TRuntimeFilterLayout::operator=(const TRuntimeFilterLayout& other29) {
  filter_id = other29.filter_id;
  local_layout = other29.local_layout;
  global_layout = other29.global_layout;
  pipeline_level_multi_partitioned = other29.pipeline_level_multi_partitioned;
  num_instances = other29.num_instances;
  num_drivers_per_instance = other29.num_drivers_per_instance;
  bucketseq_to_instance = other29.bucketseq_to_instance;
  bucketseq_to_driverseq = other29.bucketseq_to_driverseq;
  bucketseq_to_partition = other29.bucketseq_to_partition;
  __isset = other29.__isset;
  return *this;
}
void TRuntimeFilterLayout::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TRuntimeFilterLayout(";
  out << "filter_id="; (__isset.filter_id ? (out << to_string(filter_id)) : (out << "<null>"));
  out << ", " << "local_layout="; (__isset.local_layout ? (out << to_string(local_layout)) : (out << "<null>"));
  out << ", " << "global_layout="; (__isset.global_layout ? (out << to_string(global_layout)) : (out << "<null>"));
  out << ", " << "pipeline_level_multi_partitioned="; (__isset.pipeline_level_multi_partitioned ? (out << to_string(pipeline_level_multi_partitioned)) : (out << "<null>"));
  out << ", " << "num_instances="; (__isset.num_instances ? (out << to_string(num_instances)) : (out << "<null>"));
  out << ", " << "num_drivers_per_instance="; (__isset.num_drivers_per_instance ? (out << to_string(num_drivers_per_instance)) : (out << "<null>"));
  out << ", " << "bucketseq_to_instance="; (__isset.bucketseq_to_instance ? (out << to_string(bucketseq_to_instance)) : (out << "<null>"));
  out << ", " << "bucketseq_to_driverseq="; (__isset.bucketseq_to_driverseq ? (out << to_string(bucketseq_to_driverseq)) : (out << "<null>"));
  out << ", " << "bucketseq_to_partition="; (__isset.bucketseq_to_partition ? (out << to_string(bucketseq_to_partition)) : (out << "<null>"));
  out << ")";
}


TRuntimeFilterDescription::~TRuntimeFilterDescription() noexcept {
}

TRuntimeFilterDescription::TRuntimeFilterDescription() noexcept
   : filter_id(0),
     expr_order(0),
     has_remote_targets(0),
     bloom_filter_size(0),
     build_join_mode(static_cast<TRuntimeFilterBuildJoinMode::type>(0)),
     build_plan_node_id(0),
     filter_type(static_cast<TRuntimeFilterBuildType::type>(0)),
     build_from_group_execution(0) {
}

void TRuntimeFilterDescription::__set_filter_id(const int32_t val) {
  this->filter_id = val;
__isset.filter_id = true;
}

void TRuntimeFilterDescription::__set_build_expr(const  ::starrocks::TExpr& val) {
  this->build_expr = val;
__isset.build_expr = true;
}

void TRuntimeFilterDescription::__set_expr_order(const int32_t val) {
  this->expr_order = val;
__isset.expr_order = true;
}

void TRuntimeFilterDescription::__set_plan_node_id_to_target_expr(const std::map< ::starrocks::TPlanNodeId,  ::starrocks::TExpr> & val) {
  this->plan_node_id_to_target_expr = val;
__isset.plan_node_id_to_target_expr = true;
}

void TRuntimeFilterDescription::__set_has_remote_targets(const bool val) {
  this->has_remote_targets = val;
__isset.has_remote_targets = true;
}

void TRuntimeFilterDescription::__set_bloom_filter_size(const int64_t val) {
  this->bloom_filter_size = val;
__isset.bloom_filter_size = true;
}

void TRuntimeFilterDescription::__set_runtime_filter_merge_nodes(const std::vector< ::starrocks::TNetworkAddress> & val) {
  this->runtime_filter_merge_nodes = val;
__isset.runtime_filter_merge_nodes = true;
}

void TRuntimeFilterDescription::__set_build_join_mode(const TRuntimeFilterBuildJoinMode::type val) {
  this->build_join_mode = val;
__isset.build_join_mode = true;
}

void TRuntimeFilterDescription::__set_sender_finst_id(const  ::starrocks::TUniqueId& val) {
  this->sender_finst_id = val;
__isset.sender_finst_id = true;
}

void TRuntimeFilterDescription::__set_build_plan_node_id(const  ::starrocks::TPlanNodeId val) {
  this->build_plan_node_id = val;
__isset.build_plan_node_id = true;
}

void TRuntimeFilterDescription::__set_broadcast_grf_senders(const std::vector< ::starrocks::TUniqueId> & val) {
  this->broadcast_grf_senders = val;
__isset.broadcast_grf_senders = true;
}

void TRuntimeFilterDescription::__set_broadcast_grf_destinations(const std::vector<TRuntimeFilterDestination> & val) {
  this->broadcast_grf_destinations = val;
__isset.broadcast_grf_destinations = true;
}

void TRuntimeFilterDescription::__set_bucketseq_to_instance(const std::vector<int32_t> & val) {
  this->bucketseq_to_instance = val;
__isset.bucketseq_to_instance = true;
}

void TRuntimeFilterDescription::__set_plan_node_id_to_partition_by_exprs(const std::map< ::starrocks::TPlanNodeId, std::vector< ::starrocks::TExpr> > & val) {
  this->plan_node_id_to_partition_by_exprs = val;
__isset.plan_node_id_to_partition_by_exprs = true;
}

void TRuntimeFilterDescription::__set_filter_type(const TRuntimeFilterBuildType::type val) {
  this->filter_type = val;
__isset.filter_type = true;
}

void TRuntimeFilterDescription::__set_layout(const TRuntimeFilterLayout& val) {
  this->layout = val;
__isset.layout = true;
}

void TRuntimeFilterDescription::__set_build_from_group_execution(const bool val) {
  this->build_from_group_execution = val;
__isset.build_from_group_execution = true;
}
std::ostream& operator<<(std::ostream& out, const TRuntimeFilterDescription& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TRuntimeFilterDescription::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->filter_id);
          this->__isset.filter_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->build_expr.read(iprot);
          this->__isset.build_expr = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->expr_order);
          this->__isset.expr_order = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->plan_node_id_to_target_expr.clear();
            uint32_t _size30;
            ::apache::thrift::protocol::TType _ktype31;
            ::apache::thrift::protocol::TType _vtype32;
            xfer += iprot->readMapBegin(_ktype31, _vtype32, _size30);
            uint32_t _i34;
            for (_i34 = 0; _i34 < _size30; ++_i34)
            {
               ::starrocks::TPlanNodeId _key35;
              xfer += iprot->readI32(_key35);
               ::starrocks::TExpr& _val36 = this->plan_node_id_to_target_expr[_key35];
              xfer += _val36.read(iprot);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.plan_node_id_to_target_expr = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->has_remote_targets);
          this->__isset.has_remote_targets = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->bloom_filter_size);
          this->__isset.bloom_filter_size = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->runtime_filter_merge_nodes.clear();
            uint32_t _size37;
            ::apache::thrift::protocol::TType _etype40;
            xfer += iprot->readListBegin(_etype40, _size37);
            this->runtime_filter_merge_nodes.resize(_size37);
            uint32_t _i41;
            for (_i41 = 0; _i41 < _size37; ++_i41)
            {
              xfer += this->runtime_filter_merge_nodes[_i41].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.runtime_filter_merge_nodes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast42;
          xfer += iprot->readI32(ecast42);
          this->build_join_mode = static_cast<TRuntimeFilterBuildJoinMode::type>(ecast42);
          this->__isset.build_join_mode = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->sender_finst_id.read(iprot);
          this->__isset.sender_finst_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 11:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->build_plan_node_id);
          this->__isset.build_plan_node_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 12:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->broadcast_grf_senders.clear();
            uint32_t _size43;
            ::apache::thrift::protocol::TType _etype46;
            xfer += iprot->readListBegin(_etype46, _size43);
            this->broadcast_grf_senders.resize(_size43);
            uint32_t _i47;
            for (_i47 = 0; _i47 < _size43; ++_i47)
            {
              xfer += this->broadcast_grf_senders[_i47].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.broadcast_grf_senders = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 13:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->broadcast_grf_destinations.clear();
            uint32_t _size48;
            ::apache::thrift::protocol::TType _etype51;
            xfer += iprot->readListBegin(_etype51, _size48);
            this->broadcast_grf_destinations.resize(_size48);
            uint32_t _i52;
            for (_i52 = 0; _i52 < _size48; ++_i52)
            {
              xfer += this->broadcast_grf_destinations[_i52].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.broadcast_grf_destinations = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 14:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->bucketseq_to_instance.clear();
            uint32_t _size53;
            ::apache::thrift::protocol::TType _etype56;
            xfer += iprot->readListBegin(_etype56, _size53);
            this->bucketseq_to_instance.resize(_size53);
            uint32_t _i57;
            for (_i57 = 0; _i57 < _size53; ++_i57)
            {
              xfer += iprot->readI32(this->bucketseq_to_instance[_i57]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.bucketseq_to_instance = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 15:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->plan_node_id_to_partition_by_exprs.clear();
            uint32_t _size58;
            ::apache::thrift::protocol::TType _ktype59;
            ::apache::thrift::protocol::TType _vtype60;
            xfer += iprot->readMapBegin(_ktype59, _vtype60, _size58);
            uint32_t _i62;
            for (_i62 = 0; _i62 < _size58; ++_i62)
            {
               ::starrocks::TPlanNodeId _key63;
              xfer += iprot->readI32(_key63);
              std::vector< ::starrocks::TExpr> & _val64 = this->plan_node_id_to_partition_by_exprs[_key63];
              {
                _val64.clear();
                uint32_t _size65;
                ::apache::thrift::protocol::TType _etype68;
                xfer += iprot->readListBegin(_etype68, _size65);
                _val64.resize(_size65);
                uint32_t _i69;
                for (_i69 = 0; _i69 < _size65; ++_i69)
                {
                  xfer += _val64[_i69].read(iprot);
                }
                xfer += iprot->readListEnd();
              }
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.plan_node_id_to_partition_by_exprs = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 16:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast70;
          xfer += iprot->readI32(ecast70);
          this->filter_type = static_cast<TRuntimeFilterBuildType::type>(ecast70);
          this->__isset.filter_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 17:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->layout.read(iprot);
          this->__isset.layout = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 18:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->build_from_group_execution);
          this->__isset.build_from_group_execution = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TRuntimeFilterDescription::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TRuntimeFilterDescription");

  if (this->__isset.filter_id) {
    xfer += oprot->writeFieldBegin("filter_id", ::apache::thrift::protocol::T_I32, 1);
    xfer += oprot->writeI32(this->filter_id);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.build_expr) {
    xfer += oprot->writeFieldBegin("build_expr", ::apache::thrift::protocol::T_STRUCT, 2);
    xfer += this->build_expr.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.expr_order) {
    xfer += oprot->writeFieldBegin("expr_order", ::apache::thrift::protocol::T_I32, 3);
    xfer += oprot->writeI32(this->expr_order);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.plan_node_id_to_target_expr) {
    xfer += oprot->writeFieldBegin("plan_node_id_to_target_expr", ::apache::thrift::protocol::T_MAP, 4);
    {
      xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_I32, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->plan_node_id_to_target_expr.size()));
      std::map< ::starrocks::TPlanNodeId,  ::starrocks::TExpr> ::const_iterator _iter71;
      for (_iter71 = this->plan_node_id_to_target_expr.begin(); _iter71 != this->plan_node_id_to_target_expr.end(); ++_iter71)
      {
        xfer += oprot->writeI32(_iter71->first);
        xfer += _iter71->second.write(oprot);
      }
      xfer += oprot->writeMapEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.has_remote_targets) {
    xfer += oprot->writeFieldBegin("has_remote_targets", ::apache::thrift::protocol::T_BOOL, 6);
    xfer += oprot->writeBool(this->has_remote_targets);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.bloom_filter_size) {
    xfer += oprot->writeFieldBegin("bloom_filter_size", ::apache::thrift::protocol::T_I64, 7);
    xfer += oprot->writeI64(this->bloom_filter_size);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.runtime_filter_merge_nodes) {
    xfer += oprot->writeFieldBegin("runtime_filter_merge_nodes", ::apache::thrift::protocol::T_LIST, 8);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->runtime_filter_merge_nodes.size()));
      std::vector< ::starrocks::TNetworkAddress> ::const_iterator _iter72;
      for (_iter72 = this->runtime_filter_merge_nodes.begin(); _iter72 != this->runtime_filter_merge_nodes.end(); ++_iter72)
      {
        xfer += (*_iter72).write(oprot);
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.build_join_mode) {
    xfer += oprot->writeFieldBegin("build_join_mode", ::apache::thrift::protocol::T_I32, 9);
    xfer += oprot->writeI32(static_cast<int32_t>(this->build_join_mode));
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.sender_finst_id) {
    xfer += oprot->writeFieldBegin("sender_finst_id", ::apache::thrift::protocol::T_STRUCT, 10);
    xfer += this->sender_finst_id.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.build_plan_node_id) {
    xfer += oprot->writeFieldBegin("build_plan_node_id", ::apache::thrift::protocol::T_I32, 11);
    xfer += oprot->writeI32(this->build_plan_node_id);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.broadcast_grf_senders) {
    xfer += oprot->writeFieldBegin("broadcast_grf_senders", ::apache::thrift::protocol::T_LIST, 12);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->broadcast_grf_senders.size()));
      std::vector< ::starrocks::TUniqueId> ::const_iterator _iter73;
      for (_iter73 = this->broadcast_grf_senders.begin(); _iter73 != this->broadcast_grf_senders.end(); ++_iter73)
      {
        xfer += (*_iter73).write(oprot);
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.broadcast_grf_destinations) {
    xfer += oprot->writeFieldBegin("broadcast_grf_destinations", ::apache::thrift::protocol::T_LIST, 13);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->broadcast_grf_destinations.size()));
      std::vector<TRuntimeFilterDestination> ::const_iterator _iter74;
      for (_iter74 = this->broadcast_grf_destinations.begin(); _iter74 != this->broadcast_grf_destinations.end(); ++_iter74)
      {
        xfer += (*_iter74).write(oprot);
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.bucketseq_to_instance) {
    xfer += oprot->writeFieldBegin("bucketseq_to_instance", ::apache::thrift::protocol::T_LIST, 14);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->bucketseq_to_instance.size()));
      std::vector<int32_t> ::const_iterator _iter75;
      for (_iter75 = this->bucketseq_to_instance.begin(); _iter75 != this->bucketseq_to_instance.end(); ++_iter75)
      {
        xfer += oprot->writeI32((*_iter75));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.plan_node_id_to_partition_by_exprs) {
    xfer += oprot->writeFieldBegin("plan_node_id_to_partition_by_exprs", ::apache::thrift::protocol::T_MAP, 15);
    {
      xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_I32, ::apache::thrift::protocol::T_LIST, static_cast<uint32_t>(this->plan_node_id_to_partition_by_exprs.size()));
      std::map< ::starrocks::TPlanNodeId, std::vector< ::starrocks::TExpr> > ::const_iterator _iter76;
      for (_iter76 = this->plan_node_id_to_partition_by_exprs.begin(); _iter76 != this->plan_node_id_to_partition_by_exprs.end(); ++_iter76)
      {
        xfer += oprot->writeI32(_iter76->first);
        {
          xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(_iter76->second.size()));
          std::vector< ::starrocks::TExpr> ::const_iterator _iter77;
          for (_iter77 = _iter76->second.begin(); _iter77 != _iter76->second.end(); ++_iter77)
          {
            xfer += (*_iter77).write(oprot);
          }
          xfer += oprot->writeListEnd();
        }
      }
      xfer += oprot->writeMapEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.filter_type) {
    xfer += oprot->writeFieldBegin("filter_type", ::apache::thrift::protocol::T_I32, 16);
    xfer += oprot->writeI32(static_cast<int32_t>(this->filter_type));
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.layout) {
    xfer += oprot->writeFieldBegin("layout", ::apache::thrift::protocol::T_STRUCT, 17);
    xfer += this->layout.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.build_from_group_execution) {
    xfer += oprot->writeFieldBegin("build_from_group_execution", ::apache::thrift::protocol::T_BOOL, 18);
    xfer += oprot->writeBool(this->build_from_group_execution);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TRuntimeFilterDescription &a, TRuntimeFilterDescription &b) {
  using ::std::swap;
  swap(a.filter_id, b.filter_id);
  swap(a.build_expr, b.build_expr);
  swap(a.expr_order, b.expr_order);
  swap(a.plan_node_id_to_target_expr, b.plan_node_id_to_target_expr);
  swap(a.has_remote_targets, b.has_remote_targets);
  swap(a.bloom_filter_size, b.bloom_filter_size);
  swap(a.runtime_filter_merge_nodes, b.runtime_filter_merge_nodes);
  swap(a.build_join_mode, b.build_join_mode);
  swap(a.sender_finst_id, b.sender_finst_id);
  swap(a.build_plan_node_id, b.build_plan_node_id);
  swap(a.broadcast_grf_senders, b.broadcast_grf_senders);
  swap(a.broadcast_grf_destinations, b.broadcast_grf_destinations);
  swap(a.bucketseq_to_instance, b.bucketseq_to_instance);
  swap(a.plan_node_id_to_partition_by_exprs, b.plan_node_id_to_partition_by_exprs);
  swap(a.filter_type, b.filter_type);
  swap(a.layout, b.layout);
  swap(a.build_from_group_execution, b.build_from_group_execution);
  swap(a.__isset, b.__isset);
}

bool TRuntimeFilterDescription::operator==(const TRuntimeFilterDescription & rhs) const
{
  if (__isset.filter_id != rhs.__isset.filter_id)
    return false;
  else if (__isset.filter_id && !(filter_id == rhs.filter_id))
    return false;
  if (__isset.build_expr != rhs.__isset.build_expr)
    return false;
  else if (__isset.build_expr && !(build_expr == rhs.build_expr))
    return false;
  if (__isset.expr_order != rhs.__isset.expr_order)
    return false;
  else if (__isset.expr_order && !(expr_order == rhs.expr_order))
    return false;
  if (__isset.plan_node_id_to_target_expr != rhs.__isset.plan_node_id_to_target_expr)
    return false;
  else if (__isset.plan_node_id_to_target_expr && !(plan_node_id_to_target_expr == rhs.plan_node_id_to_target_expr))
    return false;
  if (__isset.has_remote_targets != rhs.__isset.has_remote_targets)
    return false;
  else if (__isset.has_remote_targets && !(has_remote_targets == rhs.has_remote_targets))
    return false;
  if (__isset.bloom_filter_size != rhs.__isset.bloom_filter_size)
    return false;
  else if (__isset.bloom_filter_size && !(bloom_filter_size == rhs.bloom_filter_size))
    return false;
  if (__isset.runtime_filter_merge_nodes != rhs.__isset.runtime_filter_merge_nodes)
    return false;
  else if (__isset.runtime_filter_merge_nodes && !(runtime_filter_merge_nodes == rhs.runtime_filter_merge_nodes))
    return false;
  if (__isset.build_join_mode != rhs.__isset.build_join_mode)
    return false;
  else if (__isset.build_join_mode && !(build_join_mode == rhs.build_join_mode))
    return false;
  if (__isset.sender_finst_id != rhs.__isset.sender_finst_id)
    return false;
  else if (__isset.sender_finst_id && !(sender_finst_id == rhs.sender_finst_id))
    return false;
  if (__isset.build_plan_node_id != rhs.__isset.build_plan_node_id)
    return false;
  else if (__isset.build_plan_node_id && !(build_plan_node_id == rhs.build_plan_node_id))
    return false;
  if (__isset.broadcast_grf_senders != rhs.__isset.broadcast_grf_senders)
    return false;
  else if (__isset.broadcast_grf_senders && !(broadcast_grf_senders == rhs.broadcast_grf_senders))
    return false;
  if (__isset.broadcast_grf_destinations != rhs.__isset.broadcast_grf_destinations)
    return false;
  else if (__isset.broadcast_grf_destinations && !(broadcast_grf_destinations == rhs.broadcast_grf_destinations))
    return false;
  if (__isset.bucketseq_to_instance != rhs.__isset.bucketseq_to_instance)
    return false;
  else if (__isset.bucketseq_to_instance && !(bucketseq_to_instance == rhs.bucketseq_to_instance))
    return false;
  if (__isset.plan_node_id_to_partition_by_exprs != rhs.__isset.plan_node_id_to_partition_by_exprs)
    return false;
  else if (__isset.plan_node_id_to_partition_by_exprs && !(plan_node_id_to_partition_by_exprs == rhs.plan_node_id_to_partition_by_exprs))
    return false;
  if (__isset.filter_type != rhs.__isset.filter_type)
    return false;
  else if (__isset.filter_type && !(filter_type == rhs.filter_type))
    return false;
  if (__isset.layout != rhs.__isset.layout)
    return false;
  else if (__isset.layout && !(layout == rhs.layout))
    return false;
  if (__isset.build_from_group_execution != rhs.__isset.build_from_group_execution)
    return false;
  else if (__isset.build_from_group_execution && !(build_from_group_execution == rhs.build_from_group_execution))
    return false;
  return true;
}

TRuntimeFilterDescription::TRuntimeFilterDescription(const TRuntimeFilterDescription& other78) {
  filter_id = other78.filter_id;
  build_expr = other78.build_expr;
  expr_order = other78.expr_order;
  plan_node_id_to_target_expr = other78.plan_node_id_to_target_expr;
  has_remote_targets = other78.has_remote_targets;
  bloom_filter_size = other78.bloom_filter_size;
  runtime_filter_merge_nodes = other78.runtime_filter_merge_nodes;
  build_join_mode = other78.build_join_mode;
  sender_finst_id = other78.sender_finst_id;
  build_plan_node_id = other78.build_plan_node_id;
  broadcast_grf_senders = other78.broadcast_grf_senders;
  broadcast_grf_destinations = other78.broadcast_grf_destinations;
  bucketseq_to_instance = other78.bucketseq_to_instance;
  plan_node_id_to_partition_by_exprs = other78.plan_node_id_to_partition_by_exprs;
  filter_type = other78.filter_type;
  layout = other78.layout;
  build_from_group_execution = other78.build_from_group_execution;
  __isset = other78.__isset;
}
TRuntimeFilterDescription& TRuntimeFilterDescription::operator=(const TRuntimeFilterDescription& other79) {
  filter_id = other79.filter_id;
  build_expr = other79.build_expr;
  expr_order = other79.expr_order;
  plan_node_id_to_target_expr = other79.plan_node_id_to_target_expr;
  has_remote_targets = other79.has_remote_targets;
  bloom_filter_size = other79.bloom_filter_size;
  runtime_filter_merge_nodes = other79.runtime_filter_merge_nodes;
  build_join_mode = other79.build_join_mode;
  sender_finst_id = other79.sender_finst_id;
  build_plan_node_id = other79.build_plan_node_id;
  broadcast_grf_senders = other79.broadcast_grf_senders;
  broadcast_grf_destinations = other79.broadcast_grf_destinations;
  bucketseq_to_instance = other79.bucketseq_to_instance;
  plan_node_id_to_partition_by_exprs = other79.plan_node_id_to_partition_by_exprs;
  filter_type = other79.filter_type;
  layout = other79.layout;
  build_from_group_execution = other79.build_from_group_execution;
  __isset = other79.__isset;
  return *this;
}
void TRuntimeFilterDescription::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TRuntimeFilterDescription(";
  out << "filter_id="; (__isset.filter_id ? (out << to_string(filter_id)) : (out << "<null>"));
  out << ", " << "build_expr="; (__isset.build_expr ? (out << to_string(build_expr)) : (out << "<null>"));
  out << ", " << "expr_order="; (__isset.expr_order ? (out << to_string(expr_order)) : (out << "<null>"));
  out << ", " << "plan_node_id_to_target_expr="; (__isset.plan_node_id_to_target_expr ? (out << to_string(plan_node_id_to_target_expr)) : (out << "<null>"));
  out << ", " << "has_remote_targets="; (__isset.has_remote_targets ? (out << to_string(has_remote_targets)) : (out << "<null>"));
  out << ", " << "bloom_filter_size="; (__isset.bloom_filter_size ? (out << to_string(bloom_filter_size)) : (out << "<null>"));
  out << ", " << "runtime_filter_merge_nodes="; (__isset.runtime_filter_merge_nodes ? (out << to_string(runtime_filter_merge_nodes)) : (out << "<null>"));
  out << ", " << "build_join_mode="; (__isset.build_join_mode ? (out << to_string(build_join_mode)) : (out << "<null>"));
  out << ", " << "sender_finst_id="; (__isset.sender_finst_id ? (out << to_string(sender_finst_id)) : (out << "<null>"));
  out << ", " << "build_plan_node_id="; (__isset.build_plan_node_id ? (out << to_string(build_plan_node_id)) : (out << "<null>"));
  out << ", " << "broadcast_grf_senders="; (__isset.broadcast_grf_senders ? (out << to_string(broadcast_grf_senders)) : (out << "<null>"));
  out << ", " << "broadcast_grf_destinations="; (__isset.broadcast_grf_destinations ? (out << to_string(broadcast_grf_destinations)) : (out << "<null>"));
  out << ", " << "bucketseq_to_instance="; (__isset.bucketseq_to_instance ? (out << to_string(bucketseq_to_instance)) : (out << "<null>"));
  out << ", " << "plan_node_id_to_partition_by_exprs="; (__isset.plan_node_id_to_partition_by_exprs ? (out << to_string(plan_node_id_to_partition_by_exprs)) : (out << "<null>"));
  out << ", " << "filter_type="; (__isset.filter_type ? (out << to_string(filter_type)) : (out << "<null>"));
  out << ", " << "layout="; (__isset.layout ? (out << to_string(layout)) : (out << "<null>"));
  out << ", " << "build_from_group_execution="; (__isset.build_from_group_execution ? (out << to_string(build_from_group_execution)) : (out << "<null>"));
  out << ")";
}


TRuntimeFilterProberParams::~TRuntimeFilterProberParams() noexcept {
}

TRuntimeFilterProberParams::TRuntimeFilterProberParams() noexcept {
}

void TRuntimeFilterProberParams::__set_fragment_instance_id(const  ::starrocks::TUniqueId& val) {
  this->fragment_instance_id = val;
__isset.fragment_instance_id = true;
}

void TRuntimeFilterProberParams::__set_fragment_instance_address(const  ::starrocks::TNetworkAddress& val) {
  this->fragment_instance_address = val;
__isset.fragment_instance_address = true;
}
std::ostream& operator<<(std::ostream& out, const TRuntimeFilterProberParams& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TRuntimeFilterProberParams::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->fragment_instance_id.read(iprot);
          this->__isset.fragment_instance_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->fragment_instance_address.read(iprot);
          this->__isset.fragment_instance_address = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TRuntimeFilterProberParams::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TRuntimeFilterProberParams");

  if (this->__isset.fragment_instance_id) {
    xfer += oprot->writeFieldBegin("fragment_instance_id", ::apache::thrift::protocol::T_STRUCT, 1);
    xfer += this->fragment_instance_id.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.fragment_instance_address) {
    xfer += oprot->writeFieldBegin("fragment_instance_address", ::apache::thrift::protocol::T_STRUCT, 2);
    xfer += this->fragment_instance_address.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TRuntimeFilterProberParams &a, TRuntimeFilterProberParams &b) {
  using ::std::swap;
  swap(a.fragment_instance_id, b.fragment_instance_id);
  swap(a.fragment_instance_address, b.fragment_instance_address);
  swap(a.__isset, b.__isset);
}

bool TRuntimeFilterProberParams::operator==(const TRuntimeFilterProberParams & rhs) const
{
  if (__isset.fragment_instance_id != rhs.__isset.fragment_instance_id)
    return false;
  else if (__isset.fragment_instance_id && !(fragment_instance_id == rhs.fragment_instance_id))
    return false;
  if (__isset.fragment_instance_address != rhs.__isset.fragment_instance_address)
    return false;
  else if (__isset.fragment_instance_address && !(fragment_instance_address == rhs.fragment_instance_address))
    return false;
  return true;
}

TRuntimeFilterProberParams::TRuntimeFilterProberParams(const TRuntimeFilterProberParams& other80) {
  fragment_instance_id = other80.fragment_instance_id;
  fragment_instance_address = other80.fragment_instance_address;
  __isset = other80.__isset;
}
TRuntimeFilterProberParams& TRuntimeFilterProberParams::operator=(const TRuntimeFilterProberParams& other81) {
  fragment_instance_id = other81.fragment_instance_id;
  fragment_instance_address = other81.fragment_instance_address;
  __isset = other81.__isset;
  return *this;
}
void TRuntimeFilterProberParams::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TRuntimeFilterProberParams(";
  out << "fragment_instance_id="; (__isset.fragment_instance_id ? (out << to_string(fragment_instance_id)) : (out << "<null>"));
  out << ", " << "fragment_instance_address="; (__isset.fragment_instance_address ? (out << to_string(fragment_instance_address)) : (out << "<null>"));
  out << ")";
}


TRuntimeFilterParams::~TRuntimeFilterParams() noexcept {
}

TRuntimeFilterParams::TRuntimeFilterParams() noexcept
   : runtime_filter_max_size(0) {
}

void TRuntimeFilterParams::__set_id_to_prober_params(const std::map<int32_t, std::vector<TRuntimeFilterProberParams> > & val) {
  this->id_to_prober_params = val;
__isset.id_to_prober_params = true;
}

void TRuntimeFilterParams::__set_runtime_filter_builder_number(const std::map<int32_t, int32_t> & val) {
  this->runtime_filter_builder_number = val;
__isset.runtime_filter_builder_number = true;
}

void TRuntimeFilterParams::__set_runtime_filter_max_size(const int64_t val) {
  this->runtime_filter_max_size = val;
__isset.runtime_filter_max_size = true;
}
std::ostream& operator<<(std::ostream& out, const TRuntimeFilterParams& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TRuntimeFilterParams::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 2:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->id_to_prober_params.clear();
            uint32_t _size82;
            ::apache::thrift::protocol::TType _ktype83;
            ::apache::thrift::protocol::TType _vtype84;
            xfer += iprot->readMapBegin(_ktype83, _vtype84, _size82);
            uint32_t _i86;
            for (_i86 = 0; _i86 < _size82; ++_i86)
            {
              int32_t _key87;
              xfer += iprot->readI32(_key87);
              std::vector<TRuntimeFilterProberParams> & _val88 = this->id_to_prober_params[_key87];
              {
                _val88.clear();
                uint32_t _size89;
                ::apache::thrift::protocol::TType _etype92;
                xfer += iprot->readListBegin(_etype92, _size89);
                _val88.resize(_size89);
                uint32_t _i93;
                for (_i93 = 0; _i93 < _size89; ++_i93)
                {
                  xfer += _val88[_i93].read(iprot);
                }
                xfer += iprot->readListEnd();
              }
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.id_to_prober_params = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->runtime_filter_builder_number.clear();
            uint32_t _size94;
            ::apache::thrift::protocol::TType _ktype95;
            ::apache::thrift::protocol::TType _vtype96;
            xfer += iprot->readMapBegin(_ktype95, _vtype96, _size94);
            uint32_t _i98;
            for (_i98 = 0; _i98 < _size94; ++_i98)
            {
              int32_t _key99;
              xfer += iprot->readI32(_key99);
              int32_t& _val100 = this->runtime_filter_builder_number[_key99];
              xfer += iprot->readI32(_val100);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.runtime_filter_builder_number = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->runtime_filter_max_size);
          this->__isset.runtime_filter_max_size = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TRuntimeFilterParams::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TRuntimeFilterParams");

  if (this->__isset.id_to_prober_params) {
    xfer += oprot->writeFieldBegin("id_to_prober_params", ::apache::thrift::protocol::T_MAP, 2);
    {
      xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_I32, ::apache::thrift::protocol::T_LIST, static_cast<uint32_t>(this->id_to_prober_params.size()));
      std::map<int32_t, std::vector<TRuntimeFilterProberParams> > ::const_iterator _iter101;
      for (_iter101 = this->id_to_prober_params.begin(); _iter101 != this->id_to_prober_params.end(); ++_iter101)
      {
        xfer += oprot->writeI32(_iter101->first);
        {
          xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(_iter101->second.size()));
          std::vector<TRuntimeFilterProberParams> ::const_iterator _iter102;
          for (_iter102 = _iter101->second.begin(); _iter102 != _iter101->second.end(); ++_iter102)
          {
            xfer += (*_iter102).write(oprot);
          }
          xfer += oprot->writeListEnd();
        }
      }
      xfer += oprot->writeMapEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.runtime_filter_builder_number) {
    xfer += oprot->writeFieldBegin("runtime_filter_builder_number", ::apache::thrift::protocol::T_MAP, 3);
    {
      xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_I32, ::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->runtime_filter_builder_number.size()));
      std::map<int32_t, int32_t> ::const_iterator _iter103;
      for (_iter103 = this->runtime_filter_builder_number.begin(); _iter103 != this->runtime_filter_builder_number.end(); ++_iter103)
      {
        xfer += oprot->writeI32(_iter103->first);
        xfer += oprot->writeI32(_iter103->second);
      }
      xfer += oprot->writeMapEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.runtime_filter_max_size) {
    xfer += oprot->writeFieldBegin("runtime_filter_max_size", ::apache::thrift::protocol::T_I64, 4);
    xfer += oprot->writeI64(this->runtime_filter_max_size);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TRuntimeFilterParams &a, TRuntimeFilterParams &b) {
  using ::std::swap;
  swap(a.id_to_prober_params, b.id_to_prober_params);
  swap(a.runtime_filter_builder_number, b.runtime_filter_builder_number);
  swap(a.runtime_filter_max_size, b.runtime_filter_max_size);
  swap(a.__isset, b.__isset);
}

bool TRuntimeFilterParams::operator==(const TRuntimeFilterParams & rhs) const
{
  if (__isset.id_to_prober_params != rhs.__isset.id_to_prober_params)
    return false;
  else if (__isset.id_to_prober_params && !(id_to_prober_params == rhs.id_to_prober_params))
    return false;
  if (__isset.runtime_filter_builder_number != rhs.__isset.runtime_filter_builder_number)
    return false;
  else if (__isset.runtime_filter_builder_number && !(runtime_filter_builder_number == rhs.runtime_filter_builder_number))
    return false;
  if (__isset.runtime_filter_max_size != rhs.__isset.runtime_filter_max_size)
    return false;
  else if (__isset.runtime_filter_max_size && !(runtime_filter_max_size == rhs.runtime_filter_max_size))
    return false;
  return true;
}

TRuntimeFilterParams::TRuntimeFilterParams(const TRuntimeFilterParams& other104) {
  id_to_prober_params = other104.id_to_prober_params;
  runtime_filter_builder_number = other104.runtime_filter_builder_number;
  runtime_filter_max_size = other104.runtime_filter_max_size;
  __isset = other104.__isset;
}
TRuntimeFilterParams& TRuntimeFilterParams::operator=(const TRuntimeFilterParams& other105) {
  id_to_prober_params = other105.id_to_prober_params;
  runtime_filter_builder_number = other105.runtime_filter_builder_number;
  runtime_filter_max_size = other105.runtime_filter_max_size;
  __isset = other105.__isset;
  return *this;
}
void TRuntimeFilterParams::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TRuntimeFilterParams(";
  out << "id_to_prober_params="; (__isset.id_to_prober_params ? (out << to_string(id_to_prober_params)) : (out << "<null>"));
  out << ", " << "runtime_filter_builder_number="; (__isset.runtime_filter_builder_number ? (out << to_string(runtime_filter_builder_number)) : (out << "<null>"));
  out << ", " << "runtime_filter_max_size="; (__isset.runtime_filter_max_size ? (out << to_string(runtime_filter_max_size)) : (out << "<null>"));
  out << ")";
}

} // namespace
