/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RuntimeProfile_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace starrocks {

int _kTCounterAggregateTypeValues[] = {
  TCounterAggregateType::SUM,
  TCounterAggregateType::AVG,
  TCounterAggregateType::SUM_AVG,
  TCounterAggregateType::AVG_SUM
};
const char* _kTCounterAggregateTypeNames[] = {
  "SUM",
  "AVG",
  "SUM_AVG",
  "AVG_SUM"
};
const std::map<int, const char*> _TCounterAggregateType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kTCounterAggregateTypeValues, _kTCounterAggregateTypeNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const TCounterAggregateType::type& val) {
  std::map<int, const char*>::const_iterator it = _TCounterAggregateType_VALUES_TO_NAMES.find(val);
  if (it != _TCounterAggregateType_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const TCounterAggregateType::type& val) {
  std::map<int, const char*>::const_iterator it = _TCounterAggregateType_VALUES_TO_NAMES.find(val);
  if (it != _TCounterAggregateType_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kTCounterMergeTypeValues[] = {
  TCounterMergeType::MERGE_ALL,
  TCounterMergeType::SKIP_ALL,
  TCounterMergeType::SKIP_FIRST_MERGE,
  TCounterMergeType::SKIP_SECOND_MERGE
};
const char* _kTCounterMergeTypeNames[] = {
  "MERGE_ALL",
  "SKIP_ALL",
  "SKIP_FIRST_MERGE",
  "SKIP_SECOND_MERGE"
};
const std::map<int, const char*> _TCounterMergeType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kTCounterMergeTypeValues, _kTCounterMergeTypeNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const TCounterMergeType::type& val) {
  std::map<int, const char*>::const_iterator it = _TCounterMergeType_VALUES_TO_NAMES.find(val);
  if (it != _TCounterMergeType_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const TCounterMergeType::type& val) {
  std::map<int, const char*>::const_iterator it = _TCounterMergeType_VALUES_TO_NAMES.find(val);
  if (it != _TCounterMergeType_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kTCounterMinMaxTypeValues[] = {
  TCounterMinMaxType::MIN_MAX_ALL,
  TCounterMinMaxType::SKIP_ALL
};
const char* _kTCounterMinMaxTypeNames[] = {
  "MIN_MAX_ALL",
  "SKIP_ALL"
};
const std::map<int, const char*> _TCounterMinMaxType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(2, _kTCounterMinMaxTypeValues, _kTCounterMinMaxTypeNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const TCounterMinMaxType::type& val) {
  std::map<int, const char*>::const_iterator it = _TCounterMinMaxType_VALUES_TO_NAMES.find(val);
  if (it != _TCounterMinMaxType_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const TCounterMinMaxType::type& val) {
  std::map<int, const char*>::const_iterator it = _TCounterMinMaxType_VALUES_TO_NAMES.find(val);
  if (it != _TCounterMinMaxType_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


TCounterStrategy::~TCounterStrategy() noexcept {
}

TCounterStrategy::TCounterStrategy() noexcept
   : aggregate_type(static_cast<TCounterAggregateType::type>(0)),
     merge_type(static_cast<TCounterMergeType::type>(0)),
     display_threshold(0LL),
     min_max_type(static_cast<TCounterMinMaxType::type>(0)) {
}

void TCounterStrategy::__set_aggregate_type(const TCounterAggregateType::type val) {
  this->aggregate_type = val;
}

void TCounterStrategy::__set_merge_type(const TCounterMergeType::type val) {
  this->merge_type = val;
}

void TCounterStrategy::__set_display_threshold(const int64_t val) {
  this->display_threshold = val;
}

void TCounterStrategy::__set_min_max_type(const TCounterMinMaxType::type val) {
  this->min_max_type = val;
__isset.min_max_type = true;
}
std::ostream& operator<<(std::ostream& out, const TCounterStrategy& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TCounterStrategy::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_aggregate_type = false;
  bool isset_merge_type = false;
  bool isset_display_threshold = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast0;
          xfer += iprot->readI32(ecast0);
          this->aggregate_type = static_cast<TCounterAggregateType::type>(ecast0);
          isset_aggregate_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast1;
          xfer += iprot->readI32(ecast1);
          this->merge_type = static_cast<TCounterMergeType::type>(ecast1);
          isset_merge_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->display_threshold);
          isset_display_threshold = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast2;
          xfer += iprot->readI32(ecast2);
          this->min_max_type = static_cast<TCounterMinMaxType::type>(ecast2);
          this->__isset.min_max_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_aggregate_type)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_merge_type)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_display_threshold)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TCounterStrategy::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TCounterStrategy");

  xfer += oprot->writeFieldBegin("aggregate_type", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(static_cast<int32_t>(this->aggregate_type));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("merge_type", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(static_cast<int32_t>(this->merge_type));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("display_threshold", ::apache::thrift::protocol::T_I64, 3);
  xfer += oprot->writeI64(this->display_threshold);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.min_max_type) {
    xfer += oprot->writeFieldBegin("min_max_type", ::apache::thrift::protocol::T_I32, 4);
    xfer += oprot->writeI32(static_cast<int32_t>(this->min_max_type));
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TCounterStrategy &a, TCounterStrategy &b) {
  using ::std::swap;
  swap(a.aggregate_type, b.aggregate_type);
  swap(a.merge_type, b.merge_type);
  swap(a.display_threshold, b.display_threshold);
  swap(a.min_max_type, b.min_max_type);
  swap(a.__isset, b.__isset);
}

bool TCounterStrategy::operator==(const TCounterStrategy & rhs) const
{
  if (!(aggregate_type == rhs.aggregate_type))
    return false;
  if (!(merge_type == rhs.merge_type))
    return false;
  if (!(display_threshold == rhs.display_threshold))
    return false;
  if (__isset.min_max_type != rhs.__isset.min_max_type)
    return false;
  else if (__isset.min_max_type && !(min_max_type == rhs.min_max_type))
    return false;
  return true;
}

TCounterStrategy::TCounterStrategy(const TCounterStrategy& other3) noexcept {
  aggregate_type = other3.aggregate_type;
  merge_type = other3.merge_type;
  display_threshold = other3.display_threshold;
  min_max_type = other3.min_max_type;
  __isset = other3.__isset;
}
TCounterStrategy& TCounterStrategy::operator=(const TCounterStrategy& other4) noexcept {
  aggregate_type = other4.aggregate_type;
  merge_type = other4.merge_type;
  display_threshold = other4.display_threshold;
  min_max_type = other4.min_max_type;
  __isset = other4.__isset;
  return *this;
}
void TCounterStrategy::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TCounterStrategy(";
  out << "aggregate_type=" << to_string(aggregate_type);
  out << ", " << "merge_type=" << to_string(merge_type);
  out << ", " << "display_threshold=" << to_string(display_threshold);
  out << ", " << "min_max_type="; (__isset.min_max_type ? (out << to_string(min_max_type)) : (out << "<null>"));
  out << ")";
}


TCounter::~TCounter() noexcept {
}

TCounter::TCounter() noexcept
   : name(),
     type(static_cast< ::starrocks::TUnit::type>(0)),
     value(0) {
}

void TCounter::__set_name(const std::string& val) {
  this->name = val;
}

void TCounter::__set_type(const  ::starrocks::TUnit::type val) {
  this->type = val;
}

void TCounter::__set_value(const int64_t val) {
  this->value = val;
}

void TCounter::__set_strategy(const TCounterStrategy& val) {
  this->strategy = val;
__isset.strategy = true;
}
std::ostream& operator<<(std::ostream& out, const TCounter& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TCounter::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_name = false;
  bool isset_type = false;
  bool isset_value = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          isset_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast5;
          xfer += iprot->readI32(ecast5);
          this->type = static_cast< ::starrocks::TUnit::type>(ecast5);
          isset_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->value);
          isset_value = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->strategy.read(iprot);
          this->__isset.strategy = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_name)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_type)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_value)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TCounter::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TCounter");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(static_cast<int32_t>(this->type));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("value", ::apache::thrift::protocol::T_I64, 3);
  xfer += oprot->writeI64(this->value);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.strategy) {
    xfer += oprot->writeFieldBegin("strategy", ::apache::thrift::protocol::T_STRUCT, 5);
    xfer += this->strategy.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TCounter &a, TCounter &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.type, b.type);
  swap(a.value, b.value);
  swap(a.strategy, b.strategy);
  swap(a.__isset, b.__isset);
}

bool TCounter::operator==(const TCounter & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(type == rhs.type))
    return false;
  if (!(value == rhs.value))
    return false;
  if (__isset.strategy != rhs.__isset.strategy)
    return false;
  else if (__isset.strategy && !(strategy == rhs.strategy))
    return false;
  return true;
}

TCounter::TCounter(const TCounter& other6) {
  name = other6.name;
  type = other6.type;
  value = other6.value;
  strategy = other6.strategy;
  __isset = other6.__isset;
}
TCounter& TCounter::operator=(const TCounter& other7) {
  name = other7.name;
  type = other7.type;
  value = other7.value;
  strategy = other7.strategy;
  __isset = other7.__isset;
  return *this;
}
void TCounter::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TCounter(";
  out << "name=" << to_string(name);
  out << ", " << "type=" << to_string(type);
  out << ", " << "value=" << to_string(value);
  out << ", " << "strategy="; (__isset.strategy ? (out << to_string(strategy)) : (out << "<null>"));
  out << ")";
}


TRuntimeProfileNode::~TRuntimeProfileNode() noexcept {
}

TRuntimeProfileNode::TRuntimeProfileNode() noexcept
   : name(),
     num_children(0),
     metadata(0),
     indent(0),
     version(0) {
}

void TRuntimeProfileNode::__set_name(const std::string& val) {
  this->name = val;
}

void TRuntimeProfileNode::__set_num_children(const int32_t val) {
  this->num_children = val;
}

void TRuntimeProfileNode::__set_counters(const std::vector<TCounter> & val) {
  this->counters = val;
}

void TRuntimeProfileNode::__set_metadata(const int64_t val) {
  this->metadata = val;
}

void TRuntimeProfileNode::__set_indent(const bool val) {
  this->indent = val;
}

void TRuntimeProfileNode::__set_info_strings(const std::map<std::string, std::string> & val) {
  this->info_strings = val;
}

void TRuntimeProfileNode::__set_info_strings_display_order(const std::vector<std::string> & val) {
  this->info_strings_display_order = val;
}

void TRuntimeProfileNode::__set_child_counters_map(const std::map<std::string, std::set<std::string> > & val) {
  this->child_counters_map = val;
}

void TRuntimeProfileNode::__set_version(const int64_t val) {
  this->version = val;
__isset.version = true;
}
std::ostream& operator<<(std::ostream& out, const TRuntimeProfileNode& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TRuntimeProfileNode::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_name = false;
  bool isset_num_children = false;
  bool isset_counters = false;
  bool isset_metadata = false;
  bool isset_indent = false;
  bool isset_info_strings = false;
  bool isset_info_strings_display_order = false;
  bool isset_child_counters_map = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          isset_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->num_children);
          isset_num_children = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->counters.clear();
            uint32_t _size8;
            ::apache::thrift::protocol::TType _etype11;
            xfer += iprot->readListBegin(_etype11, _size8);
            this->counters.resize(_size8);
            uint32_t _i12;
            for (_i12 = 0; _i12 < _size8; ++_i12)
            {
              xfer += this->counters[_i12].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          isset_counters = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->metadata);
          isset_metadata = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->indent);
          isset_indent = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->info_strings.clear();
            uint32_t _size13;
            ::apache::thrift::protocol::TType _ktype14;
            ::apache::thrift::protocol::TType _vtype15;
            xfer += iprot->readMapBegin(_ktype14, _vtype15, _size13);
            uint32_t _i17;
            for (_i17 = 0; _i17 < _size13; ++_i17)
            {
              std::string _key18;
              xfer += iprot->readString(_key18);
              std::string& _val19 = this->info_strings[_key18];
              xfer += iprot->readString(_val19);
            }
            xfer += iprot->readMapEnd();
          }
          isset_info_strings = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->info_strings_display_order.clear();
            uint32_t _size20;
            ::apache::thrift::protocol::TType _etype23;
            xfer += iprot->readListBegin(_etype23, _size20);
            this->info_strings_display_order.resize(_size20);
            uint32_t _i24;
            for (_i24 = 0; _i24 < _size20; ++_i24)
            {
              xfer += iprot->readString(this->info_strings_display_order[_i24]);
            }
            xfer += iprot->readListEnd();
          }
          isset_info_strings_display_order = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->child_counters_map.clear();
            uint32_t _size25;
            ::apache::thrift::protocol::TType _ktype26;
            ::apache::thrift::protocol::TType _vtype27;
            xfer += iprot->readMapBegin(_ktype26, _vtype27, _size25);
            uint32_t _i29;
            for (_i29 = 0; _i29 < _size25; ++_i29)
            {
              std::string _key30;
              xfer += iprot->readString(_key30);
              std::set<std::string> & _val31 = this->child_counters_map[_key30];
              {
                _val31.clear();
                uint32_t _size32;
                ::apache::thrift::protocol::TType _etype35;
                xfer += iprot->readSetBegin(_etype35, _size32);
                uint32_t _i36;
                for (_i36 = 0; _i36 < _size32; ++_i36)
                {
                  std::string _elem37;
                  xfer += iprot->readString(_elem37);
                  _val31.insert(_elem37);
                }
                xfer += iprot->readSetEnd();
              }
            }
            xfer += iprot->readMapEnd();
          }
          isset_child_counters_map = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->version);
          this->__isset.version = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_name)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_num_children)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_counters)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_metadata)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_indent)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_info_strings)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_info_strings_display_order)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_child_counters_map)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TRuntimeProfileNode::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TRuntimeProfileNode");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("num_children", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->num_children);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("counters", ::apache::thrift::protocol::T_LIST, 3);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->counters.size()));
    std::vector<TCounter> ::const_iterator _iter38;
    for (_iter38 = this->counters.begin(); _iter38 != this->counters.end(); ++_iter38)
    {
      xfer += (*_iter38).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("metadata", ::apache::thrift::protocol::T_I64, 4);
  xfer += oprot->writeI64(this->metadata);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("indent", ::apache::thrift::protocol::T_BOOL, 5);
  xfer += oprot->writeBool(this->indent);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("info_strings", ::apache::thrift::protocol::T_MAP, 6);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->info_strings.size()));
    std::map<std::string, std::string> ::const_iterator _iter39;
    for (_iter39 = this->info_strings.begin(); _iter39 != this->info_strings.end(); ++_iter39)
    {
      xfer += oprot->writeString(_iter39->first);
      xfer += oprot->writeString(_iter39->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("info_strings_display_order", ::apache::thrift::protocol::T_LIST, 7);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->info_strings_display_order.size()));
    std::vector<std::string> ::const_iterator _iter40;
    for (_iter40 = this->info_strings_display_order.begin(); _iter40 != this->info_strings_display_order.end(); ++_iter40)
    {
      xfer += oprot->writeString((*_iter40));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("child_counters_map", ::apache::thrift::protocol::T_MAP, 8);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_SET, static_cast<uint32_t>(this->child_counters_map.size()));
    std::map<std::string, std::set<std::string> > ::const_iterator _iter41;
    for (_iter41 = this->child_counters_map.begin(); _iter41 != this->child_counters_map.end(); ++_iter41)
    {
      xfer += oprot->writeString(_iter41->first);
      {
        xfer += oprot->writeSetBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(_iter41->second.size()));
        std::set<std::string> ::const_iterator _iter42;
        for (_iter42 = _iter41->second.begin(); _iter42 != _iter41->second.end(); ++_iter42)
        {
          xfer += oprot->writeString((*_iter42));
        }
        xfer += oprot->writeSetEnd();
      }
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  if (this->__isset.version) {
    xfer += oprot->writeFieldBegin("version", ::apache::thrift::protocol::T_I64, 9);
    xfer += oprot->writeI64(this->version);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TRuntimeProfileNode &a, TRuntimeProfileNode &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.num_children, b.num_children);
  swap(a.counters, b.counters);
  swap(a.metadata, b.metadata);
  swap(a.indent, b.indent);
  swap(a.info_strings, b.info_strings);
  swap(a.info_strings_display_order, b.info_strings_display_order);
  swap(a.child_counters_map, b.child_counters_map);
  swap(a.version, b.version);
  swap(a.__isset, b.__isset);
}

bool TRuntimeProfileNode::operator==(const TRuntimeProfileNode & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(num_children == rhs.num_children))
    return false;
  if (!(counters == rhs.counters))
    return false;
  if (!(metadata == rhs.metadata))
    return false;
  if (!(indent == rhs.indent))
    return false;
  if (!(info_strings == rhs.info_strings))
    return false;
  if (!(info_strings_display_order == rhs.info_strings_display_order))
    return false;
  if (!(child_counters_map == rhs.child_counters_map))
    return false;
  if (__isset.version != rhs.__isset.version)
    return false;
  else if (__isset.version && !(version == rhs.version))
    return false;
  return true;
}

TRuntimeProfileNode::TRuntimeProfileNode(const TRuntimeProfileNode& other43) {
  name = other43.name;
  num_children = other43.num_children;
  counters = other43.counters;
  metadata = other43.metadata;
  indent = other43.indent;
  info_strings = other43.info_strings;
  info_strings_display_order = other43.info_strings_display_order;
  child_counters_map = other43.child_counters_map;
  version = other43.version;
  __isset = other43.__isset;
}
TRuntimeProfileNode& TRuntimeProfileNode::operator=(const TRuntimeProfileNode& other44) {
  name = other44.name;
  num_children = other44.num_children;
  counters = other44.counters;
  metadata = other44.metadata;
  indent = other44.indent;
  info_strings = other44.info_strings;
  info_strings_display_order = other44.info_strings_display_order;
  child_counters_map = other44.child_counters_map;
  version = other44.version;
  __isset = other44.__isset;
  return *this;
}
void TRuntimeProfileNode::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TRuntimeProfileNode(";
  out << "name=" << to_string(name);
  out << ", " << "num_children=" << to_string(num_children);
  out << ", " << "counters=" << to_string(counters);
  out << ", " << "metadata=" << to_string(metadata);
  out << ", " << "indent=" << to_string(indent);
  out << ", " << "info_strings=" << to_string(info_strings);
  out << ", " << "info_strings_display_order=" << to_string(info_strings_display_order);
  out << ", " << "child_counters_map=" << to_string(child_counters_map);
  out << ", " << "version="; (__isset.version ? (out << to_string(version)) : (out << "<null>"));
  out << ")";
}


TRuntimeProfileTree::~TRuntimeProfileTree() noexcept {
}

TRuntimeProfileTree::TRuntimeProfileTree() noexcept {
}

void TRuntimeProfileTree::__set_nodes(const std::vector<TRuntimeProfileNode> & val) {
  this->nodes = val;
}
std::ostream& operator<<(std::ostream& out, const TRuntimeProfileTree& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TRuntimeProfileTree::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_nodes = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->nodes.clear();
            uint32_t _size45;
            ::apache::thrift::protocol::TType _etype48;
            xfer += iprot->readListBegin(_etype48, _size45);
            this->nodes.resize(_size45);
            uint32_t _i49;
            for (_i49 = 0; _i49 < _size45; ++_i49)
            {
              xfer += this->nodes[_i49].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          isset_nodes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_nodes)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TRuntimeProfileTree::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TRuntimeProfileTree");

  xfer += oprot->writeFieldBegin("nodes", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->nodes.size()));
    std::vector<TRuntimeProfileNode> ::const_iterator _iter50;
    for (_iter50 = this->nodes.begin(); _iter50 != this->nodes.end(); ++_iter50)
    {
      xfer += (*_iter50).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TRuntimeProfileTree &a, TRuntimeProfileTree &b) {
  using ::std::swap;
  swap(a.nodes, b.nodes);
}

bool TRuntimeProfileTree::operator==(const TRuntimeProfileTree & rhs) const
{
  if (!(nodes == rhs.nodes))
    return false;
  return true;
}

TRuntimeProfileTree::TRuntimeProfileTree(const TRuntimeProfileTree& other51) {
  nodes = other51.nodes;
}
TRuntimeProfileTree& TRuntimeProfileTree::operator=(const TRuntimeProfileTree& other52) {
  nodes = other52.nodes;
  return *this;
}
void TRuntimeProfileTree::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TRuntimeProfileTree(";
  out << "nodes=" << to_string(nodes);
  out << ")";
}

} // namespace
