/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ShortCircuit_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace starrocks {


TKeyLiteralExpr::~TKeyLiteralExpr() noexcept {
}

TKeyLiteralExpr::TKeyLiteralExpr() noexcept {
}

void TKeyLiteralExpr::__set_literal_exprs(const std::vector< ::starrocks::TExpr> & val) {
  this->literal_exprs = val;
__isset.literal_exprs = true;
}
std::ostream& operator<<(std::ostream& out, const TKeyLiteralExpr& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TKeyLiteralExpr::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->literal_exprs.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->literal_exprs.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += this->literal_exprs[_i4].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.literal_exprs = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TKeyLiteralExpr::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TKeyLiteralExpr");

  if (this->__isset.literal_exprs) {
    xfer += oprot->writeFieldBegin("literal_exprs", ::apache::thrift::protocol::T_LIST, 1);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->literal_exprs.size()));
      std::vector< ::starrocks::TExpr> ::const_iterator _iter5;
      for (_iter5 = this->literal_exprs.begin(); _iter5 != this->literal_exprs.end(); ++_iter5)
      {
        xfer += (*_iter5).write(oprot);
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TKeyLiteralExpr &a, TKeyLiteralExpr &b) {
  using ::std::swap;
  swap(a.literal_exprs, b.literal_exprs);
  swap(a.__isset, b.__isset);
}

bool TKeyLiteralExpr::operator==(const TKeyLiteralExpr & rhs) const
{
  if (__isset.literal_exprs != rhs.__isset.literal_exprs)
    return false;
  else if (__isset.literal_exprs && !(literal_exprs == rhs.literal_exprs))
    return false;
  return true;
}

TKeyLiteralExpr::TKeyLiteralExpr(const TKeyLiteralExpr& other6) {
  literal_exprs = other6.literal_exprs;
  __isset = other6.__isset;
}
TKeyLiteralExpr& TKeyLiteralExpr::operator=(const TKeyLiteralExpr& other7) {
  literal_exprs = other7.literal_exprs;
  __isset = other7.__isset;
  return *this;
}
void TKeyLiteralExpr::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TKeyLiteralExpr(";
  out << "literal_exprs="; (__isset.literal_exprs ? (out << to_string(literal_exprs)) : (out << "<null>"));
  out << ")";
}


TExecShortCircuitParams::~TExecShortCircuitParams() noexcept {
}

TExecShortCircuitParams::TExecShortCircuitParams() noexcept
   : is_binary_row(0),
     enable_profile(0) {
}

void TExecShortCircuitParams::__set_desc_tbl(const  ::starrocks::TDescriptorTable& val) {
  this->desc_tbl = val;
__isset.desc_tbl = true;
}

void TExecShortCircuitParams::__set_plan(const  ::starrocks::TPlan& val) {
  this->plan = val;
__isset.plan = true;
}

void TExecShortCircuitParams::__set_output_exprs(const std::vector< ::starrocks::TExpr> & val) {
  this->output_exprs = val;
__isset.output_exprs = true;
}

void TExecShortCircuitParams::__set_data_sink(const  ::starrocks::TDataSink& val) {
  this->data_sink = val;
__isset.data_sink = true;
}

void TExecShortCircuitParams::__set_is_binary_row(const bool val) {
  this->is_binary_row = val;
__isset.is_binary_row = true;
}

void TExecShortCircuitParams::__set_enable_profile(const bool val) {
  this->enable_profile = val;
__isset.enable_profile = true;
}

void TExecShortCircuitParams::__set_scan_range(const  ::starrocks::TScanRange& val) {
  this->scan_range = val;
__isset.scan_range = true;
}

void TExecShortCircuitParams::__set_key_literal_exprs(const std::vector<TKeyLiteralExpr> & val) {
  this->key_literal_exprs = val;
__isset.key_literal_exprs = true;
}

void TExecShortCircuitParams::__set_tablet_ids(const std::vector<int64_t> & val) {
  this->tablet_ids = val;
__isset.tablet_ids = true;
}

void TExecShortCircuitParams::__set_versions(const std::vector<std::string> & val) {
  this->versions = val;
__isset.versions = true;
}
std::ostream& operator<<(std::ostream& out, const TExecShortCircuitParams& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TExecShortCircuitParams::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->desc_tbl.read(iprot);
          this->__isset.desc_tbl = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->plan.read(iprot);
          this->__isset.plan = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->output_exprs.clear();
            uint32_t _size8;
            ::apache::thrift::protocol::TType _etype11;
            xfer += iprot->readListBegin(_etype11, _size8);
            this->output_exprs.resize(_size8);
            uint32_t _i12;
            for (_i12 = 0; _i12 < _size8; ++_i12)
            {
              xfer += this->output_exprs[_i12].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.output_exprs = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->data_sink.read(iprot);
          this->__isset.data_sink = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->is_binary_row);
          this->__isset.is_binary_row = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->enable_profile);
          this->__isset.enable_profile = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->scan_range.read(iprot);
          this->__isset.scan_range = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->key_literal_exprs.clear();
            uint32_t _size13;
            ::apache::thrift::protocol::TType _etype16;
            xfer += iprot->readListBegin(_etype16, _size13);
            this->key_literal_exprs.resize(_size13);
            uint32_t _i17;
            for (_i17 = 0; _i17 < _size13; ++_i17)
            {
              xfer += this->key_literal_exprs[_i17].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.key_literal_exprs = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->tablet_ids.clear();
            uint32_t _size18;
            ::apache::thrift::protocol::TType _etype21;
            xfer += iprot->readListBegin(_etype21, _size18);
            this->tablet_ids.resize(_size18);
            uint32_t _i22;
            for (_i22 = 0; _i22 < _size18; ++_i22)
            {
              xfer += iprot->readI64(this->tablet_ids[_i22]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.tablet_ids = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->versions.clear();
            uint32_t _size23;
            ::apache::thrift::protocol::TType _etype26;
            xfer += iprot->readListBegin(_etype26, _size23);
            this->versions.resize(_size23);
            uint32_t _i27;
            for (_i27 = 0; _i27 < _size23; ++_i27)
            {
              xfer += iprot->readString(this->versions[_i27]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.versions = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TExecShortCircuitParams::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TExecShortCircuitParams");

  if (this->__isset.desc_tbl) {
    xfer += oprot->writeFieldBegin("desc_tbl", ::apache::thrift::protocol::T_STRUCT, 1);
    xfer += this->desc_tbl.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.plan) {
    xfer += oprot->writeFieldBegin("plan", ::apache::thrift::protocol::T_STRUCT, 2);
    xfer += this->plan.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.output_exprs) {
    xfer += oprot->writeFieldBegin("output_exprs", ::apache::thrift::protocol::T_LIST, 3);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->output_exprs.size()));
      std::vector< ::starrocks::TExpr> ::const_iterator _iter28;
      for (_iter28 = this->output_exprs.begin(); _iter28 != this->output_exprs.end(); ++_iter28)
      {
        xfer += (*_iter28).write(oprot);
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.data_sink) {
    xfer += oprot->writeFieldBegin("data_sink", ::apache::thrift::protocol::T_STRUCT, 4);
    xfer += this->data_sink.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.is_binary_row) {
    xfer += oprot->writeFieldBegin("is_binary_row", ::apache::thrift::protocol::T_BOOL, 5);
    xfer += oprot->writeBool(this->is_binary_row);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.enable_profile) {
    xfer += oprot->writeFieldBegin("enable_profile", ::apache::thrift::protocol::T_BOOL, 6);
    xfer += oprot->writeBool(this->enable_profile);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.scan_range) {
    xfer += oprot->writeFieldBegin("scan_range", ::apache::thrift::protocol::T_STRUCT, 7);
    xfer += this->scan_range.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.key_literal_exprs) {
    xfer += oprot->writeFieldBegin("key_literal_exprs", ::apache::thrift::protocol::T_LIST, 8);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->key_literal_exprs.size()));
      std::vector<TKeyLiteralExpr> ::const_iterator _iter29;
      for (_iter29 = this->key_literal_exprs.begin(); _iter29 != this->key_literal_exprs.end(); ++_iter29)
      {
        xfer += (*_iter29).write(oprot);
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.tablet_ids) {
    xfer += oprot->writeFieldBegin("tablet_ids", ::apache::thrift::protocol::T_LIST, 9);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>(this->tablet_ids.size()));
      std::vector<int64_t> ::const_iterator _iter30;
      for (_iter30 = this->tablet_ids.begin(); _iter30 != this->tablet_ids.end(); ++_iter30)
      {
        xfer += oprot->writeI64((*_iter30));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.versions) {
    xfer += oprot->writeFieldBegin("versions", ::apache::thrift::protocol::T_LIST, 10);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->versions.size()));
      std::vector<std::string> ::const_iterator _iter31;
      for (_iter31 = this->versions.begin(); _iter31 != this->versions.end(); ++_iter31)
      {
        xfer += oprot->writeString((*_iter31));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TExecShortCircuitParams &a, TExecShortCircuitParams &b) {
  using ::std::swap;
  swap(a.desc_tbl, b.desc_tbl);
  swap(a.plan, b.plan);
  swap(a.output_exprs, b.output_exprs);
  swap(a.data_sink, b.data_sink);
  swap(a.is_binary_row, b.is_binary_row);
  swap(a.enable_profile, b.enable_profile);
  swap(a.scan_range, b.scan_range);
  swap(a.key_literal_exprs, b.key_literal_exprs);
  swap(a.tablet_ids, b.tablet_ids);
  swap(a.versions, b.versions);
  swap(a.__isset, b.__isset);
}

bool TExecShortCircuitParams::operator==(const TExecShortCircuitParams & rhs) const
{
  if (__isset.desc_tbl != rhs.__isset.desc_tbl)
    return false;
  else if (__isset.desc_tbl && !(desc_tbl == rhs.desc_tbl))
    return false;
  if (__isset.plan != rhs.__isset.plan)
    return false;
  else if (__isset.plan && !(plan == rhs.plan))
    return false;
  if (__isset.output_exprs != rhs.__isset.output_exprs)
    return false;
  else if (__isset.output_exprs && !(output_exprs == rhs.output_exprs))
    return false;
  if (__isset.data_sink != rhs.__isset.data_sink)
    return false;
  else if (__isset.data_sink && !(data_sink == rhs.data_sink))
    return false;
  if (__isset.is_binary_row != rhs.__isset.is_binary_row)
    return false;
  else if (__isset.is_binary_row && !(is_binary_row == rhs.is_binary_row))
    return false;
  if (__isset.enable_profile != rhs.__isset.enable_profile)
    return false;
  else if (__isset.enable_profile && !(enable_profile == rhs.enable_profile))
    return false;
  if (__isset.scan_range != rhs.__isset.scan_range)
    return false;
  else if (__isset.scan_range && !(scan_range == rhs.scan_range))
    return false;
  if (__isset.key_literal_exprs != rhs.__isset.key_literal_exprs)
    return false;
  else if (__isset.key_literal_exprs && !(key_literal_exprs == rhs.key_literal_exprs))
    return false;
  if (__isset.tablet_ids != rhs.__isset.tablet_ids)
    return false;
  else if (__isset.tablet_ids && !(tablet_ids == rhs.tablet_ids))
    return false;
  if (__isset.versions != rhs.__isset.versions)
    return false;
  else if (__isset.versions && !(versions == rhs.versions))
    return false;
  return true;
}

TExecShortCircuitParams::TExecShortCircuitParams(const TExecShortCircuitParams& other32) {
  desc_tbl = other32.desc_tbl;
  plan = other32.plan;
  output_exprs = other32.output_exprs;
  data_sink = other32.data_sink;
  is_binary_row = other32.is_binary_row;
  enable_profile = other32.enable_profile;
  scan_range = other32.scan_range;
  key_literal_exprs = other32.key_literal_exprs;
  tablet_ids = other32.tablet_ids;
  versions = other32.versions;
  __isset = other32.__isset;
}
TExecShortCircuitParams& TExecShortCircuitParams::operator=(const TExecShortCircuitParams& other33) {
  desc_tbl = other33.desc_tbl;
  plan = other33.plan;
  output_exprs = other33.output_exprs;
  data_sink = other33.data_sink;
  is_binary_row = other33.is_binary_row;
  enable_profile = other33.enable_profile;
  scan_range = other33.scan_range;
  key_literal_exprs = other33.key_literal_exprs;
  tablet_ids = other33.tablet_ids;
  versions = other33.versions;
  __isset = other33.__isset;
  return *this;
}
void TExecShortCircuitParams::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TExecShortCircuitParams(";
  out << "desc_tbl="; (__isset.desc_tbl ? (out << to_string(desc_tbl)) : (out << "<null>"));
  out << ", " << "plan="; (__isset.plan ? (out << to_string(plan)) : (out << "<null>"));
  out << ", " << "output_exprs="; (__isset.output_exprs ? (out << to_string(output_exprs)) : (out << "<null>"));
  out << ", " << "data_sink="; (__isset.data_sink ? (out << to_string(data_sink)) : (out << "<null>"));
  out << ", " << "is_binary_row="; (__isset.is_binary_row ? (out << to_string(is_binary_row)) : (out << "<null>"));
  out << ", " << "enable_profile="; (__isset.enable_profile ? (out << to_string(enable_profile)) : (out << "<null>"));
  out << ", " << "scan_range="; (__isset.scan_range ? (out << to_string(scan_range)) : (out << "<null>"));
  out << ", " << "key_literal_exprs="; (__isset.key_literal_exprs ? (out << to_string(key_literal_exprs)) : (out << "<null>"));
  out << ", " << "tablet_ids="; (__isset.tablet_ids ? (out << to_string(tablet_ids)) : (out << "<null>"));
  out << ", " << "versions="; (__isset.versions ? (out << to_string(versions)) : (out << "<null>"));
  out << ")";
}

} // namespace
