/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef StarrocksExternalService_TYPES_H
#define StarrocksExternalService_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>
#include "Types_types.h"
#include "Status_types.h"


namespace starrocks {

class TScanOpenParams;

class TScanColumnDesc;

class TScanOpenResult;

class TScanNextBatchParams;

class TScanBatchResult;

class TScanCloseParams;

class TScanCloseResult;

typedef struct _TScanOpenParams__isset {
  _TScanOpenParams__isset() : batch_size(false), properties(false), limit(false), user(false), passwd(false), keep_alive_min(false), query_timeout(false), mem_limit(false) {}
  bool batch_size :1;
  bool properties :1;
  bool limit :1;
  bool user :1;
  bool passwd :1;
  bool keep_alive_min :1;
  bool query_timeout :1;
  bool mem_limit :1;
} _TScanOpenParams__isset;

class TScanOpenParams : public virtual ::apache::thrift::TBase {
 public:

  TScanOpenParams(const TScanOpenParams&);
  TScanOpenParams& operator=(const TScanOpenParams&);
  TScanOpenParams() noexcept;

  virtual ~TScanOpenParams() noexcept;
  std::string cluster;
  std::string database;
  std::string table;
  std::vector<int64_t>  tablet_ids;
  std::string opaqued_query_plan;
  int32_t batch_size;
  std::map<std::string, std::string>  properties;
  int64_t limit;
  std::string user;
  std::string passwd;
  int16_t keep_alive_min;
  int32_t query_timeout;
  int64_t mem_limit;

  _TScanOpenParams__isset __isset;

  void __set_cluster(const std::string& val);

  void __set_database(const std::string& val);

  void __set_table(const std::string& val);

  void __set_tablet_ids(const std::vector<int64_t> & val);

  void __set_opaqued_query_plan(const std::string& val);

  void __set_batch_size(const int32_t val);

  void __set_properties(const std::map<std::string, std::string> & val);

  void __set_limit(const int64_t val);

  void __set_user(const std::string& val);

  void __set_passwd(const std::string& val);

  void __set_keep_alive_min(const int16_t val);

  void __set_query_timeout(const int32_t val);

  void __set_mem_limit(const int64_t val);

  bool operator == (const TScanOpenParams & rhs) const;
  bool operator != (const TScanOpenParams &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TScanOpenParams & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TScanOpenParams &a, TScanOpenParams &b);

std::ostream& operator<<(std::ostream& out, const TScanOpenParams& obj);

typedef struct _TScanColumnDesc__isset {
  _TScanColumnDesc__isset() : name(false), type(false) {}
  bool name :1;
  bool type :1;
} _TScanColumnDesc__isset;

class TScanColumnDesc : public virtual ::apache::thrift::TBase {
 public:

  TScanColumnDesc(const TScanColumnDesc&);
  TScanColumnDesc& operator=(const TScanColumnDesc&);
  TScanColumnDesc() noexcept;

  virtual ~TScanColumnDesc() noexcept;
  std::string name;
  /**
   * 
   * @see com.starrocks.thrift.TPrimitiveType
   */
   ::starrocks::TPrimitiveType::type type;

  _TScanColumnDesc__isset __isset;

  void __set_name(const std::string& val);

  void __set_type(const  ::starrocks::TPrimitiveType::type val);

  bool operator == (const TScanColumnDesc & rhs) const;
  bool operator != (const TScanColumnDesc &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TScanColumnDesc & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TScanColumnDesc &a, TScanColumnDesc &b);

std::ostream& operator<<(std::ostream& out, const TScanColumnDesc& obj);

typedef struct _TScanOpenResult__isset {
  _TScanOpenResult__isset() : context_id(false), selected_columns(false) {}
  bool context_id :1;
  bool selected_columns :1;
} _TScanOpenResult__isset;

class TScanOpenResult : public virtual ::apache::thrift::TBase {
 public:

  TScanOpenResult(const TScanOpenResult&);
  TScanOpenResult& operator=(const TScanOpenResult&);
  TScanOpenResult() noexcept;

  virtual ~TScanOpenResult() noexcept;
   ::starrocks::TStatus status;
  std::string context_id;
  std::vector<TScanColumnDesc>  selected_columns;

  _TScanOpenResult__isset __isset;

  void __set_status(const  ::starrocks::TStatus& val);

  void __set_context_id(const std::string& val);

  void __set_selected_columns(const std::vector<TScanColumnDesc> & val);

  bool operator == (const TScanOpenResult & rhs) const;
  bool operator != (const TScanOpenResult &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TScanOpenResult & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TScanOpenResult &a, TScanOpenResult &b);

std::ostream& operator<<(std::ostream& out, const TScanOpenResult& obj);

typedef struct _TScanNextBatchParams__isset {
  _TScanNextBatchParams__isset() : context_id(false), offset(false) {}
  bool context_id :1;
  bool offset :1;
} _TScanNextBatchParams__isset;

class TScanNextBatchParams : public virtual ::apache::thrift::TBase {
 public:

  TScanNextBatchParams(const TScanNextBatchParams&);
  TScanNextBatchParams& operator=(const TScanNextBatchParams&);
  TScanNextBatchParams() noexcept;

  virtual ~TScanNextBatchParams() noexcept;
  std::string context_id;
  int64_t offset;

  _TScanNextBatchParams__isset __isset;

  void __set_context_id(const std::string& val);

  void __set_offset(const int64_t val);

  bool operator == (const TScanNextBatchParams & rhs) const;
  bool operator != (const TScanNextBatchParams &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TScanNextBatchParams & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TScanNextBatchParams &a, TScanNextBatchParams &b);

std::ostream& operator<<(std::ostream& out, const TScanNextBatchParams& obj);

typedef struct _TScanBatchResult__isset {
  _TScanBatchResult__isset() : eos(false), rows(false) {}
  bool eos :1;
  bool rows :1;
} _TScanBatchResult__isset;

class TScanBatchResult : public virtual ::apache::thrift::TBase {
 public:

  TScanBatchResult(const TScanBatchResult&);
  TScanBatchResult& operator=(const TScanBatchResult&);
  TScanBatchResult() noexcept;

  virtual ~TScanBatchResult() noexcept;
   ::starrocks::TStatus status;
  bool eos;
  std::string rows;

  _TScanBatchResult__isset __isset;

  void __set_status(const  ::starrocks::TStatus& val);

  void __set_eos(const bool val);

  void __set_rows(const std::string& val);

  bool operator == (const TScanBatchResult & rhs) const;
  bool operator != (const TScanBatchResult &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TScanBatchResult & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TScanBatchResult &a, TScanBatchResult &b);

std::ostream& operator<<(std::ostream& out, const TScanBatchResult& obj);

typedef struct _TScanCloseParams__isset {
  _TScanCloseParams__isset() : context_id(false) {}
  bool context_id :1;
} _TScanCloseParams__isset;

class TScanCloseParams : public virtual ::apache::thrift::TBase {
 public:

  TScanCloseParams(const TScanCloseParams&);
  TScanCloseParams& operator=(const TScanCloseParams&);
  TScanCloseParams() noexcept;

  virtual ~TScanCloseParams() noexcept;
  std::string context_id;

  _TScanCloseParams__isset __isset;

  void __set_context_id(const std::string& val);

  bool operator == (const TScanCloseParams & rhs) const;
  bool operator != (const TScanCloseParams &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TScanCloseParams & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TScanCloseParams &a, TScanCloseParams &b);

std::ostream& operator<<(std::ostream& out, const TScanCloseParams& obj);


class TScanCloseResult : public virtual ::apache::thrift::TBase {
 public:

  TScanCloseResult(const TScanCloseResult&);
  TScanCloseResult& operator=(const TScanCloseResult&);
  TScanCloseResult() noexcept;

  virtual ~TScanCloseResult() noexcept;
   ::starrocks::TStatus status;

  void __set_status(const  ::starrocks::TStatus& val);

  bool operator == (const TScanCloseResult & rhs) const;
  bool operator != (const TScanCloseResult &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TScanCloseResult & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TScanCloseResult &a, TScanCloseResult &b);

std::ostream& operator<<(std::ostream& out, const TScanCloseResult& obj);

} // namespace

#endif
