// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: status.proto
// Protobuf C++ Version: 6.33.0

#ifndef status_2eproto_2epb_2eh
#define status_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_status_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_status_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_status_2eproto;
}  // extern "C"
namespace starrocks {
class StatusPB;
struct StatusPBDefaultTypeInternal;
extern StatusPBDefaultTypeInternal _StatusPB_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull StatusPB_class_data_;
}  // namespace starrocks
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace starrocks {

// ===================================================================


// -------------------------------------------------------------------

class StatusPB final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:starrocks.StatusPB) */ {
 public:
  inline StatusPB() : StatusPB(nullptr) {}
  ~StatusPB() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(StatusPB* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(StatusPB));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StatusPB(::google::protobuf::internal::ConstantInitialized);

  inline StatusPB(const StatusPB& from) : StatusPB(nullptr, from) {}
  inline StatusPB(StatusPB&& from) noexcept
      : StatusPB(nullptr, ::std::move(from)) {}
  inline StatusPB& operator=(const StatusPB& from) {
    CopyFrom(from);
    return *this;
  }
  inline StatusPB& operator=(StatusPB&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StatusPB& default_instance() {
    return *reinterpret_cast<const StatusPB*>(
        &_StatusPB_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(StatusPB& a, StatusPB& b) { a.Swap(&b); }
  inline void Swap(StatusPB* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StatusPB* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StatusPB* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<StatusPB>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StatusPB& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StatusPB& from) { StatusPB::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(StatusPB* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "starrocks.StatusPB"; }

  explicit StatusPB(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  StatusPB(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const StatusPB& from);
  StatusPB(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, StatusPB&& from) noexcept
      : StatusPB(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kErrorMsgsFieldNumber = 2,
    kStatusCodeFieldNumber = 1,
  };
  // repeated string error_msgs = 2;
  int error_msgs_size() const;
  private:
  int _internal_error_msgs_size() const;

  public:
  void clear_error_msgs() ;
  const ::std::string& error_msgs(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_error_msgs(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_error_msgs(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_error_msgs();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_error_msgs(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& error_msgs() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_error_msgs();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_error_msgs() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_error_msgs();

  public:
  // required int32 status_code = 1;
  bool has_status_code() const;
  void clear_status_code() ;
  ::int32_t status_code() const;
  void set_status_code(::int32_t value);

  private:
  ::int32_t _internal_status_code() const;
  void _internal_set_status_code(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:starrocks.StatusPB)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const StatusPB& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> error_msgs_;
    ::int32_t status_code_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_status_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull StatusPB_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// StatusPB

// required int32 status_code = 1;
inline bool StatusPB::has_status_code() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void StatusPB::clear_status_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_code_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t StatusPB::status_code() const {
  // @@protoc_insertion_point(field_get:starrocks.StatusPB.status_code)
  return _internal_status_code();
}
inline void StatusPB::set_status_code(::int32_t value) {
  _internal_set_status_code(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:starrocks.StatusPB.status_code)
}
inline ::int32_t StatusPB::_internal_status_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_code_;
}
inline void StatusPB::_internal_set_status_code(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_code_ = value;
}

// repeated string error_msgs = 2;
inline int StatusPB::_internal_error_msgs_size() const {
  return _internal_error_msgs().size();
}
inline int StatusPB::error_msgs_size() const {
  return _internal_error_msgs_size();
}
inline void StatusPB::clear_error_msgs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_msgs_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL StatusPB::add_error_msgs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_error_msgs()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:starrocks.StatusPB.error_msgs)
  return _s;
}
inline const ::std::string& StatusPB::error_msgs(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:starrocks.StatusPB.error_msgs)
  return _internal_error_msgs().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL StatusPB::mutable_error_msgs(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:starrocks.StatusPB.error_msgs)
  return _internal_mutable_error_msgs()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void StatusPB::set_error_msgs(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_error_msgs()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:starrocks.StatusPB.error_msgs)
}
template <typename Arg_, typename... Args_>
inline void StatusPB::add_error_msgs(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_error_msgs(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:starrocks.StatusPB.error_msgs)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& StatusPB::error_msgs()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:starrocks.StatusPB.error_msgs)
  return _internal_error_msgs();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
StatusPB::mutable_error_msgs() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:starrocks.StatusPB.error_msgs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_error_msgs();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
StatusPB::_internal_error_msgs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_msgs_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
StatusPB::_internal_mutable_error_msgs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.error_msgs_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace starrocks


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // status_2eproto_2epb_2eh
