/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Types_constants.h"

namespace starrocks {

const TypesConstants g_Types_constants;

TypesConstants::TypesConstants() {
  TSNAPSHOT_REQ_VERSION1 = 3;

  TSNAPSHOT_REQ_VERSION2 = 4;

  TPREFER_SNAPSHOT_REQ_VERSION = 4;

}

} // namespace

