/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Types_TYPES_H
#define Types_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace starrocks {

struct TStorageType {
  enum type {
    ROW = 0,
    COLUMN = 1,
    COLUMN_WITH_ROW = 2
  };
};

extern const std::map<int, const char*> _TStorageType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TStorageType::type& val);

std::string to_string(const TStorageType::type& val);

struct TStorageMedium {
  enum type {
    HDD = 0,
    SSD = 1
  };
};

extern const std::map<int, const char*> _TStorageMedium_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TStorageMedium::type& val);

std::string to_string(const TStorageMedium::type& val);

struct TVarType {
  enum type {
    SESSION = 0,
    GLOBAL = 1,
    VERBOSE = 2
  };
};

extern const std::map<int, const char*> _TVarType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TVarType::type& val);

std::string to_string(const TVarType::type& val);

struct TPrimitiveType {
  enum type {
    INVALID_TYPE = 0,
    NULL_TYPE = 1,
    BOOLEAN = 2,
    TINYINT = 3,
    SMALLINT = 4,
    INT = 5,
    BIGINT = 6,
    FLOAT = 7,
    DOUBLE = 8,
    DATE = 9,
    DATETIME = 10,
    BINARY = 11,
    DECIMAL = 12,
    CHAR = 13,
    LARGEINT = 14,
    VARCHAR = 15,
    HLL = 16,
    DECIMALV2 = 17,
    TIME = 18,
    OBJECT = 19,
    PERCENTILE = 20,
    DECIMAL32 = 21,
    DECIMAL64 = 22,
    DECIMAL128 = 23,
    JSON = 24,
    FUNCTION = 25,
    VARBINARY = 26
  };
};

extern const std::map<int, const char*> _TPrimitiveType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TPrimitiveType::type& val);

std::string to_string(const TPrimitiveType::type& val);

struct TTypeNodeType {
  enum type {
    SCALAR = 0,
    ARRAY = 1,
    MAP = 2,
    STRUCT = 3
  };
};

extern const std::map<int, const char*> _TTypeNodeType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TTypeNodeType::type& val);

std::string to_string(const TTypeNodeType::type& val);

struct TAggregationType {
  enum type {
    SUM = 0,
    MAX = 1,
    MIN = 2,
    REPLACE = 3,
    HLL_UNION = 4,
    NONE = 5,
    BITMAP_UNION = 6,
    REPLACE_IF_NOT_NULL = 7,
    PERCENTILE_UNION = 8
  };
};

extern const std::map<int, const char*> _TAggregationType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TAggregationType::type& val);

std::string to_string(const TAggregationType::type& val);

struct TPushType {
  enum type {
    LOAD = 0,
    DELETE = 1,
    LOAD_DELETE = 2,
    LOAD_V2 = 3,
    CANCEL_DELETE = 4
  };
};

extern const std::map<int, const char*> _TPushType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TPushType::type& val);

std::string to_string(const TPushType::type& val);

struct TTaskType {
  enum type {
    CREATE = 0,
    DROP = 1,
    PUSH = 2,
    CLONE = 3,
    STORAGE_MEDIUM_MIGRATE = 4,
    ROLLUP = 5,
    SCHEMA_CHANGE = 6,
    CANCEL_DELETE = 7,
    MAKE_SNAPSHOT = 8,
    RELEASE_SNAPSHOT = 9,
    CHECK_CONSISTENCY = 10,
    UPLOAD = 11,
    DOWNLOAD = 12,
    CLEAR_REMOTE_FILE = 13,
    MOVE = 14,
    REALTIME_PUSH = 15,
    PUBLISH_VERSION = 16,
    CLEAR_ALTER_TASK = 17,
    CLEAR_TRANSACTION_TASK = 18,
    RECOVER_TABLET = 19,
    STREAM_LOAD = 20,
    UPDATE_TABLET_META_INFO = 21,
    ALTER = 22,
    INSTALL_PLUGIN = 23,
    UNINSTALL_PLUGIN = 24,
    DROP_AUTO_INCREMENT_MAP = 25,
    COMPACTION = 26,
    REMOTE_SNAPSHOT = 27,
    REPLICATE_SNAPSHOT = 28,
    UPDATE_SCHEMA = 29,
    NUM_TASK_TYPE = 30
  };
};

extern const std::map<int, const char*> _TTaskType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TTaskType::type& val);

std::string to_string(const TTaskType::type& val);

struct TStmtType {
  enum type {
    QUERY = 0,
    DDL = 1,
    DML = 2,
    EXPLAIN = 3
  };
};

extern const std::map<int, const char*> _TStmtType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TStmtType::type& val);

std::string to_string(const TStmtType::type& val);

struct TExplainLevel {
  enum type {
    NORMAL = 0,
    VERBOSE = 1,
    COSTS = 2
  };
};

extern const std::map<int, const char*> _TExplainLevel_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TExplainLevel::type& val);

std::string to_string(const TExplainLevel::type& val);

struct QueryState {
  enum type {
    CREATED = 0,
    INITIALIZED = 1,
    COMPILED = 2,
    RUNNING = 3,
    FINISHED = 4,
    EXCEPTION = 5
  };
};

extern const std::map<int, const char*> _QueryState_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const QueryState::type& val);

std::string to_string(const QueryState::type& val);

struct TFunctionType {
  enum type {
    SCALAR = 0,
    AGGREGATE = 1
  };
};

extern const std::map<int, const char*> _TFunctionType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TFunctionType::type& val);

std::string to_string(const TFunctionType::type& val);

struct TFunctionBinaryType {
  enum type {
    BUILTIN = 0,
    HIVE = 1,
    NATIVE = 2,
    IR = 3,
    SRJAR = 4
  };
};

extern const std::map<int, const char*> _TFunctionBinaryType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TFunctionBinaryType::type& val);

std::string to_string(const TFunctionBinaryType::type& val);

struct TLoadJobState {
  enum type {
    PENDING = 0,
    ETL = 1,
    LOADING = 2,
    FINISHED = 3,
    CANCELLED = 4
  };
};

extern const std::map<int, const char*> _TLoadJobState_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TLoadJobState::type& val);

std::string to_string(const TLoadJobState::type& val);

struct TEtlState {
  enum type {
    RUNNING = 0,
    FINISHED = 1,
    CANCELLED = 2,
    UNKNOWN = 3
  };
};

extern const std::map<int, const char*> _TEtlState_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TEtlState::type& val);

std::string to_string(const TEtlState::type& val);

struct TTableType {
  enum type {
    MYSQL_TABLE = 0,
    OLAP_TABLE = 1,
    SCHEMA_TABLE = 2,
    KUDU_TABLE = 3,
    BROKER_TABLE = 4,
    ES_TABLE = 5,
    HDFS_TABLE = 6,
    ICEBERG_TABLE = 7,
    HUDI_TABLE = 8,
    JDBC_TABLE = 9,
    PAIMON_TABLE = 10,
    VIEW = 20,
    MATERIALIZED_VIEW = 21,
    FILE_TABLE = 22,
    DELTALAKE_TABLE = 23,
    TABLE_FUNCTION_TABLE = 24,
    ODPS_TABLE = 25,
    LOGICAL_ICEBERG_METADATA_TABLE = 26
  };
};

extern const std::map<int, const char*> _TTableType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TTableType::type& val);

std::string to_string(const TTableType::type& val);

struct TKeysType {
  enum type {
    PRIMARY_KEYS = 0,
    DUP_KEYS = 1,
    UNIQUE_KEYS = 2,
    AGG_KEYS = 3
  };
};

extern const std::map<int, const char*> _TKeysType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TKeysType::type& val);

std::string to_string(const TKeysType::type& val);

struct TPriority {
  enum type {
    NORMAL = 0,
    HIGH = 1
  };
};

extern const std::map<int, const char*> _TPriority_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TPriority::type& val);

std::string to_string(const TPriority::type& val);

struct TExportState {
  enum type {
    RUNNING = 0,
    FINISHED = 1,
    CANCELLED = 2,
    UNKNOWN = 3
  };
};

extern const std::map<int, const char*> _TExportState_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TExportState::type& val);

std::string to_string(const TExportState::type& val);

struct TFileType {
  enum type {
    FILE_LOCAL = 0,
    FILE_BROKER = 1,
    FILE_STREAM = 2
  };
};

extern const std::map<int, const char*> _TFileType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TFileType::type& val);

std::string to_string(const TFileType::type& val);

struct TLoadType {
  enum type {
    MANUAL_LOAD = 0,
    ROUTINE_LOAD = 1,
    MINI_LOAD = 2
  };
};

extern const std::map<int, const char*> _TLoadType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TLoadType::type& val);

std::string to_string(const TLoadType::type& val);

struct TLoadSourceType {
  enum type {
    RAW = 0,
    KAFKA = 1,
    PULSAR = 2
  };
};

extern const std::map<int, const char*> _TLoadSourceType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TLoadSourceType::type& val);

std::string to_string(const TLoadSourceType::type& val);

struct TOpType {
  enum type {
    UPSERT = 0,
    DELETE = 1
  };
};

extern const std::map<int, const char*> _TOpType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TOpType::type& val);

std::string to_string(const TOpType::type& val);

struct TCompressionType {
  enum type {
    UNKNOWN_COMPRESSION = 0,
    DEFAULT_COMPRESSION = 1,
    NO_COMPRESSION = 2,
    SNAPPY = 3,
    LZ4 = 4,
    LZ4_FRAME = 5,
    ZLIB = 6,
    ZSTD = 7,
    GZIP = 8,
    DEFLATE = 9,
    BZIP2 = 10,
    LZO = 11,
    BROTLI = 12
  };
};

extern const std::map<int, const char*> _TCompressionType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TCompressionType::type& val);

std::string to_string(const TCompressionType::type& val);

struct TWriteQuorumType {
  enum type {
    ONE = 0,
    MAJORITY = 1,
    ALL = 2
  };
};

extern const std::map<int, const char*> _TWriteQuorumType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TWriteQuorumType::type& val);

std::string to_string(const TWriteQuorumType::type& val);

struct StreamSourceType {
  enum type {
    BINLOG = 0,
    KAFKA = 1
  };
};

extern const std::map<int, const char*> _StreamSourceType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const StreamSourceType::type& val);

std::string to_string(const StreamSourceType::type& val);

struct TPartialUpdateMode {
  enum type {
    UNKNOWN_MODE = 0,
    ROW_MODE = 1,
    COLUMN_UPSERT_MODE = 2,
    AUTO_MODE = 3,
    COLUMN_UPDATE_MODE = 4
  };
};

extern const std::map<int, const char*> _TPartialUpdateMode_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TPartialUpdateMode::type& val);

std::string to_string(const TPartialUpdateMode::type& val);

struct TRunMode {
  enum type {
    SHARED_NOTHING = 0,
    SHARED_DATA = 1,
    HYBRID = 2
  };
};

extern const std::map<int, const char*> _TRunMode_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TRunMode::type& val);

std::string to_string(const TRunMode::type& val);

struct TTxnType {
  enum type {
    TXN_NORMAL = 0,
    TXN_REPLICATION = 1
  };
};

extern const std::map<int, const char*> _TTxnType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TTxnType::type& val);

std::string to_string(const TTxnType::type& val);

typedef int64_t TTimestamp;

typedef int32_t TPlanNodeId;

typedef int32_t TTupleId;

typedef int32_t TSlotId;

typedef int64_t TTableId;

typedef int64_t TTabletId;

typedef int64_t TVersion;

typedef int64_t TVersionHash;

typedef int32_t TSchemaHash;

typedef int32_t TPort;

typedef int64_t TCount;

typedef int64_t TSize;

typedef int32_t TClusterId;

typedef int64_t TEpoch;

typedef int64_t TTransactionId;

typedef int64_t TPartitionId;

class TScalarType;

class TStructField;

class TTypeNode;

class TTypeDesc;

class TColumnType;

class TNetworkAddress;

class TUniqueId;

class TFunctionName;

class TScalarFunction;

class TAggregateFunction;

class TTableFunction;

class TFunction;

class TBackend;

class TResourceInfo;

class TTabletCommitInfo;

class TTabletFailInfo;

class TUserRoles;

class TUserIdentity;

class TBinlogOffset;

class TIcebergColumnStats;

class TIcebergDataFile;

class THiveFileInfo;

class TSinkCommitInfo;

class TSnapshotInfo;

typedef struct _TScalarType__isset {
  _TScalarType__isset() : len(false), precision(false), scale(false) {}
  bool len :1;
  bool precision :1;
  bool scale :1;
} _TScalarType__isset;

class TScalarType : public virtual ::apache::thrift::TBase {
 public:

  TScalarType(const TScalarType&) noexcept;
  TScalarType& operator=(const TScalarType&) noexcept;
  TScalarType() noexcept;

  virtual ~TScalarType() noexcept;
  /**
   * 
   * @see TPrimitiveType
   */
  TPrimitiveType::type type;
  int32_t len;
  int32_t precision;
  int32_t scale;

  _TScalarType__isset __isset;

  void __set_type(const TPrimitiveType::type val);

  void __set_len(const int32_t val);

  void __set_precision(const int32_t val);

  void __set_scale(const int32_t val);

  bool operator == (const TScalarType & rhs) const;
  bool operator != (const TScalarType &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TScalarType & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TScalarType &a, TScalarType &b);

std::ostream& operator<<(std::ostream& out, const TScalarType& obj);

typedef struct _TStructField__isset {
  _TStructField__isset() : name(false), comment(false), id(false) {}
  bool name :1;
  bool comment :1;
  bool id :1;
} _TStructField__isset;

class TStructField : public virtual ::apache::thrift::TBase {
 public:

  TStructField(const TStructField&);
  TStructField& operator=(const TStructField&);
  TStructField() noexcept;

  virtual ~TStructField() noexcept;
  std::string name;
  std::string comment;
  int32_t id;

  _TStructField__isset __isset;

  void __set_name(const std::string& val);

  void __set_comment(const std::string& val);

  void __set_id(const int32_t val);

  bool operator == (const TStructField & rhs) const;
  bool operator != (const TStructField &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TStructField & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TStructField &a, TStructField &b);

std::ostream& operator<<(std::ostream& out, const TStructField& obj);

typedef struct _TTypeNode__isset {
  _TTypeNode__isset() : scalar_type(false), struct_fields(false), is_named(false) {}
  bool scalar_type :1;
  bool struct_fields :1;
  bool is_named :1;
} _TTypeNode__isset;

class TTypeNode : public virtual ::apache::thrift::TBase {
 public:

  TTypeNode(const TTypeNode&);
  TTypeNode& operator=(const TTypeNode&);
  TTypeNode() noexcept;

  virtual ~TTypeNode() noexcept;
  /**
   * 
   * @see TTypeNodeType
   */
  TTypeNodeType::type type;
  TScalarType scalar_type;
  std::vector<TStructField>  struct_fields;
  bool is_named;

  _TTypeNode__isset __isset;

  void __set_type(const TTypeNodeType::type val);

  void __set_scalar_type(const TScalarType& val);

  void __set_struct_fields(const std::vector<TStructField> & val);

  void __set_is_named(const bool val);

  bool operator == (const TTypeNode & rhs) const;
  bool operator != (const TTypeNode &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TTypeNode & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TTypeNode &a, TTypeNode &b);

std::ostream& operator<<(std::ostream& out, const TTypeNode& obj);

typedef struct _TTypeDesc__isset {
  _TTypeDesc__isset() : types(false) {}
  bool types :1;
} _TTypeDesc__isset;

class TTypeDesc : public virtual ::apache::thrift::TBase {
 public:

  TTypeDesc(const TTypeDesc&);
  TTypeDesc& operator=(const TTypeDesc&);
  TTypeDesc() noexcept;

  virtual ~TTypeDesc() noexcept;
  std::vector<TTypeNode>  types;

  _TTypeDesc__isset __isset;

  void __set_types(const std::vector<TTypeNode> & val);

  bool operator == (const TTypeDesc & rhs) const;
  bool operator != (const TTypeDesc &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TTypeDesc & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TTypeDesc &a, TTypeDesc &b);

std::ostream& operator<<(std::ostream& out, const TTypeDesc& obj);

typedef struct _TColumnType__isset {
  _TColumnType__isset() : len(false), index_len(false), precision(false), scale(false) {}
  bool len :1;
  bool index_len :1;
  bool precision :1;
  bool scale :1;
} _TColumnType__isset;

class TColumnType : public virtual ::apache::thrift::TBase {
 public:

  TColumnType(const TColumnType&) noexcept;
  TColumnType& operator=(const TColumnType&) noexcept;
  TColumnType() noexcept;

  virtual ~TColumnType() noexcept;
  /**
   * 
   * @see TPrimitiveType
   */
  TPrimitiveType::type type;
  int32_t len;
  int32_t index_len;
  int32_t precision;
  int32_t scale;

  _TColumnType__isset __isset;

  void __set_type(const TPrimitiveType::type val);

  void __set_len(const int32_t val);

  void __set_index_len(const int32_t val);

  void __set_precision(const int32_t val);

  void __set_scale(const int32_t val);

  bool operator == (const TColumnType & rhs) const;
  bool operator != (const TColumnType &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TColumnType & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TColumnType &a, TColumnType &b);

std::ostream& operator<<(std::ostream& out, const TColumnType& obj);


class TNetworkAddress : public virtual ::apache::thrift::TBase {
 public:

  TNetworkAddress(const TNetworkAddress&);
  TNetworkAddress& operator=(const TNetworkAddress&);
  TNetworkAddress() noexcept;

  virtual ~TNetworkAddress() noexcept;
  std::string hostname;
  int32_t port;

  void __set_hostname(const std::string& val);

  void __set_port(const int32_t val);

  bool operator == (const TNetworkAddress & rhs) const;
  bool operator != (const TNetworkAddress &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TNetworkAddress & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TNetworkAddress &a, TNetworkAddress &b);

std::ostream& operator<<(std::ostream& out, const TNetworkAddress& obj);


class TUniqueId : public virtual ::apache::thrift::TBase {
 public:

  TUniqueId(const TUniqueId&) noexcept;
  TUniqueId& operator=(const TUniqueId&) noexcept;
  TUniqueId() noexcept;

  virtual ~TUniqueId() noexcept;
  int64_t hi;
  int64_t lo;

  void __set_hi(const int64_t val);

  void __set_lo(const int64_t val);

  bool operator == (const TUniqueId & rhs) const;
  bool operator != (const TUniqueId &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TUniqueId & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TUniqueId &a, TUniqueId &b);

std::ostream& operator<<(std::ostream& out, const TUniqueId& obj);

typedef struct _TFunctionName__isset {
  _TFunctionName__isset() : db_name(false) {}
  bool db_name :1;
} _TFunctionName__isset;

class TFunctionName : public virtual ::apache::thrift::TBase {
 public:

  TFunctionName(const TFunctionName&);
  TFunctionName& operator=(const TFunctionName&);
  TFunctionName() noexcept;

  virtual ~TFunctionName() noexcept;
  std::string db_name;
  std::string function_name;

  _TFunctionName__isset __isset;

  void __set_db_name(const std::string& val);

  void __set_function_name(const std::string& val);

  bool operator == (const TFunctionName & rhs) const;
  bool operator != (const TFunctionName &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TFunctionName & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TFunctionName &a, TFunctionName &b);

std::ostream& operator<<(std::ostream& out, const TFunctionName& obj);

typedef struct _TScalarFunction__isset {
  _TScalarFunction__isset() : prepare_fn_symbol(false), close_fn_symbol(false) {}
  bool prepare_fn_symbol :1;
  bool close_fn_symbol :1;
} _TScalarFunction__isset;

class TScalarFunction : public virtual ::apache::thrift::TBase {
 public:

  TScalarFunction(const TScalarFunction&);
  TScalarFunction& operator=(const TScalarFunction&);
  TScalarFunction() noexcept;

  virtual ~TScalarFunction() noexcept;
  std::string symbol;
  std::string prepare_fn_symbol;
  std::string close_fn_symbol;

  _TScalarFunction__isset __isset;

  void __set_symbol(const std::string& val);

  void __set_prepare_fn_symbol(const std::string& val);

  void __set_close_fn_symbol(const std::string& val);

  bool operator == (const TScalarFunction & rhs) const;
  bool operator != (const TScalarFunction &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TScalarFunction & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TScalarFunction &a, TScalarFunction &b);

std::ostream& operator<<(std::ostream& out, const TScalarFunction& obj);

typedef struct _TAggregateFunction__isset {
  _TAggregateFunction__isset() : update_fn_symbol(false), init_fn_symbol(false), serialize_fn_symbol(false), merge_fn_symbol(false), finalize_fn_symbol(false), get_value_fn_symbol(false), remove_fn_symbol(false), is_analytic_only_fn(true), symbol(false), is_asc_order(false), nulls_first(false), is_distinct(true) {}
  bool update_fn_symbol :1;
  bool init_fn_symbol :1;
  bool serialize_fn_symbol :1;
  bool merge_fn_symbol :1;
  bool finalize_fn_symbol :1;
  bool get_value_fn_symbol :1;
  bool remove_fn_symbol :1;
  bool is_analytic_only_fn :1;
  bool symbol :1;
  bool is_asc_order :1;
  bool nulls_first :1;
  bool is_distinct :1;
} _TAggregateFunction__isset;

class TAggregateFunction : public virtual ::apache::thrift::TBase {
 public:

  TAggregateFunction(const TAggregateFunction&);
  TAggregateFunction& operator=(const TAggregateFunction&);
  TAggregateFunction() noexcept;

  virtual ~TAggregateFunction() noexcept;
  TTypeDesc intermediate_type;
  std::string update_fn_symbol;
  std::string init_fn_symbol;
  std::string serialize_fn_symbol;
  std::string merge_fn_symbol;
  std::string finalize_fn_symbol;
  std::string get_value_fn_symbol;
  std::string remove_fn_symbol;
  bool is_analytic_only_fn;
  std::string symbol;
  std::vector<bool>  is_asc_order;
  std::vector<bool>  nulls_first;
  bool is_distinct;

  _TAggregateFunction__isset __isset;

  void __set_intermediate_type(const TTypeDesc& val);

  void __set_update_fn_symbol(const std::string& val);

  void __set_init_fn_symbol(const std::string& val);

  void __set_serialize_fn_symbol(const std::string& val);

  void __set_merge_fn_symbol(const std::string& val);

  void __set_finalize_fn_symbol(const std::string& val);

  void __set_get_value_fn_symbol(const std::string& val);

  void __set_remove_fn_symbol(const std::string& val);

  void __set_is_analytic_only_fn(const bool val);

  void __set_symbol(const std::string& val);

  void __set_is_asc_order(const std::vector<bool> & val);

  void __set_nulls_first(const std::vector<bool> & val);

  void __set_is_distinct(const bool val);

  bool operator == (const TAggregateFunction & rhs) const;
  bool operator != (const TAggregateFunction &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TAggregateFunction & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TAggregateFunction &a, TAggregateFunction &b);

std::ostream& operator<<(std::ostream& out, const TAggregateFunction& obj);

typedef struct _TTableFunction__isset {
  _TTableFunction__isset() : symbol(false), is_left_join(false) {}
  bool symbol :1;
  bool is_left_join :1;
} _TTableFunction__isset;

class TTableFunction : public virtual ::apache::thrift::TBase {
 public:

  TTableFunction(const TTableFunction&);
  TTableFunction& operator=(const TTableFunction&);
  TTableFunction() noexcept;

  virtual ~TTableFunction() noexcept;
  std::vector<TTypeDesc>  ret_types;
  std::string symbol;
  bool is_left_join;

  _TTableFunction__isset __isset;

  void __set_ret_types(const std::vector<TTypeDesc> & val);

  void __set_symbol(const std::string& val);

  void __set_is_left_join(const bool val);

  bool operator == (const TTableFunction & rhs) const;
  bool operator != (const TTableFunction &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TTableFunction & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TTableFunction &a, TTableFunction &b);

std::ostream& operator<<(std::ostream& out, const TTableFunction& obj);

typedef struct _TFunction__isset {
  _TFunction__isset() : comment(false), signature(false), hdfs_location(false), scalar_fn(false), aggregate_fn(false), id(false), checksum(false), fid(false), table_fn(false), could_apply_dict_optimize(false), ignore_nulls(false), isolated(false) {}
  bool comment :1;
  bool signature :1;
  bool hdfs_location :1;
  bool scalar_fn :1;
  bool aggregate_fn :1;
  bool id :1;
  bool checksum :1;
  bool fid :1;
  bool table_fn :1;
  bool could_apply_dict_optimize :1;
  bool ignore_nulls :1;
  bool isolated :1;
} _TFunction__isset;

class TFunction : public virtual ::apache::thrift::TBase {
 public:

  TFunction(const TFunction&);
  TFunction& operator=(const TFunction&);
  TFunction() noexcept;

  virtual ~TFunction() noexcept;
  TFunctionName name;
  /**
   * 
   * @see TFunctionBinaryType
   */
  TFunctionBinaryType::type binary_type;
  std::vector<TTypeDesc>  arg_types;
  TTypeDesc ret_type;
  bool has_var_args;
  std::string comment;
  std::string signature;
  std::string hdfs_location;
  TScalarFunction scalar_fn;
  TAggregateFunction aggregate_fn;
  int64_t id;
  std::string checksum;
  int64_t fid;
  TTableFunction table_fn;
  bool could_apply_dict_optimize;
  bool ignore_nulls;
  bool isolated;

  _TFunction__isset __isset;

  void __set_name(const TFunctionName& val);

  void __set_binary_type(const TFunctionBinaryType::type val);

  void __set_arg_types(const std::vector<TTypeDesc> & val);

  void __set_ret_type(const TTypeDesc& val);

  void __set_has_var_args(const bool val);

  void __set_comment(const std::string& val);

  void __set_signature(const std::string& val);

  void __set_hdfs_location(const std::string& val);

  void __set_scalar_fn(const TScalarFunction& val);

  void __set_aggregate_fn(const TAggregateFunction& val);

  void __set_id(const int64_t val);

  void __set_checksum(const std::string& val);

  void __set_fid(const int64_t val);

  void __set_table_fn(const TTableFunction& val);

  void __set_could_apply_dict_optimize(const bool val);

  void __set_ignore_nulls(const bool val);

  void __set_isolated(const bool val);

  bool operator == (const TFunction & rhs) const;
  bool operator != (const TFunction &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TFunction & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TFunction &a, TFunction &b);

std::ostream& operator<<(std::ostream& out, const TFunction& obj);


class TBackend : public virtual ::apache::thrift::TBase {
 public:

  TBackend(const TBackend&);
  TBackend& operator=(const TBackend&);
  TBackend() noexcept;

  virtual ~TBackend() noexcept;
  std::string host;
  TPort be_port;
  TPort http_port;

  void __set_host(const std::string& val);

  void __set_be_port(const TPort val);

  void __set_http_port(const TPort val);

  bool operator == (const TBackend & rhs) const;
  bool operator != (const TBackend &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBackend & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBackend &a, TBackend &b);

std::ostream& operator<<(std::ostream& out, const TBackend& obj);


class TResourceInfo : public virtual ::apache::thrift::TBase {
 public:

  TResourceInfo(const TResourceInfo&);
  TResourceInfo& operator=(const TResourceInfo&);
  TResourceInfo() noexcept;

  virtual ~TResourceInfo() noexcept;
  std::string user;
  std::string group;

  void __set_user(const std::string& val);

  void __set_group(const std::string& val);

  bool operator == (const TResourceInfo & rhs) const;
  bool operator != (const TResourceInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TResourceInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TResourceInfo &a, TResourceInfo &b);

std::ostream& operator<<(std::ostream& out, const TResourceInfo& obj);

typedef struct _TTabletCommitInfo__isset {
  _TTabletCommitInfo__isset() : invalid_dict_cache_columns(false), valid_dict_cache_columns(false), valid_dict_collected_versions(false) {}
  bool invalid_dict_cache_columns :1;
  bool valid_dict_cache_columns :1;
  bool valid_dict_collected_versions :1;
} _TTabletCommitInfo__isset;

class TTabletCommitInfo : public virtual ::apache::thrift::TBase {
 public:

  TTabletCommitInfo(const TTabletCommitInfo&);
  TTabletCommitInfo& operator=(const TTabletCommitInfo&);
  TTabletCommitInfo() noexcept;

  virtual ~TTabletCommitInfo() noexcept;
  int64_t tabletId;
  int64_t backendId;
  std::vector<std::string>  invalid_dict_cache_columns;
  std::vector<std::string>  valid_dict_cache_columns;
  std::vector<int64_t>  valid_dict_collected_versions;

  _TTabletCommitInfo__isset __isset;

  void __set_tabletId(const int64_t val);

  void __set_backendId(const int64_t val);

  void __set_invalid_dict_cache_columns(const std::vector<std::string> & val);

  void __set_valid_dict_cache_columns(const std::vector<std::string> & val);

  void __set_valid_dict_collected_versions(const std::vector<int64_t> & val);

  bool operator == (const TTabletCommitInfo & rhs) const;
  bool operator != (const TTabletCommitInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TTabletCommitInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TTabletCommitInfo &a, TTabletCommitInfo &b);

std::ostream& operator<<(std::ostream& out, const TTabletCommitInfo& obj);

typedef struct _TTabletFailInfo__isset {
  _TTabletFailInfo__isset() : tabletId(false), backendId(false) {}
  bool tabletId :1;
  bool backendId :1;
} _TTabletFailInfo__isset;

class TTabletFailInfo : public virtual ::apache::thrift::TBase {
 public:

  TTabletFailInfo(const TTabletFailInfo&) noexcept;
  TTabletFailInfo& operator=(const TTabletFailInfo&) noexcept;
  TTabletFailInfo() noexcept;

  virtual ~TTabletFailInfo() noexcept;
  int64_t tabletId;
  int64_t backendId;

  _TTabletFailInfo__isset __isset;

  void __set_tabletId(const int64_t val);

  void __set_backendId(const int64_t val);

  bool operator == (const TTabletFailInfo & rhs) const;
  bool operator != (const TTabletFailInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TTabletFailInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TTabletFailInfo &a, TTabletFailInfo &b);

std::ostream& operator<<(std::ostream& out, const TTabletFailInfo& obj);

typedef struct _TUserRoles__isset {
  _TUserRoles__isset() : role_id_list(false) {}
  bool role_id_list :1;
} _TUserRoles__isset;

class TUserRoles : public virtual ::apache::thrift::TBase {
 public:

  TUserRoles(const TUserRoles&);
  TUserRoles& operator=(const TUserRoles&);
  TUserRoles() noexcept;

  virtual ~TUserRoles() noexcept;
  std::vector<int64_t>  role_id_list;

  _TUserRoles__isset __isset;

  void __set_role_id_list(const std::vector<int64_t> & val);

  bool operator == (const TUserRoles & rhs) const;
  bool operator != (const TUserRoles &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TUserRoles & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TUserRoles &a, TUserRoles &b);

std::ostream& operator<<(std::ostream& out, const TUserRoles& obj);

typedef struct _TUserIdentity__isset {
  _TUserIdentity__isset() : username(false), host(false), is_domain(false), is_ephemeral(false), current_role_ids(false) {}
  bool username :1;
  bool host :1;
  bool is_domain :1;
  bool is_ephemeral :1;
  bool current_role_ids :1;
} _TUserIdentity__isset;

class TUserIdentity : public virtual ::apache::thrift::TBase {
 public:

  TUserIdentity(const TUserIdentity&);
  TUserIdentity& operator=(const TUserIdentity&);
  TUserIdentity() noexcept;

  virtual ~TUserIdentity() noexcept;
  std::string username;
  std::string host;
  bool is_domain;
  bool is_ephemeral;
  TUserRoles current_role_ids;

  _TUserIdentity__isset __isset;

  void __set_username(const std::string& val);

  void __set_host(const std::string& val);

  void __set_is_domain(const bool val);

  void __set_is_ephemeral(const bool val);

  void __set_current_role_ids(const TUserRoles& val);

  bool operator == (const TUserIdentity & rhs) const;
  bool operator != (const TUserIdentity &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TUserIdentity & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TUserIdentity &a, TUserIdentity &b);

std::ostream& operator<<(std::ostream& out, const TUserIdentity& obj);

typedef struct _TBinlogOffset__isset {
  _TBinlogOffset__isset() : tablet_id(false), version(false), lsn(false) {}
  bool tablet_id :1;
  bool version :1;
  bool lsn :1;
} _TBinlogOffset__isset;

class TBinlogOffset : public virtual ::apache::thrift::TBase {
 public:

  TBinlogOffset(const TBinlogOffset&) noexcept;
  TBinlogOffset& operator=(const TBinlogOffset&) noexcept;
  TBinlogOffset() noexcept;

  virtual ~TBinlogOffset() noexcept;
  TTabletId tablet_id;
  TVersion version;
  int64_t lsn;

  _TBinlogOffset__isset __isset;

  void __set_tablet_id(const TTabletId val);

  void __set_version(const TVersion val);

  void __set_lsn(const int64_t val);

  bool operator == (const TBinlogOffset & rhs) const;
  bool operator != (const TBinlogOffset &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TBinlogOffset & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TBinlogOffset &a, TBinlogOffset &b);

std::ostream& operator<<(std::ostream& out, const TBinlogOffset& obj);

typedef struct _TIcebergColumnStats__isset {
  _TIcebergColumnStats__isset() : column_sizes(false), value_counts(false), null_value_counts(false), nan_value_counts(false), lower_bounds(false), upper_bounds(false) {}
  bool column_sizes :1;
  bool value_counts :1;
  bool null_value_counts :1;
  bool nan_value_counts :1;
  bool lower_bounds :1;
  bool upper_bounds :1;
} _TIcebergColumnStats__isset;

class TIcebergColumnStats : public virtual ::apache::thrift::TBase {
 public:

  TIcebergColumnStats(const TIcebergColumnStats&);
  TIcebergColumnStats& operator=(const TIcebergColumnStats&);
  TIcebergColumnStats() noexcept;

  virtual ~TIcebergColumnStats() noexcept;
  std::map<int32_t, int64_t>  column_sizes;
  std::map<int32_t, int64_t>  value_counts;
  std::map<int32_t, int64_t>  null_value_counts;
  std::map<int32_t, int64_t>  nan_value_counts;
  std::map<int32_t, std::string>  lower_bounds;
  std::map<int32_t, std::string>  upper_bounds;

  _TIcebergColumnStats__isset __isset;

  void __set_column_sizes(const std::map<int32_t, int64_t> & val);

  void __set_value_counts(const std::map<int32_t, int64_t> & val);

  void __set_null_value_counts(const std::map<int32_t, int64_t> & val);

  void __set_nan_value_counts(const std::map<int32_t, int64_t> & val);

  void __set_lower_bounds(const std::map<int32_t, std::string> & val);

  void __set_upper_bounds(const std::map<int32_t, std::string> & val);

  bool operator == (const TIcebergColumnStats & rhs) const;
  bool operator != (const TIcebergColumnStats &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TIcebergColumnStats & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TIcebergColumnStats &a, TIcebergColumnStats &b);

std::ostream& operator<<(std::ostream& out, const TIcebergColumnStats& obj);

typedef struct _TIcebergDataFile__isset {
  _TIcebergDataFile__isset() : path(false), format(false), record_count(false), file_size_in_bytes(false), partition_path(false), split_offsets(false), column_stats(false) {}
  bool path :1;
  bool format :1;
  bool record_count :1;
  bool file_size_in_bytes :1;
  bool partition_path :1;
  bool split_offsets :1;
  bool column_stats :1;
} _TIcebergDataFile__isset;

class TIcebergDataFile : public virtual ::apache::thrift::TBase {
 public:

  TIcebergDataFile(const TIcebergDataFile&);
  TIcebergDataFile& operator=(const TIcebergDataFile&);
  TIcebergDataFile() noexcept;

  virtual ~TIcebergDataFile() noexcept;
  std::string path;
  std::string format;
  int64_t record_count;
  int64_t file_size_in_bytes;
  std::string partition_path;
  std::vector<int64_t>  split_offsets;
  TIcebergColumnStats column_stats;

  _TIcebergDataFile__isset __isset;

  void __set_path(const std::string& val);

  void __set_format(const std::string& val);

  void __set_record_count(const int64_t val);

  void __set_file_size_in_bytes(const int64_t val);

  void __set_partition_path(const std::string& val);

  void __set_split_offsets(const std::vector<int64_t> & val);

  void __set_column_stats(const TIcebergColumnStats& val);

  bool operator == (const TIcebergDataFile & rhs) const;
  bool operator != (const TIcebergDataFile &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TIcebergDataFile & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TIcebergDataFile &a, TIcebergDataFile &b);

std::ostream& operator<<(std::ostream& out, const TIcebergDataFile& obj);

typedef struct _THiveFileInfo__isset {
  _THiveFileInfo__isset() : file_name(false), partition_path(false), record_count(false), file_size_in_bytes(false) {}
  bool file_name :1;
  bool partition_path :1;
  bool record_count :1;
  bool file_size_in_bytes :1;
} _THiveFileInfo__isset;

class THiveFileInfo : public virtual ::apache::thrift::TBase {
 public:

  THiveFileInfo(const THiveFileInfo&);
  THiveFileInfo& operator=(const THiveFileInfo&);
  THiveFileInfo() noexcept;

  virtual ~THiveFileInfo() noexcept;
  std::string file_name;
  std::string partition_path;
  int64_t record_count;
  int64_t file_size_in_bytes;

  _THiveFileInfo__isset __isset;

  void __set_file_name(const std::string& val);

  void __set_partition_path(const std::string& val);

  void __set_record_count(const int64_t val);

  void __set_file_size_in_bytes(const int64_t val);

  bool operator == (const THiveFileInfo & rhs) const;
  bool operator != (const THiveFileInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const THiveFileInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(THiveFileInfo &a, THiveFileInfo &b);

std::ostream& operator<<(std::ostream& out, const THiveFileInfo& obj);

typedef struct _TSinkCommitInfo__isset {
  _TSinkCommitInfo__isset() : iceberg_data_file(false), hive_file_info(false), is_overwrite(false), staging_dir(false) {}
  bool iceberg_data_file :1;
  bool hive_file_info :1;
  bool is_overwrite :1;
  bool staging_dir :1;
} _TSinkCommitInfo__isset;

class TSinkCommitInfo : public virtual ::apache::thrift::TBase {
 public:

  TSinkCommitInfo(const TSinkCommitInfo&);
  TSinkCommitInfo& operator=(const TSinkCommitInfo&);
  TSinkCommitInfo() noexcept;

  virtual ~TSinkCommitInfo() noexcept;
  TIcebergDataFile iceberg_data_file;
  THiveFileInfo hive_file_info;
  bool is_overwrite;
  std::string staging_dir;

  _TSinkCommitInfo__isset __isset;

  void __set_iceberg_data_file(const TIcebergDataFile& val);

  void __set_hive_file_info(const THiveFileInfo& val);

  void __set_is_overwrite(const bool val);

  void __set_staging_dir(const std::string& val);

  bool operator == (const TSinkCommitInfo & rhs) const;
  bool operator != (const TSinkCommitInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TSinkCommitInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TSinkCommitInfo &a, TSinkCommitInfo &b);

std::ostream& operator<<(std::ostream& out, const TSinkCommitInfo& obj);

typedef struct _TSnapshotInfo__isset {
  _TSnapshotInfo__isset() : backend(false), snapshot_path(false), incremental_snapshot(false) {}
  bool backend :1;
  bool snapshot_path :1;
  bool incremental_snapshot :1;
} _TSnapshotInfo__isset;

class TSnapshotInfo : public virtual ::apache::thrift::TBase {
 public:

  TSnapshotInfo(const TSnapshotInfo&);
  TSnapshotInfo& operator=(const TSnapshotInfo&);
  TSnapshotInfo() noexcept;

  virtual ~TSnapshotInfo() noexcept;
  TBackend backend;
  std::string snapshot_path;
  bool incremental_snapshot;

  _TSnapshotInfo__isset __isset;

  void __set_backend(const TBackend& val);

  void __set_snapshot_path(const std::string& val);

  void __set_incremental_snapshot(const bool val);

  bool operator == (const TSnapshotInfo & rhs) const;
  bool operator != (const TSnapshotInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TSnapshotInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TSnapshotInfo &a, TSnapshotInfo &b);

std::ostream& operator<<(std::ostream& out, const TSnapshotInfo& obj);

} // namespace

#endif
